-- name: BatchUpsertDisputedMarkets :exec
INSERT INTO polymarket_disputed_market (
  market_key,
  market_id,
  condition_id,
  slug,
  event_id,
  event_slug,
  question,
  description,
  resolution_source,
  image,
  icon,
  uma_resolution_status,
  uma_resolution_statuses,
  outcomes,
  outcome_prices,
  clob_token_ids,
  active,
  closed,
  archived,
  restricted,
  enable_order_book,
  volume,
  volume_num,
  liquidity_num,
  volume_24hr,
  volume_1wk,
  volume_1mo,
  volume_1yr,
  spread,
  best_bid,
  best_ask,
  last_trade_price,
  tags,
  raw,
  fetched_at,
  last_seen_at
)
SELECT
  unnest(sqlc.arg('market_keys')::text[]),
  unnest(sqlc.arg('market_ids')::text[]),
  unnest(sqlc.arg('condition_ids')::text[]),
  unnest(sqlc.arg('slugs')::text[]),
  unnest(sqlc.arg('event_ids')::text[]),
  unnest(sqlc.arg('event_slugs')::text[]),
  unnest(sqlc.arg('questions')::text[]),
  unnest(sqlc.arg('descriptions')::text[]),
  unnest(sqlc.arg('resolution_sources')::text[]),
  unnest(sqlc.arg('images')::text[]),
  unnest(sqlc.arg('icons')::text[]),
  unnest(sqlc.arg('uma_resolution_status_values')::text[]),
  unnest(sqlc.arg('uma_resolution_statuses_values')::text[]),
  unnest(sqlc.arg('outcomes_values')::text[]),
  unnest(sqlc.arg('outcome_prices_values')::text[]),
  unnest(sqlc.arg('clob_token_ids_values')::text[]),
  unnest(sqlc.arg('active_values')::boolean[]),
  unnest(sqlc.arg('closed_values')::boolean[]),
  unnest(sqlc.arg('archived_values')::boolean[]),
  unnest(sqlc.arg('restricted_values')::boolean[]),
  unnest(sqlc.arg('enable_order_book_values')::boolean[]),
  unnest(sqlc.arg('volume_values')::text[]),
  unnest(sqlc.arg('volume_num_values')::double precision[]),
  unnest(sqlc.arg('liquidity_num_values')::double precision[]),
  unnest(sqlc.arg('volume_24hr_values')::double precision[]),
  unnest(sqlc.arg('volume_1wk_values')::double precision[]),
  unnest(sqlc.arg('volume_1mo_values')::double precision[]),
  unnest(sqlc.arg('volume_1yr_values')::double precision[]),
  unnest(sqlc.arg('spread_values')::double precision[]),
  unnest(sqlc.arg('best_bid_values')::double precision[]),
  unnest(sqlc.arg('best_ask_values')::double precision[]),
  unnest(sqlc.arg('last_trade_price_values')::double precision[]),
  unnest(sqlc.arg('tags_values')::jsonb[]),
  unnest(sqlc.arg('raw_values')::jsonb[]),
  unnest(sqlc.arg('fetched_at_values')::timestamptz[]),
  unnest(sqlc.arg('last_seen_at_values')::timestamptz[])
ON CONFLICT (market_key) DO UPDATE
SET market_id = EXCLUDED.market_id,
  condition_id = EXCLUDED.condition_id,
  slug = EXCLUDED.slug,
  event_id = EXCLUDED.event_id,
  event_slug = EXCLUDED.event_slug,
  question = EXCLUDED.question,
  description = EXCLUDED.description,
  resolution_source = EXCLUDED.resolution_source,
  image = EXCLUDED.image,
  icon = EXCLUDED.icon,
  uma_resolution_status = EXCLUDED.uma_resolution_status,
  uma_resolution_statuses = EXCLUDED.uma_resolution_statuses,
  outcomes = EXCLUDED.outcomes,
  outcome_prices = EXCLUDED.outcome_prices,
  clob_token_ids = EXCLUDED.clob_token_ids,
  active = EXCLUDED.active,
  closed = EXCLUDED.closed,
  archived = EXCLUDED.archived,
  restricted = EXCLUDED.restricted,
  enable_order_book = EXCLUDED.enable_order_book,
  volume = EXCLUDED.volume,
  volume_num = EXCLUDED.volume_num,
  liquidity_num = EXCLUDED.liquidity_num,
  volume_24hr = EXCLUDED.volume_24hr,
  volume_1wk = EXCLUDED.volume_1wk,
  volume_1mo = EXCLUDED.volume_1mo,
  volume_1yr = EXCLUDED.volume_1yr,
  spread = EXCLUDED.spread,
  best_bid = EXCLUDED.best_bid,
  best_ask = EXCLUDED.best_ask,
  last_trade_price = EXCLUDED.last_trade_price,
  tags = EXCLUDED.tags,
  raw = EXCLUDED.raw,
  fetched_at = EXCLUDED.fetched_at,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = now();

-- name: DeleteDisputedMarketsNotSeenSince :execrows
DELETE FROM polymarket_disputed_market
WHERE last_seen_at < @last_seen_at;

-- name: ListDisputedMarkets :many
SELECT
  market_key,
  market_id,
  condition_id,
  slug,
  event_id,
  event_slug,
  question,
  image,
  icon,
  uma_resolution_status,
  uma_resolution_statuses,
  active,
  closed,
  enable_order_book,
  volume_num,
  liquidity_num,
  volume_24hr,
  spread,
  best_bid,
  best_ask,
  last_trade_price,
  fetched_at,
  last_seen_at
FROM polymarket_disputed_market
ORDER BY volume_24hr DESC, volume_num DESC, market_key
LIMIT sqlc.arg('limit');
