-- name: BatchUpsertSportsLiveEvents :exec
INSERT INTO polymarket_sports_live_event (
  event_key,
  event_id,
  ticker,
  slug,
  title,
  description,
  resolution_source,
  start_date,
  creation_date,
  end_date,
  start_time,
  created_at_gamma,
  updated_at_gamma,
  image,
  icon,
  active,
  closed,
  archived,
  featured,
  restricted,
  live,
  ended,
  liquidity,
  volume,
  open_interest,
  category,
  score,
  period,
  elapsed,
  finished_timestamp,
  game_id,
  event_date,
  game_status,
  comment_count,
  sport,
  teams,
  tags,
  raw,
  fetched_at,
  last_seen_at
)
SELECT
  unnest(sqlc.arg('event_keys')::text[]),
  unnest(sqlc.arg('event_ids')::text[]),
  unnest(sqlc.arg('tickers')::text[]),
  unnest(sqlc.arg('slugs')::text[]),
  unnest(sqlc.arg('titles')::text[]),
  unnest(sqlc.arg('descriptions')::text[]),
  unnest(sqlc.arg('resolution_sources')::text[]),
  unnest(sqlc.arg('start_date_values')::timestamptz[]),
  unnest(sqlc.arg('creation_date_values')::timestamptz[]),
  unnest(sqlc.arg('end_date_values')::timestamptz[]),
  unnest(sqlc.arg('start_time_values')::timestamptz[]),
  unnest(sqlc.arg('created_at_gamma_values')::timestamptz[]),
  unnest(sqlc.arg('updated_at_gamma_values')::timestamptz[]),
  unnest(sqlc.arg('images')::text[]),
  unnest(sqlc.arg('icons')::text[]),
  unnest(sqlc.arg('active_values')::boolean[]),
  unnest(sqlc.arg('closed_values')::boolean[]),
  unnest(sqlc.arg('archived_values')::boolean[]),
  unnest(sqlc.arg('featured_values')::boolean[]),
  unnest(sqlc.arg('restricted_values')::boolean[]),
  unnest(sqlc.arg('live_values')::boolean[]),
  unnest(sqlc.arg('ended_values')::boolean[]),
  unnest(sqlc.arg('liquidity_values')::double precision[]),
  unnest(sqlc.arg('volume_values')::double precision[]),
  unnest(sqlc.arg('open_interest_values')::double precision[]),
  unnest(sqlc.arg('categories')::text[]),
  unnest(sqlc.arg('scores')::text[]),
  unnest(sqlc.arg('periods')::text[]),
  unnest(sqlc.arg('elapsed_values')::text[]),
  unnest(sqlc.arg('finished_timestamps')::text[]),
  unnest(sqlc.arg('game_id_values')::bigint[]),
  unnest(sqlc.arg('event_dates')::text[]),
  unnest(sqlc.arg('game_statuses')::text[]),
  unnest(sqlc.arg('comment_count_values')::bigint[]),
  unnest(sqlc.arg('sport_values')::jsonb[]),
  unnest(sqlc.arg('teams_values')::jsonb[]),
  unnest(sqlc.arg('tags_values')::jsonb[]),
  unnest(sqlc.arg('raw_values')::jsonb[]),
  unnest(sqlc.arg('fetched_at_values')::timestamptz[]),
  unnest(sqlc.arg('last_seen_at_values')::timestamptz[])
ON CONFLICT (event_key) DO UPDATE
SET event_id = EXCLUDED.event_id,
  ticker = EXCLUDED.ticker,
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  resolution_source = EXCLUDED.resolution_source,
  start_date = EXCLUDED.start_date,
  creation_date = EXCLUDED.creation_date,
  end_date = EXCLUDED.end_date,
  start_time = EXCLUDED.start_time,
  created_at_gamma = EXCLUDED.created_at_gamma,
  updated_at_gamma = EXCLUDED.updated_at_gamma,
  image = EXCLUDED.image,
  icon = EXCLUDED.icon,
  active = EXCLUDED.active,
  closed = EXCLUDED.closed,
  archived = EXCLUDED.archived,
  featured = EXCLUDED.featured,
  restricted = EXCLUDED.restricted,
  live = EXCLUDED.live,
  ended = EXCLUDED.ended,
  liquidity = EXCLUDED.liquidity,
  volume = EXCLUDED.volume,
  open_interest = EXCLUDED.open_interest,
  category = EXCLUDED.category,
  score = EXCLUDED.score,
  period = EXCLUDED.period,
  elapsed = EXCLUDED.elapsed,
  finished_timestamp = EXCLUDED.finished_timestamp,
  game_id = EXCLUDED.game_id,
  event_date = EXCLUDED.event_date,
  game_status = EXCLUDED.game_status,
  comment_count = EXCLUDED.comment_count,
  sport = EXCLUDED.sport,
  teams = EXCLUDED.teams,
  tags = EXCLUDED.tags,
  raw = EXCLUDED.raw,
  fetched_at = EXCLUDED.fetched_at,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = now();

-- name: BatchUpsertSportsLiveMarkets :exec
INSERT INTO polymarket_sports_live_market (
  market_key,
  event_key,
  event_id,
  event_slug,
  market_id,
  condition_id,
  slug,
  question,
  title,
  description,
  resolution_source,
  sports_market_type,
  group_item_title,
  image,
  icon,
  outcomes,
  outcome_prices,
  clob_token_ids,
  active,
  closed,
  archived,
  restricted,
  enable_order_book,
  volume,
  volume_num,
  liquidity_num,
  volume_24hr,
  volume_1wk,
  volume_1mo,
  volume_1yr,
  spread,
  best_bid,
  best_ask,
  last_trade_price,
  start_date,
  end_date,
  created_at_gamma,
  updated_at_gamma,
  tags,
  raw,
  fetched_at,
  last_seen_at
)
SELECT
  unnest(sqlc.arg('market_keys')::text[]),
  unnest(sqlc.arg('event_keys')::text[]),
  unnest(sqlc.arg('event_ids')::text[]),
  unnest(sqlc.arg('event_slugs')::text[]),
  unnest(sqlc.arg('market_ids')::text[]),
  unnest(sqlc.arg('condition_ids')::text[]),
  unnest(sqlc.arg('slugs')::text[]),
  unnest(sqlc.arg('questions')::text[]),
  unnest(sqlc.arg('titles')::text[]),
  unnest(sqlc.arg('descriptions')::text[]),
  unnest(sqlc.arg('resolution_sources')::text[]),
  unnest(sqlc.arg('sports_market_types')::text[]),
  unnest(sqlc.arg('group_item_titles')::text[]),
  unnest(sqlc.arg('images')::text[]),
  unnest(sqlc.arg('icons')::text[]),
  unnest(sqlc.arg('outcomes_values')::text[]),
  unnest(sqlc.arg('outcome_prices_values')::text[]),
  unnest(sqlc.arg('clob_token_ids_values')::text[]),
  unnest(sqlc.arg('active_values')::boolean[]),
  unnest(sqlc.arg('closed_values')::boolean[]),
  unnest(sqlc.arg('archived_values')::boolean[]),
  unnest(sqlc.arg('restricted_values')::boolean[]),
  unnest(sqlc.arg('enable_order_book_values')::boolean[]),
  unnest(sqlc.arg('volume_values')::text[]),
  unnest(sqlc.arg('volume_num_values')::double precision[]),
  unnest(sqlc.arg('liquidity_num_values')::double precision[]),
  unnest(sqlc.arg('volume_24hr_values')::double precision[]),
  unnest(sqlc.arg('volume_1wk_values')::double precision[]),
  unnest(sqlc.arg('volume_1mo_values')::double precision[]),
  unnest(sqlc.arg('volume_1yr_values')::double precision[]),
  unnest(sqlc.arg('spread_values')::double precision[]),
  unnest(sqlc.arg('best_bid_values')::double precision[]),
  unnest(sqlc.arg('best_ask_values')::double precision[]),
  unnest(sqlc.arg('last_trade_price_values')::double precision[]),
  unnest(sqlc.arg('start_date_values')::timestamptz[]),
  unnest(sqlc.arg('end_date_values')::timestamptz[]),
  unnest(sqlc.arg('created_at_gamma_values')::timestamptz[]),
  unnest(sqlc.arg('updated_at_gamma_values')::timestamptz[]),
  unnest(sqlc.arg('tags_values')::jsonb[]),
  unnest(sqlc.arg('raw_values')::jsonb[]),
  unnest(sqlc.arg('fetched_at_values')::timestamptz[]),
  unnest(sqlc.arg('last_seen_at_values')::timestamptz[])
ON CONFLICT (market_key) DO UPDATE
SET event_key = EXCLUDED.event_key,
  event_id = EXCLUDED.event_id,
  event_slug = EXCLUDED.event_slug,
  market_id = EXCLUDED.market_id,
  condition_id = EXCLUDED.condition_id,
  slug = EXCLUDED.slug,
  question = EXCLUDED.question,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  resolution_source = EXCLUDED.resolution_source,
  sports_market_type = EXCLUDED.sports_market_type,
  group_item_title = EXCLUDED.group_item_title,
  image = EXCLUDED.image,
  icon = EXCLUDED.icon,
  outcomes = EXCLUDED.outcomes,
  outcome_prices = EXCLUDED.outcome_prices,
  clob_token_ids = EXCLUDED.clob_token_ids,
  active = EXCLUDED.active,
  closed = EXCLUDED.closed,
  archived = EXCLUDED.archived,
  restricted = EXCLUDED.restricted,
  enable_order_book = EXCLUDED.enable_order_book,
  volume = EXCLUDED.volume,
  volume_num = EXCLUDED.volume_num,
  liquidity_num = EXCLUDED.liquidity_num,
  volume_24hr = EXCLUDED.volume_24hr,
  volume_1wk = EXCLUDED.volume_1wk,
  volume_1mo = EXCLUDED.volume_1mo,
  volume_1yr = EXCLUDED.volume_1yr,
  spread = EXCLUDED.spread,
  best_bid = EXCLUDED.best_bid,
  best_ask = EXCLUDED.best_ask,
  last_trade_price = EXCLUDED.last_trade_price,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  created_at_gamma = EXCLUDED.created_at_gamma,
  updated_at_gamma = EXCLUDED.updated_at_gamma,
  tags = EXCLUDED.tags,
  raw = EXCLUDED.raw,
  fetched_at = EXCLUDED.fetched_at,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = now();

-- name: DeleteSportsLiveMarketsNotSeenSince :execrows
DELETE FROM polymarket_sports_live_market
WHERE last_seen_at < @last_seen_at;

-- name: DeleteSportsLiveEventsNotSeenSince :execrows
DELETE FROM polymarket_sports_live_event
WHERE last_seen_at < @last_seen_at;

-- name: ListSportsLiveEvents :many
SELECT
  event.event_key,
  event.event_id,
  event.slug,
  event.title,
  COALESCE(NULLIF(event.image, ''), event.icon)::text AS image,
  event.score,
  event.period,
  event.elapsed,
  event.game_status,
  event.start_time,
  event.updated_at_gamma,
  event.liquidity,
  event.volume,
  COUNT(market.market_key)::bigint AS market_count,
  event.teams,
  event.fetched_at,
  event.last_seen_at
FROM polymarket_sports_live_event AS event
LEFT JOIN polymarket_sports_live_market AS market ON market.event_key = event.event_key
GROUP BY event.event_key
ORDER BY event.volume DESC, event.liquidity DESC, event.updated_at_gamma DESC NULLS LAST, event.event_key
LIMIT sqlc.arg('limit');

-- name: ListSportsLiveMarketsByEventKeys :many
SELECT
  market.event_key,
  market.market_key,
  market.condition_id,
  market.slug,
  market.sports_market_type,
  COALESCE(NULLIF(market.question, ''), market.title)::text AS question,
  market.outcomes,
  market.outcome_prices,
  market.best_bid,
  market.best_ask,
  market.last_trade_price,
  market.spread,
  market.liquidity_num,
  market.volume_num,
  market.updated_at_gamma
FROM polymarket_sports_live_market AS market
WHERE market.event_key = ANY(sqlc.arg('event_keys')::text[])
  AND lower(market.sports_market_type) = 'moneyline'
ORDER BY market.event_key, market.liquidity_num DESC, market.volume_num DESC, market.market_key;

-- name: GetPolymarketSyncState :one
SELECT last_success_at
FROM polymarket_sync_state
WHERE sync_name = @sync_name;

-- name: UpsertPolymarketSyncState :exec
INSERT INTO polymarket_sync_state (sync_name, last_success_at)
VALUES (@sync_name, @last_success_at)
ON CONFLICT (sync_name) DO UPDATE
SET last_success_at = EXCLUDED.last_success_at,
  updated_at = now();
