apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: quay.io/useryege/athena
  newName: docker.io/yege6776/athena
  newTag: latest

resources:
- ./server
- ./config
- ./redis
