// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OperationLogDelivery struct {
	EventID       pgtype.UUID
	State         string
	FailureCount  int64
	NextAttemptAt pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	ReasonCode    pgtype.Text
}

type OperationLogEntryVersion struct {
	OperationID         pgtype.UUID
	VisibleFromSeq      int64
	VisibleToSeq        pgtype.Int8
	StartedAt           pgtype.Timestamptz
	FinishedAt          pgtype.Timestamptz
	ActorAccountID      pgtype.UUID
	ActorUsername       pgtype.Text
	ActorRole           string
	Realm               string
	CredentialKind      string
	ModuleCode          string
	ActionCode          string
	Outcome             string
	Observation         string
	TargetAccountID     pgtype.UUID
	PrimaryResourceType pgtype.Text
	PrimaryResourceID   pgtype.Text
	RequestID           pgtype.UUID
	ParentOperationID   pgtype.UUID
	BusinessRequestID   pgtype.Text
	DurationMs          pgtype.Int8
	Detail              []byte
	SourceEventIds      []pgtype.UUID
}

type OperationLogEvent struct {
	EventID       pgtype.UUID
	IngestID      pgtype.Int8
	OperationID   pgtype.UUID
	Phase         string
	ProducerID    pgtype.UUID
	SchemaVersion int32
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Payload       []byte
	PayloadHash   []byte
}

type OperationLogProducerStatus struct {
	ProducerID             pgtype.UUID
	StartedAt              pgtype.Timestamptz
	LastSeenAt             pgtype.Timestamptz
	StoppedAt              pgtype.Timestamptz
	SnapshotNo             int64
	AttemptedEvents        int64
	ConfirmedEvents        int64
	UnconfirmedEvents      int64
	InvalidEvents          int64
	CapacityRejectedEvents int64
	InFlightEvents         int64
	LastFailureAt          pgtype.Timestamptz
	LastFailureCode        pgtype.Text
	LastRecoveredAt        pgtype.Timestamptz
	LastConfirmedAt        pgtype.Timestamptz
	PersistenceReachable   pgtype.Bool
}

type OperationLogPublication struct {
	SingletonID     int32
	LastSeq         int64
	LastPublishedAt pgtype.Timestamptz
}
