//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1alpha1

func (*ManagedOODisputeItem) ProtoMessage() {}

func (*ManagedOOProposalItem) ProtoMessage() {}

func (*MarketRadarHotMarketItem) ProtoMessage() {}

func (*MarketRadarHotMarketTokenItem) ProtoMessage() {}

func (*MarketRadarMoverMarketItem) ProtoMessage() {}

func (*MarketRadarMoverTokenItem) ProtoMessage() {}

func (*MarketRadarMoverWindowItem) ProtoMessage() {}

func (*MarketRadarRealtimeMarketItem) ProtoMessage() {}

func (*MarketRadarRealtimeTokenItem) ProtoMessage() {}

func (*MarketRadarRealtimeWindowItem) ProtoMessage() {}

func (*NotificationDeliveryDetail) ProtoMessage() {}

func (*NotificationDeliveryItem) ProtoMessage() {}

func (*NotificationStatus) ProtoMessage() {}

func (*SportsHistoryEventCardItem) ProtoMessage() {}

func (*SportsHistoryPriceHistorySeriesItem) ProtoMessage() {}

func (*SportsHistorySyncStatus) ProtoMessage() {}

func (*SportsLiveEventCardItem) ProtoMessage() {}

func (*SportsLiveMarketCardItem) ProtoMessage() {}

func (*SportsLivePriceHistorySeriesItem) ProtoMessage() {}

func (*SportsTeamItem) ProtoMessage() {}

func (*TokenAveObservation) ProtoMessage() {}

func (*TokenAvePair) ProtoMessage() {}

func (*TokenAveToken) ProtoMessage() {}

func (*TokenChain) ProtoMessage() {}

func (*TokenChainCheckpoint) ProtoMessage() {}

func (*TokenChainPair) ProtoMessage() {}

func (*TokenChainPairLiquidity) ProtoMessage() {}

func (*TokenChainProcessingAttempt) ProtoMessage() {}

func (*TokenChainProcessingSummary) ProtoMessage() {}

func (*TokenChainStateObservation) ProtoMessage() {}

func (*TokenChainToken) ProtoMessage() {}

func (*TokenCollectionSchedule) ProtoMessage() {}

func (*TokenCollectionTask) ProtoMessage() {}

func (*TokenContractCode) ProtoMessage() {}

func (*TokenContractCodeBlocklistEntry) ProtoMessage() {}

func (*TokenContractSourceObservation) ProtoMessage() {}

func (*TokenNodeStatus) ProtoMessage() {}

func (*TokenProject) ProtoMessage() {}

func (*TokenProjectDetail) ProtoMessage() {}

func (*TokenProjectInitialRecipient) ProtoMessage() {}

func (*TokenProjectListItem) ProtoMessage() {}

func (*TokenProjectObservation) ProtoMessage() {}

func (*TokenProjectPairRiskSummary) ProtoMessage() {}

func (*TokenProjectRelatedWallet) ProtoMessage() {}

func (*TokenProjectReportEvaluationSummary) ProtoMessage() {}

func (*TokenProjectReportRiskSummary) ProtoMessage() {}

func (*TokenProjectReportSummary) ProtoMessage() {}

func (*TokenProjectSwapActivity) ProtoMessage() {}

func (*TokenProjectSwapAsset) ProtoMessage() {}

func (*TokenProjectSwapBlock) ProtoMessage() {}

func (*TokenProjectSwapEvent) ProtoMessage() {}

func (*TokenProjectSwapPairActivity) ProtoMessage() {}

func (*TokenProjectTrendPoint) ProtoMessage() {}

func (*TokenProjectTrendSeries) ProtoMessage() {}

func (*TokenProjectTrends) ProtoMessage() {}

func (*TokenReportRevision) ProtoMessage() {}

func (*TokenResearchState) ProtoMessage() {}

func (*TokenRuntimeConfiguration) ProtoMessage() {}

func (*TokenSelection) ProtoMessage() {}

func (*TokenSimulationResult) ProtoMessage() {}

func (*TokenWalletAssetState) ProtoMessage() {}

func (*TokenWalletBlocklistEntry) ProtoMessage() {}

func (*TokenWalletNormalTransaction) ProtoMessage() {}

func (*TokenWalletTransactionCount) ProtoMessage() {}

func (*WalletItem) ProtoMessage() {}

func (*WalletStatus) ProtoMessage() {}

func (*WormMarketsEventItem) ProtoMessage() {}

func (*WormMarketsMarginPositionEstimateItem) ProtoMessage() {}

func (*WormMarketsMarketItem) ProtoMessage() {}
