//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1alpha1

func (*PairV2State) ProtoMessage() {}

func (*ProjectAnalysisState) ProtoMessage() {}

func (*ProjectMeta) ProtoMessage() {}

func (*ProjectSimulateState) ProtoMessage() {}

func (*ProjectSourceCodeState) ProtoMessage() {}

func (*ProjectView) ProtoMessage() {}

func (*SimulateResult) ProtoMessage() {}

func (*SourceCodeBlacklistState) ProtoMessage() {}

func (*TokenState) ProtoMessage() {}
