####################################################################################################
# athena-dev
####################################################################################################
FROM athena-base
COPY athena /usr/local/bin/

USER root
RUN ln -s /usr/local/bin/athena /usr/local/bin/athena-server 
USER 999
