extra:
  analytics:
    property: G-5Z1VTPDL73
    provider: google
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
markdown_extensions:
- markdown_include.include
- codehilite:
    css_class: highlight
- admonition
- toc:
    permalink: true
- pymdownx.superfences
nav:
- Overview: index.md
- understand_the_basics.md
- core_concepts.md
- getting_started.md
- faq.md
- security_considerations.md
- Support: SUPPORT.md
- roadmap.md
- Releases ⧉: https://github.com/useryege/athena/releases
plugins:
- search
- gh-admonitions
repo_url: https://github.com/useryege/athena
site_name: Athena - Declarative GitOps CD for Kubernetes
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true
theme:
  custom_dir: docs/overrides
  favicon: assets/favicon.png
  font:
    text: Work Sans
  logo: assets/logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
