api-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/api-server} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_SSH_DATA_PATH=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} ATHENA_BINARY_NAME=athena-server $COMMAND --loglevel debug --redis localhost:${ATHENA_REDIS_PORT:-6379} --disable-auth=${ATHENA_SERVER_DISABLE_AUTH:-'true'} --port ${ATHENA_SERVER_PORT:-8080}"
worm: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-worm} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-worm $COMMAND --loglevel debug --port ${ATHENA_WORM_PORT:-8084} --redis localhost:${ATHENA_REDIS_PORT:-6379}"
polymarket: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-polymarket} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-polymarket $COMMAND --loglevel debug --port ${ATHENA_POLYMARKET_PORT:-8092}"
token: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-token} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-token $COMMAND --loglevel debug --port ${ATHENA_TOKEN_PORT:-8094}"
token-chain-ingestor: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-token-chain-ingestor} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-token ATHENA_TOKEN_MODE=chain-ingestor ATHENA_TOKEN_NODE_WS_USE_PROXY=${ATHENA_TOKEN_NODE_WS_USE_PROXY:-false} $COMMAND --loglevel debug"
token-project-qualifier: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-token-project-qualifier} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-token ATHENA_TOKEN_MODE=project-qualifier ATHENA_TOKEN_NODE_WS_USE_PROXY=${ATHENA_TOKEN_NODE_WS_USE_PROXY:-false} $COMMAND --loglevel debug"
token-project-data-collector: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-token-project-data-collector} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-token ATHENA_TOKEN_MODE=project-data-collector ATHENA_TOKEN_NODE_WS_USE_PROXY=${ATHENA_TOKEN_NODE_WS_USE_PROXY:-false} $COMMAND --loglevel debug"
token-api: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-token-api} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-token-api $COMMAND --loglevel debug --port ${ATHENA_TOKEN_API_PORT:-8096}"
notification: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-notification} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-notification $COMMAND --loglevel debug --port ${ATHENA_NOTIFICATION_PORT:-8086}"
wallet: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-wallet} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-wallet ATHENA_WALLET_ENCRYPTION_KEY=${ATHENA_WALLET_ENCRYPTION_KEY:-athena-local-wallet-encryption-key} $COMMAND --loglevel debug --port ${ATHENA_WALLET_PORT:-8088}"
redis: hack/start-redis-with-password.sh
postgres: hack/start-postgres-with-password.sh
# temporal: hack/start-temporal.sh
ui: sh -c 'cd ui && ${ATHENA_YARN_CMD:-yarn} start'
