# controller: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/app-controller} HOSTNAME=testappcontroller-1  FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_TLS_DATA_PATH=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} ATHENA_SSH_DATA_PATH=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} ATHENA_BINARY_NAME=athena-application-controller $COMMAND --loglevel debug --redis localhost:${ATHENA_E2E_REDIS_PORT:-6379} --repo-server localhost:${ATHENA_E2E_REPOSERVER_PORT:-8081} --commit-server localhost:${ATHENA_E2E_COMMITSERVER_PORT:-8086} --otlp-address=${ATHENA_OTLP_ADDRESS} --application-namespaces=${ATHENA_APPLICATION_NAMESPACES:-''} --server-side-diff-enabled=${ATHENA_APPLICATION_CONTROLLER_SERVER_SIDE_DIFF:-'false'} --hydrator-enabled=${ATHENA_HYDRATOR_ENABLED:='false'}"
api-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/api-server} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_TLS_DATA_PATH=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} ATHENA_SSH_DATA_PATH=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} ATHENA_BINARY_NAME=athena-server $COMMAND --loglevel debug --redis localhost:${ATHENA_E2E_REDIS_PORT:-6379} --disable-auth=${ATHENA_E2E_DISABLE_AUTH:-'true'} --insecure --port ${ATHENA_E2E_APISERVER_PORT:-8080}"
# dex: sh -c "ATHENA_BINARY_NAME=athena-dex go run github.com/useryege/athena/v3/cmd gendexcfg -o `pwd`/dist/dex.yaml && (test -f dist/dex.yaml || { echo 'Failed to generate dex configuration'; exit 1; }) && docker run --rm -p ${ATHENA_E2E_DEX_PORT:-5556}:${ATHENA_E2E_DEX_PORT:-5556} -v `pwd`/dist/dex.yaml:/dex.yaml ghcr.io/dexidp/dex:$(grep "image: ghcr.io/dexidp/dex" manifests/base/dex/athena-dex-server-deployment.yaml | cut -d':' -f3) dex serve /dex.yaml"
redis: hack/start-redis-with-password.sh
# repo-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "export PATH=./dist:\$PATH && [ -n \"\$ATHENA_GIT_CONFIG\" ] && export GIT_CONFIG_GLOBAL=\$ATHENA_GIT_CONFIG && export GIT_CONFIG_NOSYSTEM=1; GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/repo-server} FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_GNUPGHOME=${ATHENA_GNUPGHOME:-/tmp/athena-local/gpg/keys} ATHENA_PLUGINSOCKFILEPATH=${ATHENA_PLUGINSOCKFILEPATH:-./test/cmp}  ATHENA_GPG_DATA_PATH=${ATHENA_GPG_DATA_PATH:-/tmp/athena-local/gpg/source} ATHENA_TLS_DATA_PATH=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} ATHENA_SSH_DATA_PATH=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} ATHENA_BINARY_NAME=athena-repo-server ATHENA_GPG_ENABLED=${ATHENA_GPG_ENABLED:-false} $COMMAND --loglevel debug --port ${ATHENA_E2E_REPOSERVER_PORT:-8081} --redis localhost:${ATHENA_E2E_REDIS_PORT:-6379} --otlp-address=${ATHENA_OTLP_ADDRESS}"
# cmp-server: [ "$ATHENA_E2E_TEST" = 'true' ] && exit 0 || [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "FORCE_LOG_COLORS=1 ATHENA_FAKE_IN_CLUSTER=true ATHENA_BINARY_NAME=athena-cmp-server ATHENA_PLUGINSOCKFILEPATH=${ATHENA_PLUGINSOCKFILEPATH:-./test/cmp} $COMMAND --config-dir-path ./test/cmp --loglevel debug --otlp-address=${ATHENA_OTLP_ADDRESS}"
# commit-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/commit-server} FORCE_LOG_COLORS=1 ATHENA_BINARY_NAME=athena-commit-server $COMMAND --loglevel debug --port ${ATHENA_E2E_COMMITSERVER_PORT:-8086}"
# ui: sh -c 'cd ui && ${ATHENA_E2E_YARN_CMD:-yarn} start'
# git-server: test/fixture/testrepos/start-git.sh
# helm-registry: test/fixture/testrepos/start-helm-registry.sh
# oci-registry: test/fixture/testrepos/start-authenticated-helm-registry.sh
# dev-mounter: [ "$ATHENA_E2E_TEST" != "true" ] && go run hack/dev-mounter/main.go --configmap athena-ssh-known-hosts-cm=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} --configmap athena-tls-certs-cm=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} --configmap athena-gpg-keys-cm=${ATHENA_GPG_DATA_PATH:-/tmp/athena-local/gpg/source}
# applicationset-controller: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/applicationset-controller} FORCE_LOG_COLORS=4 ATHENA_FAKE_IN_CLUSTER=true ATHENA_TLS_DATA_PATH=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} ATHENA_SSH_DATA_PATH=${ATHENA_SSH_DATA_PATH:-/tmp/athena-local/ssh} ATHENA_BINARY_NAME=athena-applicationset-controller $COMMAND --loglevel debug --metrics-addr localhost:12345 --probe-addr localhost:12346 --athena-repo-server localhost:${ATHENA_E2E_REPOSERVER_PORT:-8081}"
# notification: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/notification} FORCE_LOG_COLORS=4 ATHENA_FAKE_IN_CLUSTER=true ATHENA_TLS_DATA_PATH=${ATHENA_TLS_DATA_PATH:-/tmp/athena-local/tls} ATHENA_BINARY_NAME=athena-notifications $COMMAND --loglevel debug --application-namespaces=${ATHENA_APPLICATION_NAMESPACES:-''} --self-service-notification-enabled=${ATHENA_NOTIFICATION_CONTROLLER_SELF_SERVICE_NOTIFICATION_ENABLED:-'false'}"

# opinion: sh -c "cd third-party/opinion && API_KEY=\"${ATHENA_OPINION_API_KEY}\" RPC_URL=\"${ATHENA_OPINION_RPC_URL}\" PRIVATE_KEY=\"${ATHENA_OPINION_PRIVATE_KEY}\" MULTI_SIG_ADDRESS=\"${ATHENA_OPINION_MULTI_SIG_ADDRESS}\" npm run start"


block-sniffer: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-block-sniffer} FORCE_LOG_COLORS=1 ATHENA_BINARY_NAME=athena-block-sniffer $COMMAND --loglevel debug --port ${ATHENA_E2E_BLOCKSNIFFER_PORT:-8088}"
project-controller: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-project-controller} FORCE_LOG_COLORS=1 ATHENA_BINARY_NAME=athena-project-controller $COMMAND --loglevel debug --port ${ATHENA_E2E_PROJECTCONTROLLER_PORT:-8090}"
node-scanner: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/athena || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${ATHENA_COVERAGE_DIR:-/tmp/coverage/athena-node-scanner} FORCE_LOG_COLORS=1 ATHENA_BINARY_NAME=athena-node-scanner $COMMAND --loglevel debug --port ${ATHENA_E2E_NODESCANNER_PORT:-8092}"