// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_ave_data.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectAveData = `-- name: CountProjectAveData :one
SELECT COUNT(*)::bigint
FROM project_ave_data
WHERE ($1::bigint IS NULL OR project_id = $1::bigint)
`

func (q *Queries) CountProjectAveData(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectAveData, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProjectAveData = `-- name: DeleteProjectAveData :execrows
DELETE FROM project_ave_data
WHERE project_id = $1
`

func (q *Queries) DeleteProjectAveData(ctx context.Context, projectID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectAveData, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectAveData = `-- name: GetProjectAveData :one
SELECT project_id, ave_response, fetched_at, created_at
FROM project_ave_data
WHERE project_id = $1
`

func (q *Queries) GetProjectAveData(ctx context.Context, projectID int64) (ProjectAveDatum, error) {
	row := q.db.QueryRow(ctx, getProjectAveData, projectID)
	var i ProjectAveDatum
	err := row.Scan(
		&i.ProjectID,
		&i.AveResponse,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectAveData = `-- name: ListProjectAveData :many
SELECT project_id, ave_response, fetched_at, created_at
FROM project_ave_data
WHERE ($1::bigint IS NULL OR project_id = $1::bigint)
ORDER BY created_at DESC, project_id DESC
LIMIT $3 OFFSET $2
`

type ListProjectAveDataParams struct {
	ProjectID pgtype.Int8
	Offset    int32
	Limit     int32
}

func (q *Queries) ListProjectAveData(ctx context.Context, arg ListProjectAveDataParams) ([]ProjectAveDatum, error) {
	rows, err := q.db.Query(ctx, listProjectAveData, arg.ProjectID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectAveDatum
	for rows.Next() {
		var i ProjectAveDatum
		if err := rows.Scan(
			&i.ProjectID,
			&i.AveResponse,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectAveData = `-- name: UpsertProjectAveData :one
INSERT INTO project_ave_data (
  project_id,
  ave_response,
  fetched_at
) VALUES (
  $1,
  $2::jsonb,
  $3
)
ON CONFLICT (project_id) DO UPDATE
SET ave_response = EXCLUDED.ave_response,
  fetched_at = EXCLUDED.fetched_at
RETURNING project_id, ave_response, fetched_at, created_at
`

type UpsertProjectAveDataParams struct {
	ProjectID   int64
	AveResponse []byte
	FetchedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertProjectAveData(ctx context.Context, arg UpsertProjectAveDataParams) (ProjectAveDatum, error) {
	row := q.db.QueryRow(ctx, upsertProjectAveData, arg.ProjectID, arg.AveResponse, arg.FetchedAt)
	var i ProjectAveDatum
	err := row.Scan(
		&i.ProjectID,
		&i.AveResponse,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}
