// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_blocklist.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletBlocklistEntry = `-- name: CreateWalletBlocklistEntry :exec
INSERT INTO wallet_blocklist (
  wallet,
  note
) VALUES (
  $1,
  $2
)
`

type CreateWalletBlocklistEntryParams struct {
	Wallet []byte
	Note   pgtype.Text
}

func (q *Queries) CreateWalletBlocklistEntry(ctx context.Context, arg CreateWalletBlocklistEntryParams) error {
	_, err := q.db.Exec(ctx, createWalletBlocklistEntry, arg.Wallet, arg.Note)
	return err
}

const deleteWalletBlocklistEntry = `-- name: DeleteWalletBlocklistEntry :execrows
DELETE FROM wallet_blocklist
WHERE wallet = $1
`

func (q *Queries) DeleteWalletBlocklistEntry(ctx context.Context, wallet []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWalletBlocklistEntry, wallet)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWalletBlocklistEntry = `-- name: GetWalletBlocklistEntry :one
SELECT wallet, note, created_at
FROM wallet_blocklist
WHERE wallet = $1
`

func (q *Queries) GetWalletBlocklistEntry(ctx context.Context, wallet []byte) (WalletBlocklist, error) {
	row := q.db.QueryRow(ctx, getWalletBlocklistEntry, wallet)
	var i WalletBlocklist
	err := row.Scan(&i.Wallet, &i.Note, &i.CreatedAt)
	return i, err
}

const isWalletBlocked = `-- name: IsWalletBlocked :one
SELECT EXISTS(
  SELECT 1
  FROM wallet_blocklist
  WHERE wallet = $1
)::boolean
`

func (q *Queries) IsWalletBlocked(ctx context.Context, wallet []byte) (bool, error) {
	row := q.db.QueryRow(ctx, isWalletBlocked, wallet)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listWalletBlocklistEntries = `-- name: ListWalletBlocklistEntries :many
SELECT wallet, note, created_at
FROM wallet_blocklist
ORDER BY created_at DESC, wallet
`

func (q *Queries) ListWalletBlocklistEntries(ctx context.Context) ([]WalletBlocklist, error) {
	rows, err := q.db.Query(ctx, listWalletBlocklistEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletBlocklist
	for rows.Next() {
		var i WalletBlocklist
		if err := rows.Scan(&i.Wallet, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBlocklistEntryNote = `-- name: UpdateWalletBlocklistEntryNote :execrows
UPDATE wallet_blocklist
SET note = $1
WHERE wallet = $2
`

type UpdateWalletBlocklistEntryNoteParams struct {
	Note   pgtype.Text
	Wallet []byte
}

func (q *Queries) UpdateWalletBlocklistEntryNote(ctx context.Context, arg UpdateWalletBlocklistEntryNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWalletBlocklistEntryNote, arg.Note, arg.Wallet)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
