syntax = "proto3";

// Notification Service
//
// Notification Service API returns notification-level workload status.
package notification;

import "google/api/annotations.proto";

option go_package = "github.com/useryege/athena/pkg/apiclient/notification";

// GetNotificationStatusRequest queries the notification service runtime status.
message GetNotificationStatusRequest {}

// GetNotificationStatusResponse returns the notification service runtime status.
message GetNotificationStatusResponse {
  bool started = 1;
  string status = 2;
}

service NotificationService {
  // GetNotificationStatus returns the notification service runtime status.
  rpc GetNotificationStatus(GetNotificationStatusRequest) returns (GetNotificationStatusResponse) {
    option (google.api.http) = {get: "/api/v1/notification/status"};
  }
}
