syntax = "proto3";
package athena.internal.tokenapi;
import "internal/tokenapi/types.proto";
option go_package = "github.com/useryege/athena/internal/tokenapi/apiclient";
service TokenCatalogService {
  rpc GetContractCode(GetContractCodeRequest) returns (GetContractCodeResponse);
  rpc ListContractCodes(ListContractCodesRequest) returns (ListContractCodesResponse);
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
  rpc GetProjectDetail(GetProjectDetailRequest) returns (GetProjectDetailResponse);
  rpc GetProjectSwapActivity(GetProjectSwapActivityRequest) returns (GetProjectSwapActivityResponse);
  rpc ListProjectSwapEvents(ListProjectSwapEventsRequest) returns (ListProjectSwapEventsResponse);
  rpc ListProjectTrends(ListProjectTrendsRequest) returns (ListProjectTrendsResponse);
  rpc ListProjectObservations(ListProjectObservationsRequest) returns (ListProjectObservationsResponse);
  rpc ListProjectWalletNormalTransactions(ListProjectWalletNormalTransactionsRequest) returns (ListProjectWalletNormalTransactionsResponse);
}
