syntax = "proto3";

// Shared application settings projected by the bootstrap API.
package cluster;

import "gogoproto/gogo.proto";

option go_package = "github.com/useryege/athena/pkg/apiclient/settings";

message Settings {
  string url = 1 [(gogoproto.customname) = "URL"];
  string appLabelKey = 4;
  // map<string, github.com.useryege.athena.pkg.apis.application.v1alpha1.ResourceOverride> resourceOverrides = 5;
  bool statusBadgeEnabled = 6;
  GoogleAnalyticsConfig googleAnalytics = 7;
  // github.com.useryege.athena.pkg.apis.application.v1alpha1.KustomizeOptions kustomizeOptions = 8;
  // Help settings
  Help help = 9;
  repeated Plugin plugins = 10;
  bool userLoginsDisabled = 11;
  // Deprecated: use sidecar plugins instead.
  // repeated github.com.useryege.athena.pkg.apis.application.v1alpha1.ConfigManagementPlugin configManagementPlugins = 12;
  repeated string kustomizeVersions = 13;
  string uiCssURL = 14;
  string uiBannerContent = 15;
  string uiBannerURL = 16;
  reserved 17;
  reserved "passwordPattern";
  string trackingMethod = 18;
  bool uiBannerPermanent = 19;
  string uiBannerPosition = 20;
  string statusBadgeRootUrl = 21;
  bool execEnabled = 22;
  string controllerNamespace = 23;
  bool appsInAnyNamespaceEnabled = 24;
  bool impersonationEnabled = 25;
  string installationID = 26;
  repeated string additionalUrls = 27 [(gogoproto.customname) = "AdditionalURLs"];
  bool hydratorEnabled = 28;
  bool syncWithReplaceAllowed = 29;
}

message GoogleAnalyticsConfig {
  string trackingID = 1;
  bool anonymizeUsers = 2;
}

// Help settings
message Help {
  // the URL for getting chat help, this will typically be your Slack channel for support
  string chatUrl = 1;
  // the text for getting chat help, defaults to "Chat now!"
  string chatText = 2;
  // the URLs for downloading athena binaries
  map<string, string> binaryUrls = 3;
}

// Plugin settings
message Plugin {
  // the name of the plugin, e.g. "kasane"
  string name = 1;
}
