// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/server/solana/solana.proto

package solana

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListProjectsRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c97c60dbf410743, []int{0}
}
func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func (m *ListProjectsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListProjectsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListProjectsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Project struct {
	Mint                 string   `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	TokenProgram         string   `protobuf:"bytes,2,opt,name=tokenProgram,proto3" json:"tokenProgram,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	FeePayer             string   `protobuf:"bytes,4,opt,name=feePayer,proto3" json:"feePayer,omitempty"`
	MintAuthority        string   `protobuf:"bytes,5,opt,name=mintAuthority,proto3" json:"mintAuthority,omitempty"`
	FreezeAuthority      string   `protobuf:"bytes,6,opt,name=freezeAuthority,proto3" json:"freezeAuthority,omitempty"`
	Decimals             uint32   `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Slot                 uint64   `protobuf:"varint,8,opt,name=slot,proto3" json:"slot,omitempty"`
	BlockTime            int64    `protobuf:"varint,9,opt,name=blockTime,proto3" json:"blockTime,omitempty"`
	DiscoveredAt         int64    `protobuf:"varint,10,opt,name=discoveredAt,proto3" json:"discoveredAt,omitempty"`
	Name                 string   `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Symbol               string   `protobuf:"bytes,12,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MetadataStatus       string   `protobuf:"bytes,13,opt,name=metadataStatus,proto3" json:"metadataStatus,omitempty"`
	MetadataSource       string   `protobuf:"bytes,14,opt,name=metadataSource,proto3" json:"metadataSource,omitempty"`
	MetadataAccount      string   `protobuf:"bytes,15,opt,name=metadataAccount,proto3" json:"metadataAccount,omitempty"`
	MetadataObservedSlot uint64   `protobuf:"varint,16,opt,name=metadataObservedSlot,proto3" json:"metadataObservedSlot,omitempty"`
	MetadataUpdatedAt    int64    `protobuf:"varint,17,opt,name=metadataUpdatedAt,proto3" json:"metadataUpdatedAt,omitempty"`
	IssuanceSource       string   `protobuf:"bytes,18,opt,name=issuanceSource,proto3" json:"issuanceSource,omitempty"`
	IssuanceProgram      string   `protobuf:"bytes,19,opt,name=issuanceProgram,proto3" json:"issuanceProgram,omitempty"`
	SourceStatus         string   `protobuf:"bytes,20,opt,name=sourceStatus,proto3" json:"sourceStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c97c60dbf410743, []int{1}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Project.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return m.Size()
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetMint() string {
	if m != nil {
		return m.Mint
	}
	return ""
}

func (m *Project) GetTokenProgram() string {
	if m != nil {
		return m.TokenProgram
	}
	return ""
}

func (m *Project) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Project) GetFeePayer() string {
	if m != nil {
		return m.FeePayer
	}
	return ""
}

func (m *Project) GetMintAuthority() string {
	if m != nil {
		return m.MintAuthority
	}
	return ""
}

func (m *Project) GetFreezeAuthority() string {
	if m != nil {
		return m.FreezeAuthority
	}
	return ""
}

func (m *Project) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *Project) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Project) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *Project) GetDiscoveredAt() int64 {
	if m != nil {
		return m.DiscoveredAt
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Project) GetMetadataStatus() string {
	if m != nil {
		return m.MetadataStatus
	}
	return ""
}

func (m *Project) GetMetadataSource() string {
	if m != nil {
		return m.MetadataSource
	}
	return ""
}

func (m *Project) GetMetadataAccount() string {
	if m != nil {
		return m.MetadataAccount
	}
	return ""
}

func (m *Project) GetMetadataObservedSlot() uint64 {
	if m != nil {
		return m.MetadataObservedSlot
	}
	return 0
}

func (m *Project) GetMetadataUpdatedAt() int64 {
	if m != nil {
		return m.MetadataUpdatedAt
	}
	return 0
}

func (m *Project) GetIssuanceSource() string {
	if m != nil {
		return m.IssuanceSource
	}
	return ""
}

func (m *Project) GetIssuanceProgram() string {
	if m != nil {
		return m.IssuanceProgram
	}
	return ""
}

func (m *Project) GetSourceStatus() string {
	if m != nil {
		return m.SourceStatus
	}
	return ""
}

type ListProjectsResponse struct {
	Items                []*Project `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalSize            int64      `protobuf:"varint,2,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c97c60dbf410743, []int{2}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetItems() []*Project {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListProjectsResponse) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

type GetDiscoveryStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiscoveryStatusRequest) Reset()         { *m = GetDiscoveryStatusRequest{} }
func (m *GetDiscoveryStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetDiscoveryStatusRequest) ProtoMessage()    {}
func (*GetDiscoveryStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c97c60dbf410743, []int{3}
}
func (m *GetDiscoveryStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetDiscoveryStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetDiscoveryStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetDiscoveryStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscoveryStatusRequest.Merge(m, src)
}
func (m *GetDiscoveryStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetDiscoveryStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscoveryStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscoveryStatusRequest proto.InternalMessageInfo

type GetDiscoveryStatusResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StartSlot            uint64   `protobuf:"varint,2,opt,name=startSlot,proto3" json:"startSlot,omitempty"`
	LastProcessedSlot    uint64   `protobuf:"varint,3,opt,name=lastProcessedSlot,proto3" json:"lastProcessedSlot,omitempty"`
	LatestFinalizedSlot  uint64   `protobuf:"varint,4,opt,name=latestFinalizedSlot,proto3" json:"latestFinalizedSlot,omitempty"`
	LastSuccessAt        int64    `protobuf:"varint,5,opt,name=lastSuccessAt,proto3" json:"lastSuccessAt,omitempty"`
	TotalProjects        int64    `protobuf:"varint,6,opt,name=totalProjects,proto3" json:"totalProjects,omitempty"`
	LastError            string   `protobuf:"bytes,7,opt,name=lastError,proto3" json:"lastError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiscoveryStatusResponse) Reset()         { *m = GetDiscoveryStatusResponse{} }
func (m *GetDiscoveryStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDiscoveryStatusResponse) ProtoMessage()    {}
func (*GetDiscoveryStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c97c60dbf410743, []int{4}
}
func (m *GetDiscoveryStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetDiscoveryStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetDiscoveryStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetDiscoveryStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscoveryStatusResponse.Merge(m, src)
}
func (m *GetDiscoveryStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetDiscoveryStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscoveryStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscoveryStatusResponse proto.InternalMessageInfo

func (m *GetDiscoveryStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetDiscoveryStatusResponse) GetStartSlot() uint64 {
	if m != nil {
		return m.StartSlot
	}
	return 0
}

func (m *GetDiscoveryStatusResponse) GetLastProcessedSlot() uint64 {
	if m != nil {
		return m.LastProcessedSlot
	}
	return 0
}

func (m *GetDiscoveryStatusResponse) GetLatestFinalizedSlot() uint64 {
	if m != nil {
		return m.LatestFinalizedSlot
	}
	return 0
}

func (m *GetDiscoveryStatusResponse) GetLastSuccessAt() int64 {
	if m != nil {
		return m.LastSuccessAt
	}
	return 0
}

func (m *GetDiscoveryStatusResponse) GetTotalProjects() int64 {
	if m != nil {
		return m.TotalProjects
	}
	return 0
}

func (m *GetDiscoveryStatusResponse) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

func init() {
	proto.RegisterType((*ListProjectsRequest)(nil), "solana.ListProjectsRequest")
	proto.RegisterType((*Project)(nil), "solana.Project")
	proto.RegisterType((*ListProjectsResponse)(nil), "solana.ListProjectsResponse")
	proto.RegisterType((*GetDiscoveryStatusRequest)(nil), "solana.GetDiscoveryStatusRequest")
	proto.RegisterType((*GetDiscoveryStatusResponse)(nil), "solana.GetDiscoveryStatusResponse")
}

func init() {
	proto.RegisterFile("internal/server/solana/solana.proto", fileDescriptor_4c97c60dbf410743)
}

var fileDescriptor_4c97c60dbf410743 = []byte{
	// 749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0x86, 0xfc, 0x97, 0x98, 0x89, 0x93, 0x86, 0x71, 0x1b, 0xc5, 0x49, 0x53, 0x57, 0xfd, 0x81,
	0x0f, 0x45, 0xdc, 0xa6, 0xe7, 0x1e, 0x5c, 0xf4, 0xe7, 0x52, 0xa0, 0x81, 0xdc, 0x5e, 0x9a, 0x13,
	0x2d, 0x4f, 0x14, 0x26, 0x92, 0xe8, 0x90, 0x23, 0x03, 0xf6, 0xb1, 0xaf, 0xd0, 0x6b, 0xdf, 0x64,
	0x5f, 0x60, 0x8f, 0x0b, 0xec, 0x0b, 0x2c, 0x82, 0x7d, 0x87, 0xbd, 0x2e, 0x38, 0xa2, 0xe2, 0xc8,
	0xf1, 0xee, 0x49, 0x9c, 0x6f, 0x3e, 0x7d, 0x1c, 0x7e, 0xc3, 0x21, 0xfb, 0x4a, 0x66, 0x08, 0x3a,
	0x13, 0xc9, 0xd0, 0x80, 0x9e, 0x83, 0x1e, 0x1a, 0x95, 0x88, 0x4c, 0xb8, 0xcf, 0xf9, 0x4c, 0x2b,
	0x54, 0xbc, 0x55, 0x44, 0xbd, 0xd3, 0x58, 0xa9, 0x38, 0x81, 0xa1, 0x98, 0xc9, 0xa1, 0xc8, 0x32,
	0x85, 0x02, 0xa5, 0xca, 0x4c, 0xc1, 0x0a, 0xae, 0xd8, 0xe1, 0x1f, 0xd2, 0xe0, 0xa5, 0x56, 0xb7,
	0x10, 0xa1, 0x09, 0xe1, 0x3e, 0x07, 0x83, 0x9c, 0xb3, 0xc6, 0x4c, 0xc4, 0xe0, 0x7b, 0x7d, 0x6f,
	0xd0, 0x09, 0x69, 0xcd, 0x7b, 0x6c, 0xdb, 0x7e, 0xc7, 0x72, 0x09, 0x7e, 0x8d, 0xf0, 0xc7, 0x98,
	0x77, 0x59, 0xf3, 0x3e, 0x07, 0xbd, 0xf0, 0xeb, 0x7d, 0x6f, 0xd0, 0x0e, 0x8b, 0x20, 0x78, 0xd1,
	0x64, 0x5b, 0x4e, 0xd9, 0x2a, 0xa6, 0x32, 0x43, 0x52, 0x6c, 0x87, 0xb4, 0xe6, 0x01, 0xdb, 0x45,
	0x75, 0x07, 0xd9, 0xa5, 0x56, 0xb1, 0x16, 0x29, 0xa9, 0xb6, 0xc3, 0x0a, 0xc6, 0x4f, 0x59, 0xdb,
	0xc8, 0x38, 0x13, 0x98, 0x6b, 0x70, 0xea, 0x2b, 0xc0, 0xd6, 0x74, 0x0d, 0x70, 0x29, 0x16, 0xa0,
	0xfd, 0x06, 0x25, 0x1f, 0x63, 0xfe, 0x35, 0xeb, 0xd8, 0x5d, 0x46, 0x39, 0xde, 0x28, 0x2d, 0x71,
	0xe1, 0x37, 0x89, 0x50, 0x05, 0xf9, 0x80, 0xed, 0x5f, 0x6b, 0x80, 0x25, 0xac, 0x78, 0x2d, 0xe2,
	0xad, 0xc3, 0x76, 0xaf, 0x29, 0x44, 0x32, 0x15, 0x89, 0xf1, 0xb7, 0x8a, 0xf3, 0x97, 0xb1, 0x3d,
	0x9d, 0x49, 0x14, 0xfa, 0xdb, 0x7d, 0x6f, 0xd0, 0x08, 0x69, 0x6d, 0x2b, 0x9f, 0x24, 0x2a, 0xba,
	0xfb, 0x4b, 0xa6, 0xe0, 0xb7, 0xfb, 0xde, 0xa0, 0x1e, 0xae, 0x00, 0x7b, 0xf6, 0xa9, 0x34, 0x91,
	0x9a, 0x83, 0x86, 0xe9, 0x08, 0x7d, 0x46, 0x84, 0x0a, 0x66, 0x55, 0x33, 0x91, 0x82, 0xbf, 0x53,
	0x78, 0x66, 0xd7, 0xfc, 0x33, 0xd6, 0x32, 0x8b, 0x74, 0xa2, 0x12, 0x7f, 0x97, 0x50, 0x17, 0xf1,
	0x6f, 0xd9, 0x5e, 0x0a, 0x28, 0xa6, 0x02, 0xc5, 0x18, 0x05, 0xe6, 0xc6, 0xef, 0x50, 0x7e, 0x0d,
	0xad, 0xf0, 0x54, 0xae, 0x23, 0xf0, 0xf7, 0xd6, 0x78, 0x84, 0x5a, 0x5f, 0x4a, 0x64, 0x14, 0x45,
	0x2a, 0xcf, 0xd0, 0xdf, 0x2f, 0x7c, 0x59, 0x83, 0xf9, 0x05, 0xeb, 0x96, 0xd0, 0x9f, 0x13, 0xba,
	0x90, 0xd3, 0xb1, 0xf5, 0xe2, 0x13, 0xf2, 0x62, 0x63, 0x8e, 0x7f, 0xc7, 0x0e, 0x4a, 0xfc, 0xef,
	0xd9, 0x54, 0x20, 0x59, 0x70, 0x40, 0x16, 0x3c, 0x4f, 0xd8, 0x9a, 0xa5, 0x31, 0xb9, 0xc8, 0x22,
	0x70, 0x35, 0xf3, 0xa2, 0xe6, 0x2a, 0x6a, 0x6b, 0x2e, 0x91, 0xf2, 0x4a, 0x1d, 0x16, 0x35, 0xaf,
	0xc1, 0xd6, 0x7d, 0x43, 0xff, 0x38, 0xaf, 0xba, 0xc5, 0xcd, 0x7b, 0x8a, 0x05, 0x57, 0xac, 0x5b,
	0x1d, 0x0d, 0x33, 0x53, 0x99, 0x01, 0xfe, 0x0d, 0x6b, 0x4a, 0x84, 0xd4, 0xf8, 0x5e, 0xbf, 0x3e,
	0xd8, 0xb9, 0xd8, 0x3f, 0x77, 0x63, 0xe7, 0x88, 0x61, 0x91, 0xb5, 0xed, 0x47, 0x85, 0x22, 0x79,
	0x9c, 0x97, 0x7a, 0xb8, 0x02, 0x82, 0x13, 0x76, 0xfc, 0x3b, 0xe0, 0x2f, 0xae, 0xdb, 0x8b, 0x62,
	0x4b, 0x37, 0x7d, 0xc1, 0xff, 0x35, 0xd6, 0xdb, 0x94, 0x75, 0x05, 0xd8, 0x2b, 0x50, 0x94, 0xed,
	0xb9, 0x2b, 0x40, 0x11, 0x8d, 0x0a, 0x0a, 0x8d, 0xe4, 0x7e, 0x8d, 0xdc, 0x5f, 0x01, 0xd6, 0xf2,
	0x44, 0xd0, 0x71, 0x22, 0x30, 0xc6, 0xf5, 0xa8, 0x4e, 0xac, 0xe7, 0x09, 0xfe, 0x3d, 0x3b, 0x4c,
	0x04, 0x82, 0xc1, 0xdf, 0x64, 0x26, 0x12, 0xb9, 0x74, 0xfc, 0x06, 0xf1, 0x37, 0xa5, 0xec, 0xb8,
	0x59, 0x99, 0x71, 0x1e, 0x59, 0x99, 0x11, 0xd2, 0xb8, 0xd5, 0xc3, 0x2a, 0x68, 0x59, 0x64, 0x42,
	0xe9, 0x2a, 0x0d, 0x5b, 0x3d, 0xac, 0x82, 0xf6, 0x24, 0xf6, 0xb7, 0x5f, 0xb5, 0x56, 0x9a, 0x66,
	0xad, 0x1d, 0xae, 0x80, 0x8b, 0x77, 0x1e, 0xeb, 0x8c, 0xc9, 0xf3, 0x31, 0xe8, 0xb9, 0x8c, 0x80,
	0xdf, 0xb2, 0xdd, 0xa7, 0xad, 0xe2, 0x27, 0x65, 0x4f, 0x36, 0xbc, 0x6d, 0xbd, 0xd3, 0xcd, 0xc9,
	0xc2, 0xdc, 0xe0, 0x8b, 0x7f, 0x5f, 0xbf, 0xfd, 0xaf, 0x76, 0xcc, 0x8f, 0xe8, 0xc1, 0x9c, 0xff,
	0x50, 0xbe, 0xad, 0xb3, 0x52, 0x7b, 0xc9, 0xf8, 0xf3, 0xde, 0xf0, 0x2f, 0x4b, 0xd1, 0x0f, 0x76,
	0xb5, 0x17, 0x7c, 0x8c, 0xe2, 0x76, 0xff, 0x9c, 0x76, 0x3f, 0xe2, 0x9f, 0xae, 0xed, 0x5e, 0x74,
	0xf8, 0xe7, 0x9f, 0x5e, 0x3e, 0x9c, 0x79, 0xaf, 0x1e, 0xce, 0xbc, 0x37, 0x0f, 0x67, 0xde, 0x3f,
	0xc3, 0x58, 0xe2, 0x4d, 0x3e, 0x39, 0x8f, 0x54, 0x3a, 0xcc, 0x0d, 0xe8, 0x05, 0xc4, 0x30, 0x14,
	0x78, 0x03, 0xb6, 0xdc, 0xbb, 0xd8, 0x4a, 0x44, 0x89, 0x84, 0x0c, 0x9d, 0xca, 0xa4, 0x45, 0x6f,
	0xfe, 0x8f, 0xef, 0x07, 0x00, 0x4f, 0x79, 0xe9, 0x0a, 0x40, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SolanaServiceClient is the client API for SolanaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SolanaServiceClient interface {
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*GetDiscoveryStatusResponse, error)
}

type solanaServiceClient struct {
	cc *grpc.ClientConn
}

func NewSolanaServiceClient(cc *grpc.ClientConn) SolanaServiceClient {
	return &solanaServiceClient{cc}
}

func (c *solanaServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/solana.SolanaService/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*GetDiscoveryStatusResponse, error) {
	out := new(GetDiscoveryStatusResponse)
	err := c.cc.Invoke(ctx, "/solana.SolanaService/GetDiscoveryStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolanaServiceServer is the server API for SolanaService service.
type SolanaServiceServer interface {
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	GetDiscoveryStatus(context.Context, *GetDiscoveryStatusRequest) (*GetDiscoveryStatusResponse, error)
}

// UnimplementedSolanaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSolanaServiceServer struct {
}

func (*UnimplementedSolanaServiceServer) ListProjects(ctx context.Context, req *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (*UnimplementedSolanaServiceServer) GetDiscoveryStatus(ctx context.Context, req *GetDiscoveryStatusRequest) (*GetDiscoveryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscoveryStatus not implemented")
}

func RegisterSolanaServiceServer(s *grpc.Server, srv SolanaServiceServer) {
	s.RegisterService(&_SolanaService_serviceDesc, srv)
}

func _SolanaService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solana.SolanaService/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_GetDiscoveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscoveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).GetDiscoveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solana.SolanaService/GetDiscoveryStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).GetDiscoveryStatus(ctx, req.(*GetDiscoveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SolanaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "solana.SolanaService",
	HandlerType: (*SolanaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProjects",
			Handler:    _SolanaService_ListProjects_Handler,
		},
		{
			MethodName: "GetDiscoveryStatus",
			Handler:    _SolanaService_GetDiscoveryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/server/solana/solana.proto",
}

func (m *ListProjectsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListProjectsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListProjectsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Query) > 0 {
		i -= len(m.Query)
		copy(dAtA[i:], m.Query)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Query)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PageSize != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Project) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Project) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Project) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.SourceStatus) > 0 {
		i -= len(m.SourceStatus)
		copy(dAtA[i:], m.SourceStatus)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.SourceStatus)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if len(m.IssuanceProgram) > 0 {
		i -= len(m.IssuanceProgram)
		copy(dAtA[i:], m.IssuanceProgram)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.IssuanceProgram)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.IssuanceSource) > 0 {
		i -= len(m.IssuanceSource)
		copy(dAtA[i:], m.IssuanceSource)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.IssuanceSource)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.MetadataUpdatedAt != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.MetadataUpdatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.MetadataObservedSlot != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.MetadataObservedSlot))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.MetadataAccount) > 0 {
		i -= len(m.MetadataAccount)
		copy(dAtA[i:], m.MetadataAccount)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.MetadataAccount)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.MetadataSource) > 0 {
		i -= len(m.MetadataSource)
		copy(dAtA[i:], m.MetadataSource)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.MetadataSource)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.MetadataStatus) > 0 {
		i -= len(m.MetadataStatus)
		copy(dAtA[i:], m.MetadataStatus)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.MetadataStatus)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x5a
	}
	if m.DiscoveredAt != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.DiscoveredAt))
		i--
		dAtA[i] = 0x50
	}
	if m.BlockTime != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.BlockTime))
		i--
		dAtA[i] = 0x48
	}
	if m.Slot != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x40
	}
	if m.Decimals != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x38
	}
	if len(m.FreezeAuthority) > 0 {
		i -= len(m.FreezeAuthority)
		copy(dAtA[i:], m.FreezeAuthority)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.FreezeAuthority)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MintAuthority) > 0 {
		i -= len(m.MintAuthority)
		copy(dAtA[i:], m.MintAuthority)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.MintAuthority)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FeePayer) > 0 {
		i -= len(m.FeePayer)
		copy(dAtA[i:], m.FeePayer)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.FeePayer)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenProgram) > 0 {
		i -= len(m.TokenProgram)
		copy(dAtA[i:], m.TokenProgram)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.TokenProgram)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mint) > 0 {
		i -= len(m.Mint)
		copy(dAtA[i:], m.Mint)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Mint)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListProjectsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListProjectsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListProjectsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TotalSize != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.TotalSize))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSolana(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetDiscoveryStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetDiscoveryStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetDiscoveryStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *GetDiscoveryStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetDiscoveryStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetDiscoveryStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.LastError) > 0 {
		i -= len(m.LastError)
		copy(dAtA[i:], m.LastError)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.LastError)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TotalProjects != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.TotalProjects))
		i--
		dAtA[i] = 0x30
	}
	if m.LastSuccessAt != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.LastSuccessAt))
		i--
		dAtA[i] = 0x28
	}
	if m.LatestFinalizedSlot != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.LatestFinalizedSlot))
		i--
		dAtA[i] = 0x20
	}
	if m.LastProcessedSlot != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.LastProcessedSlot))
		i--
		dAtA[i] = 0x18
	}
	if m.StartSlot != 0 {
		i = encodeVarintSolana(dAtA, i, uint64(m.StartSlot))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintSolana(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSolana(dAtA []byte, offset int, v uint64) int {
	offset -= sovSolana(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListProjectsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovSolana(uint64(m.Page))
	}
	if m.PageSize != 0 {
		n += 1 + sovSolana(uint64(m.PageSize))
	}
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Project) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mint)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.TokenProgram)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.FeePayer)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.MintAuthority)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.FreezeAuthority)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovSolana(uint64(m.Decimals))
	}
	if m.Slot != 0 {
		n += 1 + sovSolana(uint64(m.Slot))
	}
	if m.BlockTime != 0 {
		n += 1 + sovSolana(uint64(m.BlockTime))
	}
	if m.DiscoveredAt != 0 {
		n += 1 + sovSolana(uint64(m.DiscoveredAt))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.MetadataStatus)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.MetadataSource)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	l = len(m.MetadataAccount)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	if m.MetadataObservedSlot != 0 {
		n += 2 + sovSolana(uint64(m.MetadataObservedSlot))
	}
	if m.MetadataUpdatedAt != 0 {
		n += 2 + sovSolana(uint64(m.MetadataUpdatedAt))
	}
	l = len(m.IssuanceSource)
	if l > 0 {
		n += 2 + l + sovSolana(uint64(l))
	}
	l = len(m.IssuanceProgram)
	if l > 0 {
		n += 2 + l + sovSolana(uint64(l))
	}
	l = len(m.SourceStatus)
	if l > 0 {
		n += 2 + l + sovSolana(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListProjectsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovSolana(uint64(l))
		}
	}
	if m.TotalSize != 0 {
		n += 1 + sovSolana(uint64(m.TotalSize))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetDiscoveryStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetDiscoveryStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	if m.StartSlot != 0 {
		n += 1 + sovSolana(uint64(m.StartSlot))
	}
	if m.LastProcessedSlot != 0 {
		n += 1 + sovSolana(uint64(m.LastProcessedSlot))
	}
	if m.LatestFinalizedSlot != 0 {
		n += 1 + sovSolana(uint64(m.LatestFinalizedSlot))
	}
	if m.LastSuccessAt != 0 {
		n += 1 + sovSolana(uint64(m.LastSuccessAt))
	}
	if m.TotalProjects != 0 {
		n += 1 + sovSolana(uint64(m.TotalProjects))
	}
	l = len(m.LastError)
	if l > 0 {
		n += 1 + l + sovSolana(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSolana(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSolana(x uint64) (n int) {
	return sovSolana(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListProjectsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListProjectsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListProjectsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSolana(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSolana
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Project) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Project: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Project: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenProgram", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenProgram = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FreezeAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			m.BlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscoveredAt", wireType)
			}
			m.DiscoveredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiscoveredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataSource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataSource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataObservedSlot", wireType)
			}
			m.MetadataObservedSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetadataObservedSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUpdatedAt", wireType)
			}
			m.MetadataUpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetadataUpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuanceSource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuanceSource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuanceProgram", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuanceProgram = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSolana(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSolana
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListProjectsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListProjectsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListProjectsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &Project{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSize", wireType)
			}
			m.TotalSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSolana(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSolana
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetDiscoveryStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetDiscoveryStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetDiscoveryStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSolana(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSolana
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetDiscoveryStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetDiscoveryStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetDiscoveryStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartSlot", wireType)
			}
			m.StartSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastProcessedSlot", wireType)
			}
			m.LastProcessedSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastProcessedSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFinalizedSlot", wireType)
			}
			m.LatestFinalizedSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestFinalizedSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSuccessAt", wireType)
			}
			m.LastSuccessAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSuccessAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalProjects", wireType)
			}
			m.TotalProjects = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalProjects |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastError", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSolana
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSolana
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastError = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSolana(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSolana
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSolana(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSolana
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSolana
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSolana
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSolana
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSolana
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSolana        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSolana          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSolana = fmt.Errorf("proto: unexpected end of group")
)
