-- name: UpsertProjectAveTokenDetail :exec
INSERT INTO project_ave_token_detail (
  project_contract,
  status,
  msg,
  data_type,
  is_audited,
  fetched_at,
  total,
  launch_price,
  current_price_eth,
  current_price_usd,
  price_change_1d,
  price_change_24h,
  price_change_1h,
  lock_amount,
  burn_amount,
  other_amount,
  tx_amount_24h,
  tx_volume_u_24h,
  locked_percent,
  market_cap,
  fdv,
  tvl,
  main_pair_tvl,
  token_price_change_5m,
  token_price_change_1h,
  token_price_change_4h,
  token_price_change_24h,
  token_tx_volume_usd_5m,
  token_tx_volume_usd_1h,
  token_tx_volume_usd_4h,
  token_tx_volume_usd_24h,
  token_buy_volume_u_5m,
  token_sell_volume_u_5m,
  token,
  chain,
  decimal,
  name,
  symbol,
  holders,
  appendix,
  risk_level,
  logo_url,
  risk_info,
  risk_score,
  launch_at,
  created_at,
  tx_count_24h,
  lock_platform,
  is_mintable,
  updated_at,
  main_pair,
  has_mint_method,
  is_lp_not_locked,
  has_not_renounced,
  has_not_audited,
  has_not_open_source,
  is_in_blacklist,
  is_honeypot,
  ave_risk_level
) VALUES (
  $1,
  $2,
  sqlc.narg('msg')::text,
  $3,
  $4,
  $5,
  sqlc.narg('total')::text,
  sqlc.narg('launch_price')::text,
  sqlc.narg('current_price_eth')::text,
  sqlc.narg('current_price_usd')::text,
  sqlc.narg('price_change_1d')::text,
  sqlc.narg('price_change_24h')::text,
  sqlc.narg('price_change_1h')::text,
  sqlc.narg('lock_amount')::text,
  sqlc.narg('burn_amount')::text,
  sqlc.narg('other_amount')::text,
  sqlc.narg('tx_amount_24h')::text,
  sqlc.narg('tx_volume_u_24h')::text,
  sqlc.narg('locked_percent')::text,
  sqlc.narg('market_cap')::text,
  sqlc.narg('fdv')::text,
  sqlc.narg('tvl')::text,
  sqlc.narg('main_pair_tvl')::text,
  sqlc.narg('token_price_change_5m')::text,
  sqlc.narg('token_price_change_1h')::text,
  sqlc.narg('token_price_change_4h')::text,
  sqlc.narg('token_price_change_24h')::text,
  sqlc.narg('token_tx_volume_usd_5m')::text,
  sqlc.narg('token_tx_volume_usd_1h')::text,
  sqlc.narg('token_tx_volume_usd_4h')::text,
  sqlc.narg('token_tx_volume_usd_24h')::text,
  sqlc.narg('token_buy_volume_u_5m')::text,
  sqlc.narg('token_sell_volume_u_5m')::text,
  sqlc.narg('token')::text,
  sqlc.narg('chain')::text,
  $6,
  sqlc.narg('name')::text,
  sqlc.narg('symbol')::text,
  $7,
  sqlc.narg('appendix')::text,
  $8,
  sqlc.narg('logo_url')::text,
  sqlc.narg('risk_info')::text,
  sqlc.narg('risk_score')::text,
  $9,
  $10,
  $11,
  sqlc.narg('lock_platform')::text,
  sqlc.narg('is_mintable')::text,
  $12,
  sqlc.narg('main_pair')::text,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20
)
ON CONFLICT (project_contract) DO UPDATE SET
  status = EXCLUDED.status,
  msg = EXCLUDED.msg,
  data_type = EXCLUDED.data_type,
  is_audited = EXCLUDED.is_audited,
  fetched_at = EXCLUDED.fetched_at,
  total = EXCLUDED.total,
  launch_price = EXCLUDED.launch_price,
  current_price_eth = EXCLUDED.current_price_eth,
  current_price_usd = EXCLUDED.current_price_usd,
  price_change_1d = EXCLUDED.price_change_1d,
  price_change_24h = EXCLUDED.price_change_24h,
  price_change_1h = EXCLUDED.price_change_1h,
  lock_amount = EXCLUDED.lock_amount,
  burn_amount = EXCLUDED.burn_amount,
  other_amount = EXCLUDED.other_amount,
  tx_amount_24h = EXCLUDED.tx_amount_24h,
  tx_volume_u_24h = EXCLUDED.tx_volume_u_24h,
  locked_percent = EXCLUDED.locked_percent,
  market_cap = EXCLUDED.market_cap,
  fdv = EXCLUDED.fdv,
  tvl = EXCLUDED.tvl,
  main_pair_tvl = EXCLUDED.main_pair_tvl,
  token_price_change_5m = EXCLUDED.token_price_change_5m,
  token_price_change_1h = EXCLUDED.token_price_change_1h,
  token_price_change_4h = EXCLUDED.token_price_change_4h,
  token_price_change_24h = EXCLUDED.token_price_change_24h,
  token_tx_volume_usd_5m = EXCLUDED.token_tx_volume_usd_5m,
  token_tx_volume_usd_1h = EXCLUDED.token_tx_volume_usd_1h,
  token_tx_volume_usd_4h = EXCLUDED.token_tx_volume_usd_4h,
  token_tx_volume_usd_24h = EXCLUDED.token_tx_volume_usd_24h,
  token_buy_volume_u_5m = EXCLUDED.token_buy_volume_u_5m,
  token_sell_volume_u_5m = EXCLUDED.token_sell_volume_u_5m,
  token = EXCLUDED.token,
  chain = EXCLUDED.chain,
  decimal = EXCLUDED.decimal,
  name = EXCLUDED.name,
  symbol = EXCLUDED.symbol,
  holders = EXCLUDED.holders,
  appendix = EXCLUDED.appendix,
  risk_level = EXCLUDED.risk_level,
  logo_url = EXCLUDED.logo_url,
  risk_info = EXCLUDED.risk_info,
  risk_score = EXCLUDED.risk_score,
  launch_at = EXCLUDED.launch_at,
  created_at = EXCLUDED.created_at,
  tx_count_24h = EXCLUDED.tx_count_24h,
  lock_platform = EXCLUDED.lock_platform,
  is_mintable = EXCLUDED.is_mintable,
  updated_at = EXCLUDED.updated_at,
  main_pair = EXCLUDED.main_pair,
  has_mint_method = EXCLUDED.has_mint_method,
  is_lp_not_locked = EXCLUDED.is_lp_not_locked,
  has_not_renounced = EXCLUDED.has_not_renounced,
  has_not_audited = EXCLUDED.has_not_audited,
  has_not_open_source = EXCLUDED.has_not_open_source,
  is_in_blacklist = EXCLUDED.is_in_blacklist,
  is_honeypot = EXCLUDED.is_honeypot,
  ave_risk_level = EXCLUDED.ave_risk_level;

-- name: DeleteProjectAvePairsByContract :exec
DELETE FROM project_ave_pair
WHERE project_contract = $1;

-- name: InsertProjectAvePair :exec
INSERT INTO project_ave_pair (
  project_contract,
  rank_index,
  reserve0,
  reserve1,
  token0_price_eth,
  token0_price_usd,
  token1_price_eth,
  token1_price_usd,
  price_change,
  price_change_24h,
  price_change_1h,
  volume_u,
  low_u,
  high_u,
  fee,
  total_supply,
  tx_amount,
  pair,
  chain,
  amm,
  token0_address,
  token0_symbol,
  token0_decimal,
  token1_address,
  token1_symbol,
  token1_decimal,
  target_token,
  price_change_1d,
  created_at,
  tx_count,
  updated_at,
  market_cap,
  fdv,
  is_fake
) VALUES (
  $1,
  $2,
  sqlc.narg('reserve0')::text,
  sqlc.narg('reserve1')::text,
  sqlc.narg('token0_price_eth')::text,
  sqlc.narg('token0_price_usd')::text,
  sqlc.narg('token1_price_eth')::text,
  sqlc.narg('token1_price_usd')::text,
  sqlc.narg('price_change')::text,
  sqlc.narg('price_change_24h')::text,
  sqlc.narg('price_change_1h')::text,
  sqlc.narg('volume_u')::text,
  sqlc.narg('low_u')::text,
  sqlc.narg('high_u')::text,
  sqlc.narg('fee')::text,
  sqlc.narg('total_supply')::text,
  sqlc.narg('tx_amount')::text,
  sqlc.narg('pair')::text,
  sqlc.narg('chain')::text,
  sqlc.narg('amm')::text,
  sqlc.narg('token0_address')::text,
  sqlc.narg('token0_symbol')::text,
  $3,
  sqlc.narg('token1_address')::text,
  sqlc.narg('token1_symbol')::text,
  $4,
  sqlc.narg('target_token')::text,
  sqlc.narg('price_change_1d')::text,
  $5,
  $6,
  $7,
  sqlc.narg('market_cap')::text,
  sqlc.narg('fdv')::text,
  $8
);

-- name: ListProjectAveTokenDetailsByContracts :many
SELECT project_contract,
  status,
  msg,
  data_type,
  is_audited,
  fetched_at,
  total,
  launch_price,
  current_price_eth,
  current_price_usd,
  price_change_1d,
  price_change_24h,
  price_change_1h,
  lock_amount,
  burn_amount,
  other_amount,
  tx_amount_24h,
  tx_volume_u_24h,
  locked_percent,
  market_cap,
  fdv,
  tvl,
  main_pair_tvl,
  token_price_change_5m,
  token_price_change_1h,
  token_price_change_4h,
  token_price_change_24h,
  token_tx_volume_usd_5m,
  token_tx_volume_usd_1h,
  token_tx_volume_usd_4h,
  token_tx_volume_usd_24h,
  token_buy_volume_u_5m,
  token_sell_volume_u_5m,
  token,
  chain,
  decimal,
  name,
  symbol,
  holders,
  appendix,
  risk_level,
  logo_url,
  risk_info,
  risk_score,
  launch_at,
  created_at,
  tx_count_24h,
  lock_platform,
  is_mintable,
  updated_at,
  main_pair,
  has_mint_method,
  is_lp_not_locked,
  has_not_renounced,
  has_not_audited,
  has_not_open_source,
  is_in_blacklist,
  is_honeypot,
  ave_risk_level
FROM project_ave_token_detail
WHERE project_contract = ANY($1::bytea[]);

-- name: ListProjectAvePairsByContracts :many
SELECT project_contract,
  rank_index,
  reserve0,
  reserve1,
  token0_price_eth,
  token0_price_usd,
  token1_price_eth,
  token1_price_usd,
  price_change,
  price_change_24h,
  price_change_1h,
  volume_u,
  low_u,
  high_u,
  fee,
  total_supply,
  tx_amount,
  pair,
  chain,
  amm,
  token0_address,
  token0_symbol,
  token0_decimal,
  token1_address,
  token1_symbol,
  token1_decimal,
  target_token,
  price_change_1d,
  created_at,
  tx_count,
  updated_at,
  market_cap,
  fdv,
  is_fake
FROM project_ave_pair
WHERE project_contract = ANY($1::bytea[])
ORDER BY project_contract, rank_index;
