// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sports_live_market.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertSportsLiveEvents = `-- name: BatchUpsertSportsLiveEvents :exec
INSERT INTO polymarket_sports_live_event (
  event_key,
  event_id,
  ticker,
  slug,
  title,
  description,
  resolution_source,
  start_date,
  creation_date,
  end_date,
  start_time,
  created_at_gamma,
  updated_at_gamma,
  image,
  icon,
  active,
  closed,
  archived,
  featured,
  restricted,
  live,
  ended,
  liquidity,
  volume,
  open_interest,
  category,
  score,
  period,
  elapsed,
  finished_timestamp,
  game_id,
  event_date,
  game_status,
  comment_count,
  sport,
  teams,
  tags,
  raw,
  fetched_at,
  last_seen_at
)
SELECT
  unnest($1::text[]),
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::text[]),
  unnest($7::text[]),
  unnest($8::timestamptz[]),
  unnest($9::timestamptz[]),
  unnest($10::timestamptz[]),
  unnest($11::timestamptz[]),
  unnest($12::timestamptz[]),
  unnest($13::timestamptz[]),
  unnest($14::text[]),
  unnest($15::text[]),
  unnest($16::boolean[]),
  unnest($17::boolean[]),
  unnest($18::boolean[]),
  unnest($19::boolean[]),
  unnest($20::boolean[]),
  unnest($21::boolean[]),
  unnest($22::boolean[]),
  unnest($23::double precision[]),
  unnest($24::double precision[]),
  unnest($25::double precision[]),
  unnest($26::text[]),
  unnest($27::text[]),
  unnest($28::text[]),
  unnest($29::text[]),
  unnest($30::text[]),
  unnest($31::bigint[]),
  unnest($32::text[]),
  unnest($33::text[]),
  unnest($34::bigint[]),
  unnest($35::jsonb[]),
  unnest($36::jsonb[]),
  unnest($37::jsonb[]),
  unnest($38::jsonb[]),
  unnest($39::timestamptz[]),
  unnest($40::timestamptz[])
ON CONFLICT (event_key) DO UPDATE
SET event_id = EXCLUDED.event_id,
  ticker = EXCLUDED.ticker,
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  resolution_source = EXCLUDED.resolution_source,
  start_date = EXCLUDED.start_date,
  creation_date = EXCLUDED.creation_date,
  end_date = EXCLUDED.end_date,
  start_time = EXCLUDED.start_time,
  created_at_gamma = EXCLUDED.created_at_gamma,
  updated_at_gamma = EXCLUDED.updated_at_gamma,
  image = EXCLUDED.image,
  icon = EXCLUDED.icon,
  active = EXCLUDED.active,
  closed = EXCLUDED.closed,
  archived = EXCLUDED.archived,
  featured = EXCLUDED.featured,
  restricted = EXCLUDED.restricted,
  live = EXCLUDED.live,
  ended = EXCLUDED.ended,
  liquidity = EXCLUDED.liquidity,
  volume = EXCLUDED.volume,
  open_interest = EXCLUDED.open_interest,
  category = EXCLUDED.category,
  score = EXCLUDED.score,
  period = EXCLUDED.period,
  elapsed = EXCLUDED.elapsed,
  finished_timestamp = EXCLUDED.finished_timestamp,
  game_id = EXCLUDED.game_id,
  event_date = EXCLUDED.event_date,
  game_status = EXCLUDED.game_status,
  comment_count = EXCLUDED.comment_count,
  sport = EXCLUDED.sport,
  teams = EXCLUDED.teams,
  tags = EXCLUDED.tags,
  raw = EXCLUDED.raw,
  fetched_at = EXCLUDED.fetched_at,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = now()
`

type BatchUpsertSportsLiveEventsParams struct {
	EventKeys            []string
	EventIds             []string
	Tickers              []string
	Slugs                []string
	Titles               []string
	Descriptions         []string
	ResolutionSources    []string
	StartDateValues      []pgtype.Timestamptz
	CreationDateValues   []pgtype.Timestamptz
	EndDateValues        []pgtype.Timestamptz
	StartTimeValues      []pgtype.Timestamptz
	CreatedAtGammaValues []pgtype.Timestamptz
	UpdatedAtGammaValues []pgtype.Timestamptz
	Images               []string
	Icons                []string
	ActiveValues         []bool
	ClosedValues         []bool
	ArchivedValues       []bool
	FeaturedValues       []bool
	RestrictedValues     []bool
	LiveValues           []bool
	EndedValues          []bool
	LiquidityValues      []float64
	VolumeValues         []float64
	OpenInterestValues   []float64
	Categories           []string
	Scores               []string
	Periods              []string
	ElapsedValues        []string
	FinishedTimestamps   []string
	GameIDValues         []int64
	EventDates           []string
	GameStatuses         []string
	CommentCountValues   []int64
	SportValues          [][]byte
	TeamsValues          [][]byte
	TagsValues           [][]byte
	RawValues            [][]byte
	FetchedAtValues      []pgtype.Timestamptz
	LastSeenAtValues     []pgtype.Timestamptz
}

func (q *Queries) BatchUpsertSportsLiveEvents(ctx context.Context, arg BatchUpsertSportsLiveEventsParams) error {
	_, err := q.db.Exec(ctx, batchUpsertSportsLiveEvents,
		arg.EventKeys,
		arg.EventIds,
		arg.Tickers,
		arg.Slugs,
		arg.Titles,
		arg.Descriptions,
		arg.ResolutionSources,
		arg.StartDateValues,
		arg.CreationDateValues,
		arg.EndDateValues,
		arg.StartTimeValues,
		arg.CreatedAtGammaValues,
		arg.UpdatedAtGammaValues,
		arg.Images,
		arg.Icons,
		arg.ActiveValues,
		arg.ClosedValues,
		arg.ArchivedValues,
		arg.FeaturedValues,
		arg.RestrictedValues,
		arg.LiveValues,
		arg.EndedValues,
		arg.LiquidityValues,
		arg.VolumeValues,
		arg.OpenInterestValues,
		arg.Categories,
		arg.Scores,
		arg.Periods,
		arg.ElapsedValues,
		arg.FinishedTimestamps,
		arg.GameIDValues,
		arg.EventDates,
		arg.GameStatuses,
		arg.CommentCountValues,
		arg.SportValues,
		arg.TeamsValues,
		arg.TagsValues,
		arg.RawValues,
		arg.FetchedAtValues,
		arg.LastSeenAtValues,
	)
	return err
}

const batchUpsertSportsLiveMarkets = `-- name: BatchUpsertSportsLiveMarkets :exec
INSERT INTO polymarket_sports_live_market (
  market_key,
  event_key,
  event_id,
  event_slug,
  market_id,
  condition_id,
  slug,
  question,
  title,
  description,
  resolution_source,
  sports_market_type,
  group_item_title,
  image,
  icon,
  outcomes,
  outcome_prices,
  clob_token_ids,
  active,
  closed,
  archived,
  restricted,
  enable_order_book,
  volume,
  volume_num,
  liquidity_num,
  volume_24hr,
  volume_1wk,
  volume_1mo,
  volume_1yr,
  spread,
  best_bid,
  best_ask,
  last_trade_price,
  start_date,
  end_date,
  created_at_gamma,
  updated_at_gamma,
  tags,
  raw,
  fetched_at,
  last_seen_at
)
SELECT
  unnest($1::text[]),
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::text[]),
  unnest($7::text[]),
  unnest($8::text[]),
  unnest($9::text[]),
  unnest($10::text[]),
  unnest($11::text[]),
  unnest($12::text[]),
  unnest($13::text[]),
  unnest($14::text[]),
  unnest($15::text[]),
  unnest($16::text[]),
  unnest($17::text[]),
  unnest($18::text[]),
  unnest($19::boolean[]),
  unnest($20::boolean[]),
  unnest($21::boolean[]),
  unnest($22::boolean[]),
  unnest($23::boolean[]),
  unnest($24::text[]),
  unnest($25::double precision[]),
  unnest($26::double precision[]),
  unnest($27::double precision[]),
  unnest($28::double precision[]),
  unnest($29::double precision[]),
  unnest($30::double precision[]),
  unnest($31::double precision[]),
  unnest($32::double precision[]),
  unnest($33::double precision[]),
  unnest($34::double precision[]),
  unnest($35::timestamptz[]),
  unnest($36::timestamptz[]),
  unnest($37::timestamptz[]),
  unnest($38::timestamptz[]),
  unnest($39::jsonb[]),
  unnest($40::jsonb[]),
  unnest($41::timestamptz[]),
  unnest($42::timestamptz[])
ON CONFLICT (market_key) DO UPDATE
SET event_key = EXCLUDED.event_key,
  event_id = EXCLUDED.event_id,
  event_slug = EXCLUDED.event_slug,
  market_id = EXCLUDED.market_id,
  condition_id = EXCLUDED.condition_id,
  slug = EXCLUDED.slug,
  question = EXCLUDED.question,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  resolution_source = EXCLUDED.resolution_source,
  sports_market_type = EXCLUDED.sports_market_type,
  group_item_title = EXCLUDED.group_item_title,
  image = EXCLUDED.image,
  icon = EXCLUDED.icon,
  outcomes = EXCLUDED.outcomes,
  outcome_prices = EXCLUDED.outcome_prices,
  clob_token_ids = EXCLUDED.clob_token_ids,
  active = EXCLUDED.active,
  closed = EXCLUDED.closed,
  archived = EXCLUDED.archived,
  restricted = EXCLUDED.restricted,
  enable_order_book = EXCLUDED.enable_order_book,
  volume = EXCLUDED.volume,
  volume_num = EXCLUDED.volume_num,
  liquidity_num = EXCLUDED.liquidity_num,
  volume_24hr = EXCLUDED.volume_24hr,
  volume_1wk = EXCLUDED.volume_1wk,
  volume_1mo = EXCLUDED.volume_1mo,
  volume_1yr = EXCLUDED.volume_1yr,
  spread = EXCLUDED.spread,
  best_bid = EXCLUDED.best_bid,
  best_ask = EXCLUDED.best_ask,
  last_trade_price = EXCLUDED.last_trade_price,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  created_at_gamma = EXCLUDED.created_at_gamma,
  updated_at_gamma = EXCLUDED.updated_at_gamma,
  tags = EXCLUDED.tags,
  raw = EXCLUDED.raw,
  fetched_at = EXCLUDED.fetched_at,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = now()
`

type BatchUpsertSportsLiveMarketsParams struct {
	MarketKeys            []string
	EventKeys             []string
	EventIds              []string
	EventSlugs            []string
	MarketIds             []string
	ConditionIds          []string
	Slugs                 []string
	Questions             []string
	Titles                []string
	Descriptions          []string
	ResolutionSources     []string
	SportsMarketTypes     []string
	GroupItemTitles       []string
	Images                []string
	Icons                 []string
	OutcomesValues        []string
	OutcomePricesValues   []string
	ClobTokenIdsValues    []string
	ActiveValues          []bool
	ClosedValues          []bool
	ArchivedValues        []bool
	RestrictedValues      []bool
	EnableOrderBookValues []bool
	VolumeValues          []string
	VolumeNumValues       []float64
	LiquidityNumValues    []float64
	Volume24hrValues      []float64
	Volume1wkValues       []float64
	Volume1moValues       []float64
	Volume1yrValues       []float64
	SpreadValues          []float64
	BestBidValues         []float64
	BestAskValues         []float64
	LastTradePriceValues  []float64
	StartDateValues       []pgtype.Timestamptz
	EndDateValues         []pgtype.Timestamptz
	CreatedAtGammaValues  []pgtype.Timestamptz
	UpdatedAtGammaValues  []pgtype.Timestamptz
	TagsValues            [][]byte
	RawValues             [][]byte
	FetchedAtValues       []pgtype.Timestamptz
	LastSeenAtValues      []pgtype.Timestamptz
}

func (q *Queries) BatchUpsertSportsLiveMarkets(ctx context.Context, arg BatchUpsertSportsLiveMarketsParams) error {
	_, err := q.db.Exec(ctx, batchUpsertSportsLiveMarkets,
		arg.MarketKeys,
		arg.EventKeys,
		arg.EventIds,
		arg.EventSlugs,
		arg.MarketIds,
		arg.ConditionIds,
		arg.Slugs,
		arg.Questions,
		arg.Titles,
		arg.Descriptions,
		arg.ResolutionSources,
		arg.SportsMarketTypes,
		arg.GroupItemTitles,
		arg.Images,
		arg.Icons,
		arg.OutcomesValues,
		arg.OutcomePricesValues,
		arg.ClobTokenIdsValues,
		arg.ActiveValues,
		arg.ClosedValues,
		arg.ArchivedValues,
		arg.RestrictedValues,
		arg.EnableOrderBookValues,
		arg.VolumeValues,
		arg.VolumeNumValues,
		arg.LiquidityNumValues,
		arg.Volume24hrValues,
		arg.Volume1wkValues,
		arg.Volume1moValues,
		arg.Volume1yrValues,
		arg.SpreadValues,
		arg.BestBidValues,
		arg.BestAskValues,
		arg.LastTradePriceValues,
		arg.StartDateValues,
		arg.EndDateValues,
		arg.CreatedAtGammaValues,
		arg.UpdatedAtGammaValues,
		arg.TagsValues,
		arg.RawValues,
		arg.FetchedAtValues,
		arg.LastSeenAtValues,
	)
	return err
}

const batchUpsertSportsLivePricePoints = `-- name: BatchUpsertSportsLivePricePoints :exec
INSERT INTO polymarket_sports_live_price_point (
  token_id,
  market_key,
  event_key,
  condition_id,
  outcome,
  price_ts,
  price,
  fetched_at
)
SELECT
  unnest($1::text[]),
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::timestamptz[]),
  unnest($7::double precision[]),
  unnest($8::timestamptz[])
ON CONFLICT (token_id, price_ts) DO UPDATE
SET market_key = EXCLUDED.market_key,
  event_key = EXCLUDED.event_key,
  condition_id = EXCLUDED.condition_id,
  outcome = EXCLUDED.outcome,
  price = EXCLUDED.price,
  fetched_at = EXCLUDED.fetched_at,
  updated_at = now()
`

type BatchUpsertSportsLivePricePointsParams struct {
	TokenIds        []string
	MarketKeys      []string
	EventKeys       []string
	ConditionIds    []string
	Outcomes        []string
	PriceTsValues   []pgtype.Timestamptz
	PriceValues     []float64
	FetchedAtValues []pgtype.Timestamptz
}

func (q *Queries) BatchUpsertSportsLivePricePoints(ctx context.Context, arg BatchUpsertSportsLivePricePointsParams) error {
	_, err := q.db.Exec(ctx, batchUpsertSportsLivePricePoints,
		arg.TokenIds,
		arg.MarketKeys,
		arg.EventKeys,
		arg.ConditionIds,
		arg.Outcomes,
		arg.PriceTsValues,
		arg.PriceValues,
		arg.FetchedAtValues,
	)
	return err
}

const deleteSportsLiveEventsNotSeenSince = `-- name: DeleteSportsLiveEventsNotSeenSince :execrows
DELETE FROM polymarket_sports_live_event
WHERE last_seen_at < $1
`

func (q *Queries) DeleteSportsLiveEventsNotSeenSince(ctx context.Context, lastSeenAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSportsLiveEventsNotSeenSince, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSportsLiveMarketsNotSeenSince = `-- name: DeleteSportsLiveMarketsNotSeenSince :execrows
DELETE FROM polymarket_sports_live_market
WHERE last_seen_at < $1
`

func (q *Queries) DeleteSportsLiveMarketsNotSeenSince(ctx context.Context, lastSeenAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSportsLiveMarketsNotSeenSince, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSportsLivePriceAlertState = `-- name: DeleteSportsLivePriceAlertState :exec
DELETE FROM polymarket_sports_live_price_alert_state
WHERE token_id = $1
`

func (q *Queries) DeleteSportsLivePriceAlertState(ctx context.Context, tokenID string) error {
	_, err := q.db.Exec(ctx, deleteSportsLivePriceAlertState, tokenID)
	return err
}

const getPolymarketSyncState = `-- name: GetPolymarketSyncState :one
SELECT last_success_at
FROM polymarket_sync_state
WHERE sync_name = $1
`

func (q *Queries) GetPolymarketSyncState(ctx context.Context, syncName string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPolymarketSyncState, syncName)
	var last_success_at pgtype.Timestamptz
	err := row.Scan(&last_success_at)
	return last_success_at, err
}

const listSportsLiveEvents = `-- name: ListSportsLiveEvents :many
SELECT
  event.event_key,
  event.event_id,
  event.slug,
  event.title,
  COALESCE(NULLIF(event.image, ''), event.icon)::text AS image,
  event.score,
  event.period,
  event.elapsed,
  event.game_status,
  event.start_time,
  event.updated_at_gamma,
  event.liquidity,
  event.volume,
  COUNT(market.market_key)::bigint AS market_count,
  event.teams,
  event.fetched_at,
  event.last_seen_at
FROM polymarket_sports_live_event AS event
JOIN polymarket_sports_live_market AS market ON market.event_key = event.event_key
  AND lower(market.sports_market_type) = 'moneyline'
GROUP BY event.event_key
ORDER BY event.volume DESC, event.liquidity DESC, event.updated_at_gamma DESC NULLS LAST, event.event_key
LIMIT $1
`

type ListSportsLiveEventsRow struct {
	EventKey       string
	EventID        string
	Slug           string
	Title          string
	Image          string
	Score          string
	Period         string
	Elapsed        string
	GameStatus     string
	StartTime      pgtype.Timestamptz
	UpdatedAtGamma pgtype.Timestamptz
	Liquidity      float64
	Volume         float64
	MarketCount    int64
	Teams          []byte
	FetchedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}

func (q *Queries) ListSportsLiveEvents(ctx context.Context, limit int32) ([]ListSportsLiveEventsRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveEventsRow
	for rows.Next() {
		var i ListSportsLiveEventsRow
		if err := rows.Scan(
			&i.EventKey,
			&i.EventID,
			&i.Slug,
			&i.Title,
			&i.Image,
			&i.Score,
			&i.Period,
			&i.Elapsed,
			&i.GameStatus,
			&i.StartTime,
			&i.UpdatedAtGamma,
			&i.Liquidity,
			&i.Volume,
			&i.MarketCount,
			&i.Teams,
			&i.FetchedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLiveLatestPriceAlertTokens = `-- name: ListSportsLiveLatestPriceAlertTokens :many
WITH latest_points AS (
  SELECT DISTINCT ON (point.token_id)
    point.token_id,
    point.market_key,
    point.event_key,
    point.condition_id,
    point.outcome,
    point.price_ts,
    point.price
  FROM polymarket_sports_live_price_point AS point
  JOIN polymarket_sports_live_market AS market ON market.market_key = point.market_key
  JOIN polymarket_sports_live_event AS event ON event.event_key = point.event_key
  WHERE event.live = true
    AND event.ended = false
    AND market.closed = false
    AND lower(market.sports_market_type) = 'moneyline'
  ORDER BY point.token_id, point.price_ts DESC
)
SELECT
  latest.token_id,
  latest.market_key,
  latest.event_key,
  latest.condition_id,
  latest.outcome,
  latest.price_ts,
  latest.price,
  event.slug AS event_slug,
  COALESCE(NULLIF(event.title, ''), event.slug, latest.event_key)::text AS event_title,
  COALESCE(NULLIF(market.question, ''), NULLIF(market.title, ''), market.market_key)::text AS market_title,
  event.score,
  event.period,
  event.elapsed,
  event.game_status,
  event.volume,
  event.liquidity,
  COALESCE(state.alert_band, '')::text AS last_alert_band,
  state.last_alerted_at
FROM latest_points AS latest
JOIN polymarket_sports_live_market AS market ON market.market_key = latest.market_key
JOIN polymarket_sports_live_event AS event ON event.event_key = latest.event_key
LEFT JOIN polymarket_sports_live_price_alert_state AS state ON state.token_id = latest.token_id
ORDER BY event.volume DESC, market.liquidity_num DESC, latest.market_key, latest.token_id
`

type ListSportsLiveLatestPriceAlertTokensRow struct {
	TokenID       string
	MarketKey     string
	EventKey      string
	ConditionID   string
	Outcome       string
	PriceTs       pgtype.Timestamptz
	Price         float64
	EventSlug     string
	EventTitle    string
	MarketTitle   string
	Score         string
	Period        string
	Elapsed       string
	GameStatus    string
	Volume        float64
	Liquidity     float64
	LastAlertBand string
	LastAlertedAt pgtype.Timestamptz
}

func (q *Queries) ListSportsLiveLatestPriceAlertTokens(ctx context.Context) ([]ListSportsLiveLatestPriceAlertTokensRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveLatestPriceAlertTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveLatestPriceAlertTokensRow
	for rows.Next() {
		var i ListSportsLiveLatestPriceAlertTokensRow
		if err := rows.Scan(
			&i.TokenID,
			&i.MarketKey,
			&i.EventKey,
			&i.ConditionID,
			&i.Outcome,
			&i.PriceTs,
			&i.Price,
			&i.EventSlug,
			&i.EventTitle,
			&i.MarketTitle,
			&i.Score,
			&i.Period,
			&i.Elapsed,
			&i.GameStatus,
			&i.Volume,
			&i.Liquidity,
			&i.LastAlertBand,
			&i.LastAlertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLiveLatestPricePointTimes = `-- name: ListSportsLiveLatestPricePointTimes :many
SELECT
  token_id,
  MAX(price_ts)::timestamptz AS price_ts
FROM polymarket_sports_live_price_point
WHERE token_id = ANY($1::text[])
GROUP BY token_id
`

type ListSportsLiveLatestPricePointTimesRow struct {
	TokenID string
	PriceTs pgtype.Timestamptz
}

func (q *Queries) ListSportsLiveLatestPricePointTimes(ctx context.Context, tokenIds []string) ([]ListSportsLiveLatestPricePointTimesRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveLatestPricePointTimes, tokenIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveLatestPricePointTimesRow
	for rows.Next() {
		var i ListSportsLiveLatestPricePointTimesRow
		if err := rows.Scan(&i.TokenID, &i.PriceTs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLiveMarketsByEventKeys = `-- name: ListSportsLiveMarketsByEventKeys :many
SELECT
  market.event_key,
  market.market_key,
  market.condition_id,
  market.slug,
  market.sports_market_type,
  COALESCE(NULLIF(market.question, ''), market.title)::text AS question,
  market.outcomes,
  market.outcome_prices,
  market.best_bid,
  market.best_ask,
  market.last_trade_price,
  market.spread,
  market.liquidity_num,
  market.volume_num,
  market.updated_at_gamma
FROM polymarket_sports_live_market AS market
WHERE market.event_key = ANY($1::text[])
  AND lower(market.sports_market_type) = 'moneyline'
ORDER BY market.event_key, market.liquidity_num DESC, market.volume_num DESC, market.market_key
`

type ListSportsLiveMarketsByEventKeysRow struct {
	EventKey         string
	MarketKey        string
	ConditionID      string
	Slug             string
	SportsMarketType string
	Question         string
	Outcomes         string
	OutcomePrices    string
	BestBid          float64
	BestAsk          float64
	LastTradePrice   float64
	Spread           float64
	LiquidityNum     float64
	VolumeNum        float64
	UpdatedAtGamma   pgtype.Timestamptz
}

func (q *Queries) ListSportsLiveMarketsByEventKeys(ctx context.Context, eventKeys []string) ([]ListSportsLiveMarketsByEventKeysRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveMarketsByEventKeys, eventKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveMarketsByEventKeysRow
	for rows.Next() {
		var i ListSportsLiveMarketsByEventKeysRow
		if err := rows.Scan(
			&i.EventKey,
			&i.MarketKey,
			&i.ConditionID,
			&i.Slug,
			&i.SportsMarketType,
			&i.Question,
			&i.Outcomes,
			&i.OutcomePrices,
			&i.BestBid,
			&i.BestAsk,
			&i.LastTradePrice,
			&i.Spread,
			&i.LiquidityNum,
			&i.VolumeNum,
			&i.UpdatedAtGamma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLiveMoneylineMarketsForPriceHistory = `-- name: ListSportsLiveMoneylineMarketsForPriceHistory :many
SELECT
  market.event_key,
  market.market_key,
  market.condition_id,
  market.outcomes,
  market.clob_token_ids
FROM polymarket_sports_live_market AS market
JOIN polymarket_sports_live_event AS event ON event.event_key = market.event_key
WHERE event.live = true
  AND event.ended = false
  AND market.closed = false
  AND lower(market.sports_market_type) = 'moneyline'
  AND btrim(market.clob_token_ids) <> ''
ORDER BY event.volume DESC, market.liquidity_num DESC, market.market_key
`

type ListSportsLiveMoneylineMarketsForPriceHistoryRow struct {
	EventKey     string
	MarketKey    string
	ConditionID  string
	Outcomes     string
	ClobTokenIds string
}

func (q *Queries) ListSportsLiveMoneylineMarketsForPriceHistory(ctx context.Context) ([]ListSportsLiveMoneylineMarketsForPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveMoneylineMarketsForPriceHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveMoneylineMarketsForPriceHistoryRow
	for rows.Next() {
		var i ListSportsLiveMoneylineMarketsForPriceHistoryRow
		if err := rows.Scan(
			&i.EventKey,
			&i.MarketKey,
			&i.ConditionID,
			&i.Outcomes,
			&i.ClobTokenIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLivePriceHistoryByMarketKeys = `-- name: ListSportsLivePriceHistoryByMarketKeys :many
WITH ranked_points AS (
  SELECT
    point.market_key,
    point.token_id,
    point.outcome,
    point.price_ts,
    point.price,
    row_number() OVER (
      PARTITION BY point.market_key, point.token_id
      ORDER BY point.price_ts DESC
    ) AS row_num
  FROM polymarket_sports_live_price_point AS point
  JOIN polymarket_sports_live_market AS market ON market.market_key = point.market_key
  WHERE point.market_key = ANY($2::text[])
    AND lower(market.sports_market_type) = 'moneyline'
)
SELECT
  market_key,
  token_id,
  outcome,
  price_ts,
  price
FROM ranked_points
WHERE row_num <= $1::int
ORDER BY market_key, token_id, price_ts
`

type ListSportsLivePriceHistoryByMarketKeysParams struct {
	LimitPerToken int32
	MarketKeys    []string
}

type ListSportsLivePriceHistoryByMarketKeysRow struct {
	MarketKey string
	TokenID   string
	Outcome   string
	PriceTs   pgtype.Timestamptz
	Price     float64
}

func (q *Queries) ListSportsLivePriceHistoryByMarketKeys(ctx context.Context, arg ListSportsLivePriceHistoryByMarketKeysParams) ([]ListSportsLivePriceHistoryByMarketKeysRow, error) {
	rows, err := q.db.Query(ctx, listSportsLivePriceHistoryByMarketKeys, arg.LimitPerToken, arg.MarketKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLivePriceHistoryByMarketKeysRow
	for rows.Next() {
		var i ListSportsLivePriceHistoryByMarketKeysRow
		if err := rows.Scan(
			&i.MarketKey,
			&i.TokenID,
			&i.Outcome,
			&i.PriceTs,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportsLiveScoreAlertCandidates = `-- name: ListSportsLiveScoreAlertCandidates :many
SELECT
  event.event_key,
  event.slug,
  lower(split_part(btrim(event.slug), '-', 1))::text AS sport_type,
  COALESCE(NULLIF(event.title, ''), event.slug, event.event_key)::text AS title,
  state.last_score AS previous_score,
  btrim(event.score)::text AS score,
  event.period,
  event.elapsed,
  event.game_status,
  event.fetched_at
FROM polymarket_sports_live_event AS event
JOIN polymarket_sports_live_score_alert_state AS state ON state.event_key = event.event_key
WHERE lower(split_part(btrim(event.slug), '-', 1)) IN ('fifwc', 'mlb')
  AND event.live = true
  AND event.ended = false
  AND btrim(event.score) <> ''
  AND btrim(event.score) <> state.last_score
ORDER BY event.volume DESC, event.event_key
`

type ListSportsLiveScoreAlertCandidatesRow struct {
	EventKey      string
	Slug          string
	SportType     string
	Title         string
	PreviousScore string
	Score         string
	Period        string
	Elapsed       string
	GameStatus    string
	FetchedAt     pgtype.Timestamptz
}

func (q *Queries) ListSportsLiveScoreAlertCandidates(ctx context.Context) ([]ListSportsLiveScoreAlertCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSportsLiveScoreAlertCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportsLiveScoreAlertCandidatesRow
	for rows.Next() {
		var i ListSportsLiveScoreAlertCandidatesRow
		if err := rows.Scan(
			&i.EventKey,
			&i.Slug,
			&i.SportType,
			&i.Title,
			&i.PreviousScore,
			&i.Score,
			&i.Period,
			&i.Elapsed,
			&i.GameStatus,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedSportsLiveScoreAlertStates = `-- name: SeedSportsLiveScoreAlertStates :exec
INSERT INTO polymarket_sports_live_score_alert_state (
  event_key,
  last_score
)
SELECT
  event.event_key,
  btrim(event.score)
FROM polymarket_sports_live_event AS event
WHERE lower(split_part(btrim(event.slug), '-', 1)) IN ('fifwc', 'mlb')
  AND event.live = true
  AND event.ended = false
  AND btrim(event.score) <> ''
ON CONFLICT (event_key) DO NOTHING
`

func (q *Queries) SeedSportsLiveScoreAlertStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedSportsLiveScoreAlertStates)
	return err
}

const updateSportsLiveScoreAlertState = `-- name: UpdateSportsLiveScoreAlertState :exec
UPDATE polymarket_sports_live_score_alert_state
SET last_score = btrim($1),
  notification_id = $2,
  last_notified_at = $3,
  updated_at = now()
WHERE event_key = $4
`

type UpdateSportsLiveScoreAlertStateParams struct {
	Score          string
	NotificationID int64
	LastNotifiedAt pgtype.Timestamptz
	EventKey       string
}

func (q *Queries) UpdateSportsLiveScoreAlertState(ctx context.Context, arg UpdateSportsLiveScoreAlertStateParams) error {
	_, err := q.db.Exec(ctx, updateSportsLiveScoreAlertState,
		arg.Score,
		arg.NotificationID,
		arg.LastNotifiedAt,
		arg.EventKey,
	)
	return err
}

const upsertPolymarketSyncState = `-- name: UpsertPolymarketSyncState :exec
INSERT INTO polymarket_sync_state (sync_name, last_success_at)
VALUES ($1, $2)
ON CONFLICT (sync_name) DO UPDATE
SET last_success_at = EXCLUDED.last_success_at,
  updated_at = now()
`

type UpsertPolymarketSyncStateParams struct {
	SyncName      string
	LastSuccessAt pgtype.Timestamptz
}

func (q *Queries) UpsertPolymarketSyncState(ctx context.Context, arg UpsertPolymarketSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertPolymarketSyncState, arg.SyncName, arg.LastSuccessAt)
	return err
}

const upsertSportsLivePriceAlertState = `-- name: UpsertSportsLivePriceAlertState :exec
INSERT INTO polymarket_sports_live_price_alert_state (
  token_id,
  market_key,
  event_key,
  condition_id,
  outcome,
  alert_band,
  last_alerted_at,
  last_price_ts,
  last_price
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (token_id) DO UPDATE
SET market_key = EXCLUDED.market_key,
  event_key = EXCLUDED.event_key,
  condition_id = EXCLUDED.condition_id,
  outcome = EXCLUDED.outcome,
  alert_band = EXCLUDED.alert_band,
  last_alerted_at = EXCLUDED.last_alerted_at,
  last_price_ts = EXCLUDED.last_price_ts,
  last_price = EXCLUDED.last_price,
  updated_at = now()
`

type UpsertSportsLivePriceAlertStateParams struct {
	TokenID       string
	MarketKey     string
	EventKey      string
	ConditionID   string
	Outcome       string
	AlertBand     string
	LastAlertedAt pgtype.Timestamptz
	LastPriceTs   pgtype.Timestamptz
	LastPrice     float64
}

func (q *Queries) UpsertSportsLivePriceAlertState(ctx context.Context, arg UpsertSportsLivePriceAlertStateParams) error {
	_, err := q.db.Exec(ctx, upsertSportsLivePriceAlertState,
		arg.TokenID,
		arg.MarketKey,
		arg.EventKey,
		arg.ConditionID,
		arg.Outcome,
		arg.AlertBand,
		arg.LastAlertedAt,
		arg.LastPriceTs,
		arg.LastPrice,
	)
	return err
}
