kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: athena-redis-ha-haproxy
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: athena
  name: athena-redis-ha-proxy-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: athena-redis-ha-haproxy
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: athena-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: athena-repo-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: athena-application-controller
    ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  - from:
    - namespaceSelector: {}
    ports:
    - port: 9101
      protocol: TCP

