// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingAccountNotificationDeliveries = `-- name: CancelPendingAccountNotificationDeliveries :execrows
UPDATE account_notification_deliveries
SET status = 'cancelled',
    error_message = 'telegram binding disconnected',
    locked_at = NULL,
    locked_by = NULL
WHERE account_id = $1
  AND status = 'pending'
`

func (q *Queries) CancelPendingAccountNotificationDeliveries(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingAccountNotificationDeliveries, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelPendingAccountNotificationDeliveriesForBinding = `-- name: CancelPendingAccountNotificationDeliveriesForBinding :execrows
UPDATE account_notification_deliveries
SET status = 'cancelled',
    error_message = 'telegram recipient is unreachable',
    locked_at = NULL,
    locked_by = NULL
WHERE account_id = $1
  AND telegram_chat_id = $2
  AND binding_revision = $3
  AND status = 'pending'
`

type CancelPendingAccountNotificationDeliveriesForBindingParams struct {
	AccountID       pgtype.UUID
	TelegramChatID  int64
	BindingRevision int64
}

func (q *Queries) CancelPendingAccountNotificationDeliveriesForBinding(ctx context.Context, arg CancelPendingAccountNotificationDeliveriesForBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingAccountNotificationDeliveriesForBinding, arg.AccountID, arg.TelegramChatID, arg.BindingRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingAccountNotificationDeliveries = `-- name: ClaimPendingAccountNotificationDeliveries :many
WITH ready AS (
  SELECT id
  FROM account_notification_deliveries
  WHERE status = 'pending'
    AND next_attempt_at <= NOW()
    AND (locked_at IS NULL OR locked_at < NOW() - $3::interval)
    AND EXISTS (
      SELECT 1
      FROM telegram_bindings AS binding
      WHERE binding.account_id = account_notification_deliveries.account_id
        AND binding.telegram_chat_id = account_notification_deliveries.telegram_chat_id
        AND binding.revision = account_notification_deliveries.binding_revision
        AND binding.status = 'connected'
    )
  ORDER BY created_at ASC, id ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE account_notification_deliveries AS delivery
SET locked_at = NOW(),
    locked_by = $2,
    attempts = delivery.attempts + 1,
    last_attempt_at = NOW()
FROM ready
WHERE delivery.id = ready.id
RETURNING delivery.id, delivery.account_id, delivery.source, delivery.severity,
  COALESCE(delivery.title, '') AS title, delivery.body,
  COALESCE(delivery.link, '') AS link, delivery.channel, delivery.status,
  delivery.telegram_chat_id, delivery.binding_revision, delivery.attempts
`

type ClaimPendingAccountNotificationDeliveriesParams struct {
	Limit       int32
	LockedBy    pgtype.Text
	LockTimeout pgtype.Interval
}

type ClaimPendingAccountNotificationDeliveriesRow struct {
	ID              int64
	AccountID       pgtype.UUID
	Source          string
	Severity        string
	Title           string
	Body            string
	Link            string
	Channel         string
	Status          string
	TelegramChatID  int64
	BindingRevision int64
	Attempts        int32
}

func (q *Queries) ClaimPendingAccountNotificationDeliveries(ctx context.Context, arg ClaimPendingAccountNotificationDeliveriesParams) ([]ClaimPendingAccountNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingAccountNotificationDeliveries, arg.Limit, arg.LockedBy, arg.LockTimeout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingAccountNotificationDeliveriesRow
	for rows.Next() {
		var i ClaimPendingAccountNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Source,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Channel,
			&i.Status,
			&i.TelegramChatID,
			&i.BindingRevision,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccountNotificationDelivery = `-- name: CreateAccountNotificationDelivery :one
INSERT INTO account_notification_deliveries (
  account_id, idempotency_key, payload_digest, source, severity, title, body,
  link, channel, status, telegram_chat_id, binding_revision
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (account_id, source, idempotency_key) DO NOTHING
RETURNING id, account_id, idempotency_key, payload_digest, source, severity,
  COALESCE(title, '') AS title, body, COALESCE(link, '') AS link, channel, status,
  telegram_chat_id, binding_revision, provider_message_id, error_message,
  created_at, sent_at
`

type CreateAccountNotificationDeliveryParams struct {
	AccountID       pgtype.UUID
	IdempotencyKey  string
	PayloadDigest   []byte
	Source          string
	Severity        string
	Title           pgtype.Text
	Body            string
	Link            pgtype.Text
	Channel         string
	Status          string
	TelegramChatID  int64
	BindingRevision int64
}

type CreateAccountNotificationDeliveryRow struct {
	ID                int64
	AccountID         pgtype.UUID
	IdempotencyKey    string
	PayloadDigest     []byte
	Source            string
	Severity          string
	Title             string
	Body              string
	Link              string
	Channel           string
	Status            string
	TelegramChatID    int64
	BindingRevision   int64
	ProviderMessageID pgtype.Text
	ErrorMessage      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
}

func (q *Queries) CreateAccountNotificationDelivery(ctx context.Context, arg CreateAccountNotificationDeliveryParams) (CreateAccountNotificationDeliveryRow, error) {
	row := q.db.QueryRow(ctx, createAccountNotificationDelivery,
		arg.AccountID,
		arg.IdempotencyKey,
		arg.PayloadDigest,
		arg.Source,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Channel,
		arg.Status,
		arg.TelegramChatID,
		arg.BindingRevision,
	)
	var i CreateAccountNotificationDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.PayloadDigest,
		&i.Source,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Channel,
		&i.Status,
		&i.TelegramChatID,
		&i.BindingRevision,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getAccountNotificationDeliveryByIdempotency = `-- name: GetAccountNotificationDeliveryByIdempotency :one
SELECT id, account_id, idempotency_key, payload_digest, source, severity,
  COALESCE(title, '') AS title, body, COALESCE(link, '') AS link, channel, status,
  telegram_chat_id, binding_revision, provider_message_id, error_message,
  created_at, sent_at
FROM account_notification_deliveries
WHERE account_id = $1
  AND source = $2
  AND idempotency_key = $3
`

type GetAccountNotificationDeliveryByIdempotencyParams struct {
	AccountID      pgtype.UUID
	Source         string
	IdempotencyKey string
}

type GetAccountNotificationDeliveryByIdempotencyRow struct {
	ID                int64
	AccountID         pgtype.UUID
	IdempotencyKey    string
	PayloadDigest     []byte
	Source            string
	Severity          string
	Title             string
	Body              string
	Link              string
	Channel           string
	Status            string
	TelegramChatID    int64
	BindingRevision   int64
	ProviderMessageID pgtype.Text
	ErrorMessage      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
}

func (q *Queries) GetAccountNotificationDeliveryByIdempotency(ctx context.Context, arg GetAccountNotificationDeliveryByIdempotencyParams) (GetAccountNotificationDeliveryByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getAccountNotificationDeliveryByIdempotency, arg.AccountID, arg.Source, arg.IdempotencyKey)
	var i GetAccountNotificationDeliveryByIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.PayloadDigest,
		&i.Source,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Channel,
		&i.Status,
		&i.TelegramChatID,
		&i.BindingRevision,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getAccountNotificationRuntimeCounts = `-- name: GetAccountNotificationRuntimeCounts :one
SELECT
  (SELECT COUNT(*)::bigint FROM account_notification_deliveries WHERE status = 'pending') AS pending_count,
  (SELECT COUNT(*)::bigint FROM account_notification_deliveries WHERE status = 'pending' AND attempts > 0) AS retry_count,
  (SELECT COUNT(*)::bigint FROM account_notification_deliveries WHERE status = 'failed') AS failed_count,
  (SELECT COUNT(*)::bigint FROM telegram_bindings WHERE status = 'unreachable') AS unreachable_binding_count
`

type GetAccountNotificationRuntimeCountsRow struct {
	PendingCount            int64
	RetryCount              int64
	FailedCount             int64
	UnreachableBindingCount int64
}

func (q *Queries) GetAccountNotificationRuntimeCounts(ctx context.Context) (GetAccountNotificationRuntimeCountsRow, error) {
	row := q.db.QueryRow(ctx, getAccountNotificationRuntimeCounts)
	var i GetAccountNotificationRuntimeCountsRow
	err := row.Scan(
		&i.PendingCount,
		&i.RetryCount,
		&i.FailedCount,
		&i.UnreachableBindingCount,
	)
	return i, err
}

const getPendingAccountNotificationDeliveryForUpdate = `-- name: GetPendingAccountNotificationDeliveryForUpdate :one
SELECT id
FROM account_notification_deliveries
WHERE id = $1
  AND account_id = $2
  AND telegram_chat_id = $3
  AND binding_revision = $4
  AND status = 'pending'
FOR UPDATE
`

type GetPendingAccountNotificationDeliveryForUpdateParams struct {
	ID              int64
	AccountID       pgtype.UUID
	TelegramChatID  int64
	BindingRevision int64
}

func (q *Queries) GetPendingAccountNotificationDeliveryForUpdate(ctx context.Context, arg GetPendingAccountNotificationDeliveryForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPendingAccountNotificationDeliveryForUpdate,
		arg.ID,
		arg.AccountID,
		arg.TelegramChatID,
		arg.BindingRevision,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markAccountNotificationDeliveryFailed = `-- name: MarkAccountNotificationDeliveryFailed :execrows
UPDATE account_notification_deliveries
SET status = 'failed',
    error_message = $1,
    locked_at = NULL,
    locked_by = NULL
WHERE id = $2
  AND account_id = $3
  AND telegram_chat_id = $4
  AND binding_revision = $5
  AND status = 'pending'
`

type MarkAccountNotificationDeliveryFailedParams struct {
	ErrorMessage    pgtype.Text
	ID              int64
	AccountID       pgtype.UUID
	TelegramChatID  int64
	BindingRevision int64
}

func (q *Queries) MarkAccountNotificationDeliveryFailed(ctx context.Context, arg MarkAccountNotificationDeliveryFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAccountNotificationDeliveryFailed,
		arg.ErrorMessage,
		arg.ID,
		arg.AccountID,
		arg.TelegramChatID,
		arg.BindingRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAccountNotificationDeliverySent = `-- name: MarkAccountNotificationDeliverySent :exec
UPDATE account_notification_deliveries
SET status = 'sent',
    provider_message_id = $2,
    error_message = NULL,
    sent_at = NOW(),
    locked_at = NULL,
    locked_by = NULL
WHERE id = $1
`

type MarkAccountNotificationDeliverySentParams struct {
	ID                int64
	ProviderMessageID pgtype.Text
}

func (q *Queries) MarkAccountNotificationDeliverySent(ctx context.Context, arg MarkAccountNotificationDeliverySentParams) error {
	_, err := q.db.Exec(ctx, markAccountNotificationDeliverySent, arg.ID, arg.ProviderMessageID)
	return err
}

const scheduleAccountNotificationDeliveryRetry = `-- name: ScheduleAccountNotificationDeliveryRetry :execrows
UPDATE account_notification_deliveries
SET error_message = $1,
    next_attempt_at = $2,
    locked_at = NULL,
    locked_by = NULL
WHERE id = $3
  AND account_id = $4
  AND telegram_chat_id = $5
  AND binding_revision = $6
  AND status = 'pending'
`

type ScheduleAccountNotificationDeliveryRetryParams struct {
	ErrorMessage    pgtype.Text
	NextAttemptAt   pgtype.Timestamptz
	ID              int64
	AccountID       pgtype.UUID
	TelegramChatID  int64
	BindingRevision int64
}

func (q *Queries) ScheduleAccountNotificationDeliveryRetry(ctx context.Context, arg ScheduleAccountNotificationDeliveryRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleAccountNotificationDeliveryRetry,
		arg.ErrorMessage,
		arg.NextAttemptAt,
		arg.ID,
		arg.AccountID,
		arg.TelegramChatID,
		arg.BindingRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
