// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sender.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSenderInstance = `-- name: GetSenderInstance :one
SELECT incarnation, hostname, process_id, process_identity, registered_at, stopped_at, stop_confirmation FROM notification_sender_instances WHERE incarnation=$1
`

func (q *Queries) GetSenderInstance(ctx context.Context, incarnation pgtype.UUID) (NotificationSenderInstance, error) {
	row := q.db.QueryRow(ctx, getSenderInstance, incarnation)
	var i NotificationSenderInstance
	err := row.Scan(
		&i.Incarnation,
		&i.Hostname,
		&i.ProcessID,
		&i.ProcessIdentity,
		&i.RegisteredAt,
		&i.StoppedAt,
		&i.StopConfirmation,
	)
	return i, err
}

const hasSenderHistory = `-- name: HasSenderHistory :one
SELECT EXISTS(SELECT 1 FROM notification_sender_instances) OR EXISTS(SELECT 1 FROM notification_delivery_attempts) AS has_history
`

func (q *Queries) HasSenderHistory(ctx context.Context) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, hasSenderHistory)
	var has_history pgtype.Bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listBudgetEvidence = `-- name: ListBudgetEvidence :many
SELECT a.id, a.work_kind, a.work_id, a.owner_id, a.sender_incarnation, a.telegram_chat_id, a.telegram_group, a.payload_digest, a.authorized_at, a.started_at, a.result_at, a.sender_returned_at, a.sender_elapsed_ns, a.message_id, a.outcome, a.outcome_code, a.retry_after, a.retry_after_released_at FROM notification_delivery_attempts a
WHERE started_at >= $1 OR result_at >= $1 OR result_at + retry_after >= $1 OR result_at IS NULL
ORDER BY COALESCE(started_at,result_at,authorized_at)
`

func (q *Queries) ListBudgetEvidence(ctx context.Context, startedAt pgtype.Timestamptz) ([]NotificationDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listBudgetEvidence, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDeliveryAttempt
	for rows.Next() {
		var i NotificationDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkKind,
			&i.WorkID,
			&i.OwnerID,
			&i.SenderIncarnation,
			&i.TelegramChatID,
			&i.TelegramGroup,
			&i.PayloadDigest,
			&i.AuthorizedAt,
			&i.StartedAt,
			&i.ResultAt,
			&i.SenderReturnedAt,
			&i.SenderElapsedNs,
			&i.MessageID,
			&i.Outcome,
			&i.OutcomeCode,
			&i.RetryAfter,
			&i.RetryAfterReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSenderRecoveryAttempts = `-- name: ListSenderRecoveryAttempts :many
SELECT a.id, a.work_kind, a.work_id, a.owner_id, a.sender_incarnation, a.telegram_chat_id, a.telegram_group, a.payload_digest, a.authorized_at, a.started_at, a.result_at, a.sender_returned_at, a.sender_elapsed_ns, a.message_id, a.outcome, a.outcome_code, a.retry_after, a.retry_after_released_at FROM notification_delivery_attempts a WHERE sender_incarnation=$1 AND (
 EXISTS (SELECT 1 FROM account_notification_deliveries d WHERE a.work_kind='account' AND d.id=a.work_id AND d.current_attempt_id=a.id AND d.status='sending') OR
 EXISTS (SELECT 1 FROM system_notification_deliveries d WHERE a.work_kind='system' AND d.id=a.work_id AND d.current_attempt_id=a.id AND d.status='sending') OR
 EXISTS (SELECT 1 FROM telegram_binding_replies d WHERE a.work_kind='reply' AND d.id=a.work_id AND d.current_attempt_id=a.id AND d.status='sending'))
ORDER BY a.authorized_at
`

func (q *Queries) ListSenderRecoveryAttempts(ctx context.Context, senderIncarnation pgtype.UUID) ([]NotificationDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listSenderRecoveryAttempts, senderIncarnation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDeliveryAttempt
	for rows.Next() {
		var i NotificationDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkKind,
			&i.WorkID,
			&i.OwnerID,
			&i.SenderIncarnation,
			&i.TelegramChatID,
			&i.TelegramGroup,
			&i.PayloadDigest,
			&i.AuthorizedAt,
			&i.StartedAt,
			&i.ResultAt,
			&i.SenderReturnedAt,
			&i.SenderElapsedNs,
			&i.MessageID,
			&i.Outcome,
			&i.OutcomeCode,
			&i.RetryAfter,
			&i.RetryAfterReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreleasedRetryAfters = `-- name: ListUnreleasedRetryAfters :many
SELECT id, retry_after FROM notification_delivery_attempts
WHERE retry_after > interval '0 seconds' AND retry_after_released_at IS NULL
`

type ListUnreleasedRetryAftersRow struct {
	ID         pgtype.UUID
	RetryAfter pgtype.Interval
}

func (q *Queries) ListUnreleasedRetryAfters(ctx context.Context) ([]ListUnreleasedRetryAftersRow, error) {
	rows, err := q.db.Query(ctx, listUnreleasedRetryAfters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreleasedRetryAftersRow
	for rows.Next() {
		var i ListUnreleasedRetryAftersRow
		if err := rows.Scan(&i.ID, &i.RetryAfter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnstoppedSenders = `-- name: ListUnstoppedSenders :many
SELECT incarnation, hostname, process_id, process_identity, registered_at, stopped_at, stop_confirmation FROM notification_sender_instances WHERE stopped_at IS NULL ORDER BY registered_at
`

func (q *Queries) ListUnstoppedSenders(ctx context.Context) ([]NotificationSenderInstance, error) {
	rows, err := q.db.Query(ctx, listUnstoppedSenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSenderInstance
	for rows.Next() {
		var i NotificationSenderInstance
		if err := rows.Scan(
			&i.Incarnation,
			&i.Hostname,
			&i.ProcessID,
			&i.ProcessIdentity,
			&i.RegisteredAt,
			&i.StoppedAt,
			&i.StopConfirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerSender = `-- name: RegisterSender :exec
INSERT INTO notification_sender_instances(incarnation,hostname,process_id,process_identity) VALUES ($1,$2,$3,$4)
`

type RegisterSenderParams struct {
	Incarnation     pgtype.UUID
	Hostname        string
	ProcessID       int32
	ProcessIdentity string
}

func (q *Queries) RegisterSender(ctx context.Context, arg RegisterSenderParams) error {
	_, err := q.db.Exec(ctx, registerSender,
		arg.Incarnation,
		arg.Hostname,
		arg.ProcessID,
		arg.ProcessIdentity,
	)
	return err
}

const releaseRetryAfter = `-- name: ReleaseRetryAfter :execrows
UPDATE notification_delivery_attempts SET retry_after_released_at=clock_timestamp()
WHERE id=$1 AND retry_after > interval '0 seconds' AND retry_after_released_at IS NULL
`

func (q *Queries) ReleaseRetryAfter(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseRetryAfter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopSenderInstance = `-- name: StopSenderInstance :execrows
UPDATE notification_sender_instances SET stopped_at=clock_timestamp(),stop_confirmation=$2
WHERE incarnation=$1 AND stopped_at IS NULL
`

type StopSenderInstanceParams struct {
	Incarnation      pgtype.UUID
	StopConfirmation pgtype.Text
}

func (q *Queries) StopSenderInstance(ctx context.Context, arg StopSenderInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopSenderInstance, arg.Incarnation, arg.StopConfirmation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
