apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-server
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: athena-server
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: athena-server
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: athena-server
        env:
        - name: ATHENA_API_SERVER_REPLICAS
          value: '2'
        args:
        - /usr/local/bin/athena-server
