// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_initial_recipient.sql

package sqlc

import (
	"context"
)

const deleteProjectInitialRecipient = `-- name: DeleteProjectInitialRecipient :execrows
DELETE FROM project_initial_recipient
WHERE project_id = $1
  AND wallet = $2
`

type DeleteProjectInitialRecipientParams struct {
	ProjectID int64
	Wallet    []byte
}

func (q *Queries) DeleteProjectInitialRecipient(ctx context.Context, arg DeleteProjectInitialRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectInitialRecipient, arg.ProjectID, arg.Wallet)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectInitialRecipientsByProject = `-- name: DeleteProjectInitialRecipientsByProject :execrows
DELETE FROM project_initial_recipient
WHERE project_id = $1
`

func (q *Queries) DeleteProjectInitialRecipientsByProject(ctx context.Context, projectID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectInitialRecipientsByProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectInitialRecipient = `-- name: GetProjectInitialRecipient :one
SELECT id, project_id, wallet, ratio_bps, rank_index, source_tx_hash, source_block_number, created_at
FROM project_initial_recipient
WHERE project_id = $1
  AND wallet = $2
`

type GetProjectInitialRecipientParams struct {
	ProjectID int64
	Wallet    []byte
}

func (q *Queries) GetProjectInitialRecipient(ctx context.Context, arg GetProjectInitialRecipientParams) (ProjectInitialRecipient, error) {
	row := q.db.QueryRow(ctx, getProjectInitialRecipient, arg.ProjectID, arg.Wallet)
	var i ProjectInitialRecipient
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Wallet,
		&i.RatioBps,
		&i.RankIndex,
		&i.SourceTxHash,
		&i.SourceBlockNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectInitialRecipientsByProject = `-- name: ListProjectInitialRecipientsByProject :many
SELECT id, project_id, wallet, ratio_bps, rank_index, source_tx_hash, source_block_number, created_at
FROM project_initial_recipient
WHERE project_id = $1
ORDER BY rank_index, wallet
`

func (q *Queries) ListProjectInitialRecipientsByProject(ctx context.Context, projectID int64) ([]ProjectInitialRecipient, error) {
	rows, err := q.db.Query(ctx, listProjectInitialRecipientsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectInitialRecipient
	for rows.Next() {
		var i ProjectInitialRecipient
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Wallet,
			&i.RatioBps,
			&i.RankIndex,
			&i.SourceTxHash,
			&i.SourceBlockNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectInitialRecipientsByWallet = `-- name: ListProjectInitialRecipientsByWallet :many
SELECT id, project_id, wallet, ratio_bps, rank_index, source_tx_hash, source_block_number, created_at
FROM project_initial_recipient
WHERE wallet = $1
ORDER BY ratio_bps DESC, project_id
`

func (q *Queries) ListProjectInitialRecipientsByWallet(ctx context.Context, wallet []byte) ([]ProjectInitialRecipient, error) {
	rows, err := q.db.Query(ctx, listProjectInitialRecipientsByWallet, wallet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectInitialRecipient
	for rows.Next() {
		var i ProjectInitialRecipient
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Wallet,
			&i.RatioBps,
			&i.RankIndex,
			&i.SourceTxHash,
			&i.SourceBlockNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectInitialRecipient = `-- name: UpsertProjectInitialRecipient :one
INSERT INTO project_initial_recipient (
  project_id,
  wallet,
  ratio_bps,
  rank_index,
  source_tx_hash,
  source_block_number
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (project_id, wallet) DO UPDATE
SET ratio_bps = EXCLUDED.ratio_bps,
  rank_index = EXCLUDED.rank_index,
  source_tx_hash = EXCLUDED.source_tx_hash,
  source_block_number = EXCLUDED.source_block_number
RETURNING id, project_id, wallet, ratio_bps, rank_index, source_tx_hash, source_block_number, created_at
`

type UpsertProjectInitialRecipientParams struct {
	ProjectID         int64
	Wallet            []byte
	RatioBps          int64
	RankIndex         int32
	SourceTxHash      []byte
	SourceBlockNumber int64
}

// Discovery validation persistence.
func (q *Queries) UpsertProjectInitialRecipient(ctx context.Context, arg UpsertProjectInitialRecipientParams) (ProjectInitialRecipient, error) {
	row := q.db.QueryRow(ctx, upsertProjectInitialRecipient,
		arg.ProjectID,
		arg.Wallet,
		arg.RatioBps,
		arg.RankIndex,
		arg.SourceTxHash,
		arg.SourceBlockNumber,
	)
	var i ProjectInitialRecipient
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Wallet,
		&i.RatioBps,
		&i.RankIndex,
		&i.SourceTxHash,
		&i.SourceBlockNumber,
		&i.CreatedAt,
	)
	return i, err
}
