// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_data_collection_task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProjectDataCollectionTasks = `-- name: ClaimProjectDataCollectionTasks :many
WITH claimable AS (
  SELECT task.id
  FROM project_data_collection_task AS task
  JOIN project AS project ON project.id = task.project_id
  JOIN project_research_state AS research ON research.project_id = task.project_id
  JOIN project_data_collection_schedule AS schedule
    ON schedule.project_id = task.project_id
    AND schedule.data_type = task.data_type
  WHERE task.data_type = $2
    AND project.chain_id = ANY($3::bigint[])
    AND research.status IN ('researching', 'selected')
    AND schedule.status = 'active'
    AND (
      (task.status = 'pending' AND task.available_at <= now())
      OR (task.status = 'running' AND task.lease_expires_at <= now())
    )
  ORDER BY task.available_at, task.id
  FOR UPDATE OF task SKIP LOCKED
  LIMIT $4
)
UPDATE project_data_collection_task AS task
SET status = 'running',
  locked_at = now(),
  lease_expires_at = now() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
FROM claimable
WHERE task.id = claimable.id
RETURNING task.id, task.project_id, task.data_type, task.revision, task.status, task.attempts, task.available_at, task.locked_at, task.lease_expires_at, task.last_error, task.created_at, task.updated_at
`

type ClaimProjectDataCollectionTasksParams struct {
	LeaseSeconds int64
	DataType     string
	ChainIds     []int64
	Limit        int32
}

func (q *Queries) ClaimProjectDataCollectionTasks(ctx context.Context, arg ClaimProjectDataCollectionTasksParams) ([]ProjectDataCollectionTask, error) {
	rows, err := q.db.Query(ctx, claimProjectDataCollectionTasks,
		arg.LeaseSeconds,
		arg.DataType,
		arg.ChainIds,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDataCollectionTask
	for rows.Next() {
		var i ProjectDataCollectionTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DataType,
			&i.Revision,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProjectDataCollectionTasks = `-- name: CountProjectDataCollectionTasks :one
SELECT COUNT(*)::bigint
FROM project_data_collection_task
WHERE ($1::bigint = 0 OR project_id = $1::bigint)
  AND ($2::text = '' OR data_type = $2::text)
  AND ($3::text = '' OR status = $3::text)
`

type CountProjectDataCollectionTasksParams struct {
	ProjectID int64
	DataType  string
	Status    string
}

func (q *Queries) CountProjectDataCollectionTasks(ctx context.Context, arg CountProjectDataCollectionTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectDataCollectionTasks, arg.ProjectID, arg.DataType, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProjectDataCollectionTask = `-- name: CreateProjectDataCollectionTask :one
INSERT INTO project_data_collection_task (
  project_id,
  data_type,
  revision
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (project_id, data_type, revision) DO UPDATE
SET updated_at = project_data_collection_task.updated_at
RETURNING id, project_id, data_type, revision, status, attempts, available_at, locked_at, lease_expires_at, last_error, created_at, updated_at
`

type CreateProjectDataCollectionTaskParams struct {
	ProjectID int64
	DataType  string
	Revision  int64
}

// Research collection persistence.
func (q *Queries) CreateProjectDataCollectionTask(ctx context.Context, arg CreateProjectDataCollectionTaskParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, createProjectDataCollectionTask, arg.ProjectID, arg.DataType, arg.Revision)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Revision,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failProjectDataCollectionTask = `-- name: FailProjectDataCollectionTask :execrows
UPDATE project_data_collection_task
SET status = 'failed',
  attempts = LEAST(attempts + 1, 10),
  locked_at = NULL,
  lease_expires_at = NULL,
  last_error = $1,
  updated_at = now()
WHERE id = $2
  AND status = 'running'
`

type FailProjectDataCollectionTaskParams struct {
	LastError pgtype.Text
	ID        int64
}

func (q *Queries) FailProjectDataCollectionTask(ctx context.Context, arg FailProjectDataCollectionTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, failProjectDataCollectionTask, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectDataCollectionTask = `-- name: GetProjectDataCollectionTask :one
SELECT id, project_id, data_type, revision, status, attempts, available_at, locked_at, lease_expires_at, last_error, created_at, updated_at
FROM project_data_collection_task
WHERE id = $1
`

func (q *Queries) GetProjectDataCollectionTask(ctx context.Context, id int64) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, getProjectDataCollectionTask, id)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Revision,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForDataCollectionTask = `-- name: GetProjectForDataCollectionTask :one
SELECT project.id, project.chain_id, project.contract, project.tx_sender, project.tx_hash, project.tx_index, project.deployment_nonce, project.block_number, project.block_time, project.code_hash, project.name, project.symbol, project.decimals, project.total_supply, project.weth_pair, project.usdt_pair, project.created_at
FROM project_data_collection_task AS task
JOIN project ON project.id = task.project_id
WHERE task.id = $1
`

func (q *Queries) GetProjectForDataCollectionTask(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForDataCollectionTask, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Contract,
		&i.TxSender,
		&i.TxHash,
		&i.TxIndex,
		&i.DeploymentNonce,
		&i.BlockNumber,
		&i.BlockTime,
		&i.CodeHash,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.TotalSupply,
		&i.WethPair,
		&i.UsdtPair,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectDataCollectionTasks = `-- name: ListProjectDataCollectionTasks :many
SELECT id, project_id, data_type, revision, status, attempts, available_at, locked_at, lease_expires_at, last_error, created_at, updated_at
FROM project_data_collection_task
WHERE ($1::bigint = 0 OR project_id = $1::bigint)
  AND ($2::text = '' OR data_type = $2::text)
  AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListProjectDataCollectionTasksParams struct {
	ProjectID int64
	DataType  string
	Status    string
	Offset    int32
	Limit     int32
}

func (q *Queries) ListProjectDataCollectionTasks(ctx context.Context, arg ListProjectDataCollectionTasksParams) ([]ProjectDataCollectionTask, error) {
	rows, err := q.db.Query(ctx, listProjectDataCollectionTasks,
		arg.ProjectID,
		arg.DataType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDataCollectionTask
	for rows.Next() {
		var i ProjectDataCollectionTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DataType,
			&i.Revision,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectDataCollectionTaskSucceeded = `-- name: MarkProjectDataCollectionTaskSucceeded :execrows
UPDATE project_data_collection_task
SET status = 'succeeded',
  locked_at = NULL,
  lease_expires_at = NULL,
  last_error = NULL,
  updated_at = now()
WHERE id = $1
  AND status = 'running'
`

func (q *Queries) MarkProjectDataCollectionTaskSucceeded(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markProjectDataCollectionTaskSucceeded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewProjectDataCollectionTaskLease = `-- name: RenewProjectDataCollectionTaskLease :execrows
UPDATE project_data_collection_task
SET lease_expires_at = now() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
WHERE id = $2
  AND status = 'running'
`

type RenewProjectDataCollectionTaskLeaseParams struct {
	LeaseSeconds int64
	ID           int64
}

func (q *Queries) RenewProjectDataCollectionTaskLease(ctx context.Context, arg RenewProjectDataCollectionTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewProjectDataCollectionTaskLease, arg.LeaseSeconds, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryProjectDataCollectionTask = `-- name: RetryProjectDataCollectionTask :one
UPDATE project_data_collection_task
SET status = 'pending',
  attempts = attempts + 1,
  available_at = $1,
  locked_at = NULL,
  lease_expires_at = NULL,
  last_error = $2,
  updated_at = now()
WHERE id = $3
  AND status = 'running'
  AND attempts < 9
RETURNING id, project_id, data_type, revision, status, attempts, available_at, locked_at, lease_expires_at, last_error, created_at, updated_at
`

type RetryProjectDataCollectionTaskParams struct {
	AvailableAt pgtype.Timestamptz
	LastError   pgtype.Text
	ID          int64
}

func (q *Queries) RetryProjectDataCollectionTask(ctx context.Context, arg RetryProjectDataCollectionTaskParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, retryProjectDataCollectionTask, arg.AvailableAt, arg.LastError, arg.ID)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Revision,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
