// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_data_collection_task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProjectDataCollectionTask = `-- name: ClaimProjectDataCollectionTask :one
WITH claimable AS (
  SELECT task.id
  FROM project_data_collection_task AS task
  JOIN project ON project.id = task.project_id
  WHERE task.data_type = $2
    AND project.chain_id = ANY($3::bigint[])
    AND (
      (task.status = 'pending' AND task.available_at <= clock_timestamp())
      OR (task.status = 'running' AND task.lease_expires_at <= clock_timestamp())
    )
  ORDER BY
    CASE WHEN task.status = 'running' THEN 0 ELSE 1 END,
    COALESCE(task.lease_expires_at, task.available_at),
    task.id
  FOR UPDATE OF task SKIP LOCKED
  LIMIT 1
)
UPDATE project_data_collection_task AS task
SET status = 'running',
  claim_generation = task.claim_generation + 1,
  locked_at = clock_timestamp(),
  lease_expires_at = clock_timestamp() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
FROM claimable
WHERE task.id = claimable.id
RETURNING task.id, task.project_id, task.data_type, task.status, task.failure_count, task.available_at, task.claim_generation, task.locked_at, task.lease_expires_at, task.last_error, task.finished_at, task.created_at, task.updated_at
`

type ClaimProjectDataCollectionTaskParams struct {
	LeaseSeconds int64
	DataType     string
	ChainIds     []int64
}

func (q *Queries) ClaimProjectDataCollectionTask(ctx context.Context, arg ClaimProjectDataCollectionTaskParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, claimProjectDataCollectionTask, arg.LeaseSeconds, arg.DataType, arg.ChainIds)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProjectDataCollectionTaskTypes = `-- name: CountProjectDataCollectionTaskTypes :one
SELECT COUNT(DISTINCT data_type)::bigint
FROM project_data_collection_task
WHERE project_id = $1
`

func (q *Queries) CountProjectDataCollectionTaskTypes(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectDataCollectionTaskTypes, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProjectDataCollectionTasks = `-- name: CountProjectDataCollectionTasks :one
SELECT COUNT(*)::bigint
FROM project_data_collection_task AS task
JOIN project ON project.id = task.project_id
WHERE ($1::bigint = 0 OR project.chain_id = $1::bigint)
  AND ($2::bigint = 0 OR task.project_id = $2::bigint)
  AND ($3::text = '' OR task.data_type = $3::text)
  AND ($4::text = '' OR task.status = $4::text)
`

type CountProjectDataCollectionTasksParams struct {
	ChainID   int64
	ProjectID int64
	DataType  string
	Status    string
}

func (q *Queries) CountProjectDataCollectionTasks(ctx context.Context, arg CountProjectDataCollectionTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectDataCollectionTasks,
		arg.ChainID,
		arg.ProjectID,
		arg.DataType,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProjectDataCollectionTasks = `-- name: CreateProjectDataCollectionTasks :many

WITH required_data_types(data_type, ordinal) AS (
  SELECT data_type, ordinal
  FROM unnest(ARRAY[
    'chain_state',
    'wallet_asset_state',
    'simulation_result',
    'ave',
    'contract_code_source',
    'wallet_normal_transactions'
  ]::text[]) WITH ORDINALITY AS value(data_type, ordinal)
)
INSERT INTO project_data_collection_task (
  project_id,
  data_type
)
SELECT
  $1,
  required_data_types.data_type
FROM required_data_types
ORDER BY required_data_types.ordinal
ON CONFLICT (project_id, data_type) DO NOTHING
RETURNING id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

// One-time project data-collection task persistence.
func (q *Queries) CreateProjectDataCollectionTasks(ctx context.Context, projectID int64) ([]ProjectDataCollectionTask, error) {
	rows, err := q.db.Query(ctx, createProjectDataCollectionTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDataCollectionTask
	for rows.Next() {
		var i ProjectDataCollectionTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DataType,
			&i.Status,
			&i.FailureCount,
			&i.AvailableAt,
			&i.ClaimGeneration,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failProjectDataCollectionTask = `-- name: FailProjectDataCollectionTask :one
UPDATE project_data_collection_task
SET status = 'failed',
  failure_count = failure_count + 1,
  lease_expires_at = NULL,
  last_error = $1,
  finished_at = $2,
  updated_at = now()
WHERE id = $3
  AND status = 'running'
  AND claim_generation = $4
  AND lease_expires_at > clock_timestamp()
  AND failure_count = 2
RETURNING id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type FailProjectDataCollectionTaskParams struct {
	LastError       pgtype.Text
	FinishedAt      pgtype.Timestamptz
	ID              int64
	ClaimGeneration int64
}

func (q *Queries) FailProjectDataCollectionTask(ctx context.Context, arg FailProjectDataCollectionTaskParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, failProjectDataCollectionTask,
		arg.LastError,
		arg.FinishedAt,
		arg.ID,
		arg.ClaimGeneration,
	)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectCollectionBarrierState = `-- name: GetProjectCollectionBarrierState :one
SELECT
  COUNT(*)::bigint AS task_count,
  COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed'))::bigint AS terminal_count,
  COUNT(*) FILTER (WHERE status = 'succeeded')::bigint AS succeeded_count,
  COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed_count
FROM project_data_collection_task
WHERE project_id = $1
`

type GetProjectCollectionBarrierStateRow struct {
	TaskCount      int64
	TerminalCount  int64
	SucceededCount int64
	FailedCount    int64
}

func (q *Queries) GetProjectCollectionBarrierState(ctx context.Context, projectID int64) (GetProjectCollectionBarrierStateRow, error) {
	row := q.db.QueryRow(ctx, getProjectCollectionBarrierState, projectID)
	var i GetProjectCollectionBarrierStateRow
	err := row.Scan(
		&i.TaskCount,
		&i.TerminalCount,
		&i.SucceededCount,
		&i.FailedCount,
	)
	return i, err
}

const getProjectDataCollectionTask = `-- name: GetProjectDataCollectionTask :one
SELECT id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
FROM project_data_collection_task
WHERE id = $1
`

func (q *Queries) GetProjectDataCollectionTask(ctx context.Context, id int64) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, getProjectDataCollectionTask, id)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForDataCollectionTask = `-- name: GetProjectForDataCollectionTask :one
SELECT project.id, project.chain_id, project.contract, project.tx_sender, project.tx_hash, project.tx_index, project.deployment_nonce, project.block_number, project.block_time, project.code_hash, project.name, project.symbol, project.decimals, project.total_supply, project.weth_pair, project.usdt_pair, project.created_at
FROM project_data_collection_task AS task
JOIN project ON project.id = task.project_id
WHERE task.id = $1
`

func (q *Queries) GetProjectForDataCollectionTask(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForDataCollectionTask, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Contract,
		&i.TxSender,
		&i.TxHash,
		&i.TxIndex,
		&i.DeploymentNonce,
		&i.BlockNumber,
		&i.BlockTime,
		&i.CodeHash,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.TotalSupply,
		&i.WethPair,
		&i.UsdtPair,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectDataCollectionTasks = `-- name: ListProjectDataCollectionTasks :many
SELECT task.id, task.project_id, task.data_type, task.status, task.failure_count, task.available_at, task.claim_generation, task.locked_at, task.lease_expires_at, task.last_error, task.finished_at, task.created_at, task.updated_at
FROM project_data_collection_task AS task
JOIN project ON project.id = task.project_id
WHERE ($1::bigint = 0 OR project.chain_id = $1::bigint)
  AND ($2::bigint = 0 OR task.project_id = $2::bigint)
  AND ($3::text = '' OR task.data_type = $3::text)
  AND ($4::text = '' OR task.status = $4::text)
ORDER BY task.created_at DESC, task.id DESC
LIMIT $6 OFFSET $5
`

type ListProjectDataCollectionTasksParams struct {
	ChainID   int64
	ProjectID int64
	DataType  string
	Status    string
	Offset    int32
	Limit     int32
}

func (q *Queries) ListProjectDataCollectionTasks(ctx context.Context, arg ListProjectDataCollectionTasksParams) ([]ProjectDataCollectionTask, error) {
	rows, err := q.db.Query(ctx, listProjectDataCollectionTasks,
		arg.ChainID,
		arg.ProjectID,
		arg.DataType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDataCollectionTask
	for rows.Next() {
		var i ProjectDataCollectionTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DataType,
			&i.Status,
			&i.FailureCount,
			&i.AvailableAt,
			&i.ClaimGeneration,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDataCollectionTasksByProject = `-- name: ListProjectDataCollectionTasksByProject :many
SELECT id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
FROM project_data_collection_task
WHERE project_id = $1
ORDER BY CASE data_type
  WHEN 'chain_state' THEN 1
  WHEN 'wallet_asset_state' THEN 2
  WHEN 'simulation_result' THEN 3
  WHEN 'ave' THEN 4
  WHEN 'contract_code_source' THEN 5
  WHEN 'wallet_normal_transactions' THEN 6
  ELSE 7
END
`

func (q *Queries) ListProjectDataCollectionTasksByProject(ctx context.Context, projectID int64) ([]ProjectDataCollectionTask, error) {
	rows, err := q.db.Query(ctx, listProjectDataCollectionTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectDataCollectionTask
	for rows.Next() {
		var i ProjectDataCollectionTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DataType,
			&i.Status,
			&i.FailureCount,
			&i.AvailableAt,
			&i.ClaimGeneration,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectDataCollectionTaskForCompletion = `-- name: LockProjectDataCollectionTaskForCompletion :one
SELECT id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
FROM project_data_collection_task
WHERE id = $1
  AND project_id = $2
  AND claim_generation = $3
  AND (
    (status = 'running' AND lease_expires_at > clock_timestamp())
    OR status = 'succeeded'
  )
FOR UPDATE
`

type LockProjectDataCollectionTaskForCompletionParams struct {
	ID              int64
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) LockProjectDataCollectionTaskForCompletion(ctx context.Context, arg LockProjectDataCollectionTaskForCompletionParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, lockProjectDataCollectionTaskForCompletion, arg.ID, arg.ProjectID, arg.ClaimGeneration)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockProjectForCollectionCompletion = `-- name: LockProjectForCollectionCompletion :one
SELECT id
FROM project
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockProjectForCollectionCompletion(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockProjectForCollectionCompletion, projectID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markProjectDataCollectionTaskSucceeded = `-- name: MarkProjectDataCollectionTaskSucceeded :one
UPDATE project_data_collection_task
SET status = 'succeeded',
  lease_expires_at = NULL,
  last_error = NULL,
  finished_at = $1,
  updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND claim_generation = $3
  AND lease_expires_at > clock_timestamp()
RETURNING id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type MarkProjectDataCollectionTaskSucceededParams struct {
	FinishedAt      pgtype.Timestamptz
	ID              int64
	ClaimGeneration int64
}

func (q *Queries) MarkProjectDataCollectionTaskSucceeded(ctx context.Context, arg MarkProjectDataCollectionTaskSucceededParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, markProjectDataCollectionTaskSucceeded, arg.FinishedAt, arg.ID, arg.ClaimGeneration)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewProjectDataCollectionTaskLease = `-- name: RenewProjectDataCollectionTaskLease :execrows
UPDATE project_data_collection_task
SET lease_expires_at = clock_timestamp() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND claim_generation = $3
  AND lease_expires_at > clock_timestamp()
`

type RenewProjectDataCollectionTaskLeaseParams struct {
	LeaseSeconds    int64
	ID              int64
	ClaimGeneration int64
}

func (q *Queries) RenewProjectDataCollectionTaskLease(ctx context.Context, arg RenewProjectDataCollectionTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewProjectDataCollectionTaskLease, arg.LeaseSeconds, arg.ID, arg.ClaimGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryProjectDataCollectionTask = `-- name: RetryProjectDataCollectionTask :one
UPDATE project_data_collection_task
SET status = 'pending',
  failure_count = failure_count + 1,
  available_at = $1,
  locked_at = NULL,
  lease_expires_at = NULL,
  last_error = $2,
  updated_at = now()
WHERE id = $3
  AND status = 'running'
  AND claim_generation = $4
  AND lease_expires_at > clock_timestamp()
  AND failure_count < 2
RETURNING id, project_id, data_type, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type RetryProjectDataCollectionTaskParams struct {
	AvailableAt     pgtype.Timestamptz
	LastError       pgtype.Text
	ID              int64
	ClaimGeneration int64
}

func (q *Queries) RetryProjectDataCollectionTask(ctx context.Context, arg RetryProjectDataCollectionTaskParams) (ProjectDataCollectionTask, error) {
	row := q.db.QueryRow(ctx, retryProjectDataCollectionTask,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
		arg.ClaimGeneration,
	)
	var i ProjectDataCollectionTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DataType,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
