// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_profile_build_task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProjectProfileBuildTask = `-- name: ClaimProjectProfileBuildTask :one
WITH claimable AS (
  SELECT project_id
  FROM project_profile_build_task
  WHERE (status = 'pending' AND available_at <= clock_timestamp())
    OR (status = 'running' AND lease_expires_at <= clock_timestamp())
  ORDER BY
    CASE WHEN status = 'running' THEN 0 ELSE 1 END,
    COALESCE(lease_expires_at, available_at),
    project_id
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE project_profile_build_task AS task
SET status = 'running',
  claim_generation = task.claim_generation + 1,
  locked_at = clock_timestamp(),
  lease_expires_at = clock_timestamp() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
FROM claimable
WHERE task.project_id = claimable.project_id
RETURNING task.project_id, task.status, task.failure_count, task.available_at, task.claim_generation, task.locked_at, task.lease_expires_at, task.last_error, task.finished_at, task.created_at, task.updated_at
`

func (q *Queries) ClaimProjectProfileBuildTask(ctx context.Context, leaseSeconds int64) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, claimProjectProfileBuildTask, leaseSeconds)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueProjectProfileBuildTask = `-- name: EnqueueProjectProfileBuildTask :exec

INSERT INTO project_profile_build_task (project_id)
SELECT task.project_id
FROM project_data_collection_task AS task
WHERE task.project_id = $1
GROUP BY task.project_id
HAVING COUNT(*) = 6
  AND COUNT(*) FILTER (WHERE task.status IN ('succeeded', 'failed')) = 6
ON CONFLICT (project_id) DO NOTHING
`

// Unique project-profile build task persistence.
func (q *Queries) EnqueueProjectProfileBuildTask(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, enqueueProjectProfileBuildTask, projectID)
	return err
}

const failProjectProfileBuildTask = `-- name: FailProjectProfileBuildTask :one
UPDATE project_profile_build_task
SET status = 'failed',
  failure_count = failure_count + 1,
  lease_expires_at = NULL,
  last_error = $1,
  finished_at = $2,
  updated_at = now()
WHERE project_id = $3
  AND status = 'running'
  AND claim_generation = $4
  AND lease_expires_at > clock_timestamp()
  AND failure_count = 2
RETURNING project_id, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type FailProjectProfileBuildTaskParams struct {
	LastError       pgtype.Text
	FinishedAt      pgtype.Timestamptz
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) FailProjectProfileBuildTask(ctx context.Context, arg FailProjectProfileBuildTaskParams) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, failProjectProfileBuildTask,
		arg.LastError,
		arg.FinishedAt,
		arg.ProjectID,
		arg.ClaimGeneration,
	)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectProfileBuildTask = `-- name: GetProjectProfileBuildTask :one
SELECT project_id, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
FROM project_profile_build_task
WHERE project_id = $1
`

func (q *Queries) GetProjectProfileBuildTask(ctx context.Context, projectID int64) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, getProjectProfileBuildTask, projectID)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockProjectProfileBuildTaskForCompletion = `-- name: LockProjectProfileBuildTaskForCompletion :one
SELECT project_id, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
FROM project_profile_build_task
WHERE project_id = $1
  AND claim_generation = $2
  AND (
    (status = 'running' AND lease_expires_at > clock_timestamp())
    OR status = 'succeeded'
  )
FOR UPDATE
`

type LockProjectProfileBuildTaskForCompletionParams struct {
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) LockProjectProfileBuildTaskForCompletion(ctx context.Context, arg LockProjectProfileBuildTaskForCompletionParams) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, lockProjectProfileBuildTaskForCompletion, arg.ProjectID, arg.ClaimGeneration)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProjectProfileBuildTaskSucceeded = `-- name: MarkProjectProfileBuildTaskSucceeded :one
UPDATE project_profile_build_task
SET status = 'succeeded',
  lease_expires_at = NULL,
  last_error = NULL,
  finished_at = $1,
  updated_at = now()
WHERE project_id = $2
  AND status = 'running'
  AND claim_generation = $3
  AND lease_expires_at > clock_timestamp()
RETURNING project_id, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type MarkProjectProfileBuildTaskSucceededParams struct {
	FinishedAt      pgtype.Timestamptz
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) MarkProjectProfileBuildTaskSucceeded(ctx context.Context, arg MarkProjectProfileBuildTaskSucceededParams) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, markProjectProfileBuildTaskSucceeded, arg.FinishedAt, arg.ProjectID, arg.ClaimGeneration)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewProjectProfileBuildTaskLease = `-- name: RenewProjectProfileBuildTaskLease :execrows
UPDATE project_profile_build_task
SET lease_expires_at = clock_timestamp() + ($1::bigint * INTERVAL '1 second'),
  updated_at = now()
WHERE project_id = $2
  AND status = 'running'
  AND claim_generation = $3
  AND lease_expires_at > clock_timestamp()
`

type RenewProjectProfileBuildTaskLeaseParams struct {
	LeaseSeconds    int64
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) RenewProjectProfileBuildTaskLease(ctx context.Context, arg RenewProjectProfileBuildTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewProjectProfileBuildTaskLease, arg.LeaseSeconds, arg.ProjectID, arg.ClaimGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryProjectProfileBuildTask = `-- name: RetryProjectProfileBuildTask :one
UPDATE project_profile_build_task
SET status = 'pending',
  failure_count = failure_count + 1,
  available_at = $1,
  locked_at = NULL,
  lease_expires_at = NULL,
  last_error = $2,
  updated_at = now()
WHERE project_id = $3
  AND status = 'running'
  AND claim_generation = $4
  AND lease_expires_at > clock_timestamp()
  AND failure_count < 2
RETURNING project_id, status, failure_count, available_at, claim_generation, locked_at, lease_expires_at, last_error, finished_at, created_at, updated_at
`

type RetryProjectProfileBuildTaskParams struct {
	AvailableAt     pgtype.Timestamptz
	LastError       pgtype.Text
	ProjectID       int64
	ClaimGeneration int64
}

func (q *Queries) RetryProjectProfileBuildTask(ctx context.Context, arg RetryProjectProfileBuildTaskParams) (ProjectProfileBuildTask, error) {
	row := q.db.QueryRow(ctx, retryProjectProfileBuildTask,
		arg.AvailableAt,
		arg.LastError,
		arg.ProjectID,
		arg.ClaimGeneration,
	)
	var i ProjectProfileBuildTask
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.ClaimGeneration,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
