// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swap_processing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceChainSwapProcessingCheckpoint = `-- name: AdvanceChainSwapProcessingCheckpoint :one
UPDATE chain_swap_processing_checkpoint
SET cursor_block_number = $1,
  updated_at = now()
WHERE chain_id = $2
  AND cursor_block_number = $3
  AND initialized
  AND status = 'running'
RETURNING chain_id, cursor_block_number, status, initialized, created_at, updated_at
`

type AdvanceChainSwapProcessingCheckpointParams struct {
	CursorBlockNumber         int64
	ChainID                   int64
	ExpectedCursorBlockNumber int64
}

func (q *Queries) AdvanceChainSwapProcessingCheckpoint(ctx context.Context, arg AdvanceChainSwapProcessingCheckpointParams) (ChainSwapProcessingCheckpoint, error) {
	row := q.db.QueryRow(ctx, advanceChainSwapProcessingCheckpoint, arg.CursorBlockNumber, arg.ChainID, arg.ExpectedCursorBlockNumber)
	var i ChainSwapProcessingCheckpoint
	err := row.Scan(
		&i.ChainID,
		&i.CursorBlockNumber,
		&i.Status,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeProjectSwapPair = `-- name: CompleteProjectSwapPair :one
UPDATE project_swap_pair
SET swap_block_count = 100,
  first_swap_block_number = COALESCE(first_swap_block_number, $1::bigint),
  first_swap_block_time = COALESCE(first_swap_block_time, $2::bigint),
  last_swap_block_number = $1::bigint,
  last_swap_block_time = $2::bigint,
  status = 'completed',
  next_expiry_block_time = NULL,
  completed_block_number = $1::bigint,
  completed_block_time = $2::bigint,
  updated_at = now()
WHERE id = $3
  AND status = 'collecting'
  AND swap_block_count = 99
RETURNING id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
`

type CompleteProjectSwapPairParams struct {
	BlockNumber       int64
	BlockTime         int64
	ProjectSwapPairID int64
}

func (q *Queries) CompleteProjectSwapPair(ctx context.Context, arg CompleteProjectSwapPairParams) (ProjectSwapPair, error) {
	row := q.db.QueryRow(ctx, completeProjectSwapPair, arg.BlockNumber, arg.BlockTime, arg.ProjectSwapPairID)
	var i ProjectSwapPair
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChainID,
		&i.PairKind,
		&i.PairAddress,
		&i.StartBlockNumber,
		&i.StartBlockTime,
		&i.SwapBlockCount,
		&i.Status,
		&i.FirstSwapBlockNumber,
		&i.FirstSwapBlockTime,
		&i.LastSwapBlockNumber,
		&i.LastSwapBlockTime,
		&i.AbsoluteExpiryBlockTime,
		&i.NextExpiryBlockTime,
		&i.CompletedBlockNumber,
		&i.CompletedBlockTime,
		&i.ExpiredBlockNumber,
		&i.ExpiredBlockTime,
		&i.ExpiredReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectSwapBlock = `-- name: CreateProjectSwapBlock :one
INSERT INTO project_swap_block (
  project_swap_pair_id,
  block_number,
  block_time,
  sample_index
)
SELECT
  project_swap_pair.id,
  $1,
  $2,
  project_swap_pair.swap_block_count + 1
FROM project_swap_pair
WHERE project_swap_pair.id = $3
  AND project_swap_pair.status = 'collecting'
  AND project_swap_pair.swap_block_count < 100
RETURNING id, project_swap_pair_id, block_number, block_time, sample_index, created_at
`

type CreateProjectSwapBlockParams struct {
	BlockNumber       int64
	BlockTime         int64
	ProjectSwapPairID int64
}

func (q *Queries) CreateProjectSwapBlock(ctx context.Context, arg CreateProjectSwapBlockParams) (ProjectSwapBlock, error) {
	row := q.db.QueryRow(ctx, createProjectSwapBlock, arg.BlockNumber, arg.BlockTime, arg.ProjectSwapPairID)
	var i ProjectSwapBlock
	err := row.Scan(
		&i.ID,
		&i.ProjectSwapPairID,
		&i.BlockNumber,
		&i.BlockTime,
		&i.SampleIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectSwapEvent = `-- name: CreateProjectSwapEvent :one
INSERT INTO project_swap_event (
  project_swap_pair_id,
  project_swap_block_id,
  transaction_hash,
  transaction_index,
  log_index,
  tx_from,
  sender,
  to_address,
  amount0_in,
  amount1_in,
  amount0_out,
  amount1_out
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12
)
RETURNING id, project_swap_pair_id, project_swap_block_id, transaction_hash, transaction_index, log_index, tx_from, sender, to_address, amount0_in, amount1_in, amount0_out, amount1_out, created_at
`

type CreateProjectSwapEventParams struct {
	ProjectSwapPairID  int64
	ProjectSwapBlockID int64
	TransactionHash    []byte
	TransactionIndex   int64
	LogIndex           int64
	TxFrom             []byte
	Sender             []byte
	ToAddress          []byte
	Amount0In          pgtype.Numeric
	Amount1In          pgtype.Numeric
	Amount0Out         pgtype.Numeric
	Amount1Out         pgtype.Numeric
}

func (q *Queries) CreateProjectSwapEvent(ctx context.Context, arg CreateProjectSwapEventParams) (ProjectSwapEvent, error) {
	row := q.db.QueryRow(ctx, createProjectSwapEvent,
		arg.ProjectSwapPairID,
		arg.ProjectSwapBlockID,
		arg.TransactionHash,
		arg.TransactionIndex,
		arg.LogIndex,
		arg.TxFrom,
		arg.Sender,
		arg.ToAddress,
		arg.Amount0In,
		arg.Amount1In,
		arg.Amount0Out,
		arg.Amount1Out,
	)
	var i ProjectSwapEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectSwapPairID,
		&i.ProjectSwapBlockID,
		&i.TransactionHash,
		&i.TransactionIndex,
		&i.LogIndex,
		&i.TxFrom,
		&i.Sender,
		&i.ToAddress,
		&i.Amount0In,
		&i.Amount1In,
		&i.Amount0Out,
		&i.Amount1Out,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectSwapPair = `-- name: CreateProjectSwapPair :one
INSERT INTO project_swap_pair (
  project_id,
  chain_id,
  pair_kind,
  pair_address,
  start_block_number,
  start_block_time,
  absolute_expiry_block_time,
  next_expiry_block_time
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8::bigint
)
ON CONFLICT (project_id, pair_kind) DO UPDATE
SET project_id = project_swap_pair.project_id
WHERE project_swap_pair.chain_id = EXCLUDED.chain_id
  AND project_swap_pair.pair_address = EXCLUDED.pair_address
  AND project_swap_pair.start_block_number = EXCLUDED.start_block_number
  AND project_swap_pair.start_block_time = EXCLUDED.start_block_time
RETURNING id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
`

type CreateProjectSwapPairParams struct {
	ProjectID               int64
	ChainID                 int64
	PairKind                string
	PairAddress             []byte
	StartBlockNumber        int64
	StartBlockTime          int64
	AbsoluteExpiryBlockTime int64
	NextExpiryBlockTime     int64
}

func (q *Queries) CreateProjectSwapPair(ctx context.Context, arg CreateProjectSwapPairParams) (ProjectSwapPair, error) {
	row := q.db.QueryRow(ctx, createProjectSwapPair,
		arg.ProjectID,
		arg.ChainID,
		arg.PairKind,
		arg.PairAddress,
		arg.StartBlockNumber,
		arg.StartBlockTime,
		arg.AbsoluteExpiryBlockTime,
		arg.NextExpiryBlockTime,
	)
	var i ProjectSwapPair
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChainID,
		&i.PairKind,
		&i.PairAddress,
		&i.StartBlockNumber,
		&i.StartBlockTime,
		&i.SwapBlockCount,
		&i.Status,
		&i.FirstSwapBlockNumber,
		&i.FirstSwapBlockTime,
		&i.LastSwapBlockNumber,
		&i.LastSwapBlockTime,
		&i.AbsoluteExpiryBlockTime,
		&i.NextExpiryBlockTime,
		&i.CompletedBlockNumber,
		&i.CompletedBlockTime,
		&i.ExpiredBlockNumber,
		&i.ExpiredBlockTime,
		&i.ExpiredReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireProjectSwapPair = `-- name: ExpireProjectSwapPair :execrows
UPDATE project_swap_pair
SET status = 'expired',
  next_expiry_block_time = NULL,
  expired_block_number = $1::bigint,
  expired_block_time = $2::bigint,
  expired_reason = $3::text,
  updated_at = now()
WHERE id = $4
  AND status = 'collecting'
  AND swap_block_count < 100
  AND (
    (
      $3::text = 'max_duration'
      AND absolute_expiry_block_time <= $2::bigint
    )
    OR
    (
      $3::text = 'no_swap'
      AND swap_block_count = 0
      AND absolute_expiry_block_time > $2::bigint
      AND next_expiry_block_time <= $2::bigint
    )
    OR
    (
      $3::text = 'inactive'
      AND swap_block_count > 0
      AND absolute_expiry_block_time > $2::bigint
      AND next_expiry_block_time <= $2::bigint
    )
  )
`

type ExpireProjectSwapPairParams struct {
	ExpiredBlockNumber int64
	ExpiredBlockTime   int64
	ExpiredReason      string
	ProjectSwapPairID  int64
}

func (q *Queries) ExpireProjectSwapPair(ctx context.Context, arg ExpireProjectSwapPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireProjectSwapPair,
		arg.ExpiredBlockNumber,
		arg.ExpiredBlockTime,
		arg.ExpiredReason,
		arg.ProjectSwapPairID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findNextCollectingProjectSwapPairStartBlock = `-- name: FindNextCollectingProjectSwapPairStartBlock :one
SELECT COALESCE(MIN(start_block_number), 0)::bigint AS start_block_number
FROM project_swap_pair
WHERE chain_id = $1
  AND status = 'collecting'
  AND start_block_number <= $2
`

type FindNextCollectingProjectSwapPairStartBlockParams struct {
	ChainID                 int64
	SourceCursorBlockNumber int64
}

func (q *Queries) FindNextCollectingProjectSwapPairStartBlock(ctx context.Context, arg FindNextCollectingProjectSwapPairStartBlockParams) (int64, error) {
	row := q.db.QueryRow(ctx, findNextCollectingProjectSwapPairStartBlock, arg.ChainID, arg.SourceCursorBlockNumber)
	var start_block_number int64
	err := row.Scan(&start_block_number)
	return start_block_number, err
}

const getChainProcessingCursorForSwap = `-- name: GetChainProcessingCursorForSwap :one

SELECT cursor_block_number
FROM chain_processing_checkpoint
WHERE chain_id = $1
`

// Per-project Swap collection persistence.
func (q *Queries) GetChainProcessingCursorForSwap(ctx context.Context, chainID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getChainProcessingCursorForSwap, chainID)
	var cursor_block_number int64
	err := row.Scan(&cursor_block_number)
	return cursor_block_number, err
}

const getChainSwapProcessingCheckpoint = `-- name: GetChainSwapProcessingCheckpoint :one
SELECT chain_id, cursor_block_number, status, initialized, created_at, updated_at
FROM chain_swap_processing_checkpoint
WHERE chain_id = $1
`

func (q *Queries) GetChainSwapProcessingCheckpoint(ctx context.Context, chainID int64) (ChainSwapProcessingCheckpoint, error) {
	row := q.db.QueryRow(ctx, getChainSwapProcessingCheckpoint, chainID)
	var i ChainSwapProcessingCheckpoint
	err := row.Scan(
		&i.ChainID,
		&i.CursorBlockNumber,
		&i.Status,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSwapPairForUpdate = `-- name: GetProjectSwapPairForUpdate :one
SELECT id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
FROM project_swap_pair
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetProjectSwapPairForUpdate(ctx context.Context, projectSwapPairID int64) (ProjectSwapPair, error) {
	row := q.db.QueryRow(ctx, getProjectSwapPairForUpdate, projectSwapPairID)
	var i ProjectSwapPair
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChainID,
		&i.PairKind,
		&i.PairAddress,
		&i.StartBlockNumber,
		&i.StartBlockTime,
		&i.SwapBlockCount,
		&i.Status,
		&i.FirstSwapBlockNumber,
		&i.FirstSwapBlockTime,
		&i.LastSwapBlockNumber,
		&i.LastSwapBlockTime,
		&i.AbsoluteExpiryBlockTime,
		&i.NextExpiryBlockTime,
		&i.CompletedBlockNumber,
		&i.CompletedBlockTime,
		&i.ExpiredBlockNumber,
		&i.ExpiredBlockTime,
		&i.ExpiredReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeChainSwapProcessingCheckpoint = `-- name: InitializeChainSwapProcessingCheckpoint :one
INSERT INTO chain_swap_processing_checkpoint (
  chain_id,
  cursor_block_number,
  initialized
) VALUES (
  $1,
  $2,
  true
)
ON CONFLICT (chain_id) DO UPDATE
SET cursor_block_number = EXCLUDED.cursor_block_number,
  initialized = true,
  updated_at = now()
WHERE NOT chain_swap_processing_checkpoint.initialized
RETURNING chain_id, cursor_block_number, status, initialized, created_at, updated_at
`

type InitializeChainSwapProcessingCheckpointParams struct {
	ChainID           int64
	CursorBlockNumber int64
}

func (q *Queries) InitializeChainSwapProcessingCheckpoint(ctx context.Context, arg InitializeChainSwapProcessingCheckpointParams) (ChainSwapProcessingCheckpoint, error) {
	row := q.db.QueryRow(ctx, initializeChainSwapProcessingCheckpoint, arg.ChainID, arg.CursorBlockNumber)
	var i ChainSwapProcessingCheckpoint
	err := row.Scan(
		&i.ChainID,
		&i.CursorBlockNumber,
		&i.Status,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueCollectingProjectSwapPairsForUpdate = `-- name: ListDueCollectingProjectSwapPairsForUpdate :many
SELECT id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
FROM project_swap_pair
WHERE chain_id = $1
  AND status = 'collecting'
  AND start_block_number <= $2
  AND next_expiry_block_time <= $3::bigint
ORDER BY next_expiry_block_time, id
FOR UPDATE
`

type ListDueCollectingProjectSwapPairsForUpdateParams struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
}

func (q *Queries) ListDueCollectingProjectSwapPairsForUpdate(ctx context.Context, arg ListDueCollectingProjectSwapPairsForUpdateParams) ([]ProjectSwapPair, error) {
	rows, err := q.db.Query(ctx, listDueCollectingProjectSwapPairsForUpdate, arg.ChainID, arg.BlockNumber, arg.BlockTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSwapPair
	for rows.Next() {
		var i ProjectSwapPair
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChainID,
			&i.PairKind,
			&i.PairAddress,
			&i.StartBlockNumber,
			&i.StartBlockTime,
			&i.SwapBlockCount,
			&i.Status,
			&i.FirstSwapBlockNumber,
			&i.FirstSwapBlockTime,
			&i.LastSwapBlockNumber,
			&i.LastSwapBlockTime,
			&i.AbsoluteExpiryBlockTime,
			&i.NextExpiryBlockTime,
			&i.CompletedBlockNumber,
			&i.CompletedBlockTime,
			&i.ExpiredBlockNumber,
			&i.ExpiredBlockTime,
			&i.ExpiredReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingCollectingProjectSwapPairs = `-- name: ListMatchingCollectingProjectSwapPairs :many
SELECT id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
FROM project_swap_pair
WHERE chain_id = $1
  AND status = 'collecting'
  AND start_block_number <= $2
  AND pair_address = ANY($3::bytea[])
ORDER BY pair_address, id
`

type ListMatchingCollectingProjectSwapPairsParams struct {
	ChainID       int64
	BlockNumber   int64
	PairAddresses [][]byte
}

func (q *Queries) ListMatchingCollectingProjectSwapPairs(ctx context.Context, arg ListMatchingCollectingProjectSwapPairsParams) ([]ProjectSwapPair, error) {
	rows, err := q.db.Query(ctx, listMatchingCollectingProjectSwapPairs, arg.ChainID, arg.BlockNumber, arg.PairAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSwapPair
	for rows.Next() {
		var i ProjectSwapPair
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChainID,
			&i.PairKind,
			&i.PairAddress,
			&i.StartBlockNumber,
			&i.StartBlockTime,
			&i.SwapBlockCount,
			&i.Status,
			&i.FirstSwapBlockNumber,
			&i.FirstSwapBlockTime,
			&i.LastSwapBlockNumber,
			&i.LastSwapBlockTime,
			&i.AbsoluteExpiryBlockTime,
			&i.NextExpiryBlockTime,
			&i.CompletedBlockNumber,
			&i.CompletedBlockTime,
			&i.ExpiredBlockNumber,
			&i.ExpiredBlockTime,
			&i.ExpiredReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeProjectSwapPairBlock = `-- name: ObserveProjectSwapPairBlock :one
UPDATE project_swap_pair
SET swap_block_count = swap_block_count + 1,
  first_swap_block_number = COALESCE(first_swap_block_number, $1::bigint),
  first_swap_block_time = COALESCE(first_swap_block_time, $2::bigint),
  last_swap_block_number = $1::bigint,
  last_swap_block_time = $2::bigint,
  next_expiry_block_time = $3::bigint,
  updated_at = now()
WHERE id = $4
  AND status = 'collecting'
  AND swap_block_count < 99
RETURNING id, project_id, chain_id, pair_kind, pair_address, start_block_number, start_block_time, swap_block_count, status, first_swap_block_number, first_swap_block_time, last_swap_block_number, last_swap_block_time, absolute_expiry_block_time, next_expiry_block_time, completed_block_number, completed_block_time, expired_block_number, expired_block_time, expired_reason, created_at, updated_at
`

type ObserveProjectSwapPairBlockParams struct {
	BlockNumber         int64
	BlockTime           int64
	NextExpiryBlockTime int64
	ProjectSwapPairID   int64
}

func (q *Queries) ObserveProjectSwapPairBlock(ctx context.Context, arg ObserveProjectSwapPairBlockParams) (ProjectSwapPair, error) {
	row := q.db.QueryRow(ctx, observeProjectSwapPairBlock,
		arg.BlockNumber,
		arg.BlockTime,
		arg.NextExpiryBlockTime,
		arg.ProjectSwapPairID,
	)
	var i ProjectSwapPair
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChainID,
		&i.PairKind,
		&i.PairAddress,
		&i.StartBlockNumber,
		&i.StartBlockTime,
		&i.SwapBlockCount,
		&i.Status,
		&i.FirstSwapBlockNumber,
		&i.FirstSwapBlockTime,
		&i.LastSwapBlockNumber,
		&i.LastSwapBlockTime,
		&i.AbsoluteExpiryBlockTime,
		&i.NextExpiryBlockTime,
		&i.CompletedBlockNumber,
		&i.CompletedBlockTime,
		&i.ExpiredBlockNumber,
		&i.ExpiredBlockTime,
		&i.ExpiredReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setChainSwapProcessingCheckpointStatus = `-- name: SetChainSwapProcessingCheckpointStatus :one
INSERT INTO chain_swap_processing_checkpoint (
  chain_id,
  status
) VALUES (
  $1,
  $2
)
ON CONFLICT (chain_id) DO UPDATE
SET status = EXCLUDED.status,
  updated_at = now()
RETURNING chain_id, cursor_block_number, status, initialized, created_at, updated_at
`

type SetChainSwapProcessingCheckpointStatusParams struct {
	ChainID int64
	Status  string
}

func (q *Queries) SetChainSwapProcessingCheckpointStatus(ctx context.Context, arg SetChainSwapProcessingCheckpointStatusParams) (ChainSwapProcessingCheckpoint, error) {
	row := q.db.QueryRow(ctx, setChainSwapProcessingCheckpointStatus, arg.ChainID, arg.Status)
	var i ChainSwapProcessingCheckpoint
	err := row.Scan(
		&i.ChainID,
		&i.CursorBlockNumber,
		&i.Status,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
