apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: athena-redis
    app.kubernetes.io/part-of: athena
    app.kubernetes.io/component: redis
  name: athena-redis
spec:
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: athena-redis
