apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: athena-redis
    app.kubernetes.io/part-of: athena
    app.kubernetes.io/component: redis
  name: athena-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: athena-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athena-redis
    spec:
      initContainers:
        - command:
            - athena
            - admin
            - redis-initial-password
          image: quay.io/useryege/athena:latest
          imagePullPolicy: IfNotPresent
          name: secret-init
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: athena-redis        
      containers:
      - name: redis
        image: redis:8.2.3-alpine
        imagePullPolicy: Always
        args:
        - "--save"
        - ""
        - "--appendonly"
        - "no"
        - --requirepass $(REDIS_PASSWORD)
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: auth
                name: athena-redis
        ports:
        - containerPort: 6379
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: athena-redis
              topologyKey: kubernetes.io/hostname
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: athena
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        kubernetes.io/os: linux