apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - athena-redis-deployment.yaml
  - athena-redis-sa.yaml
  - athena-redis-service.yaml
  - athena-redis-network-policy.yaml
  - athena-redis-role.yaml
  - athena-redis-rolebinding.yaml

images:
  - name: redis
    newName: public.ecr.aws/docker/library/redis
