apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- athena-cmd-params-cm.yaml
- athena-cm.yaml
- athena-rbac-cm.yaml
- athena-secret.yaml
- athena-ssh-known-hosts-cm.yaml
- athena-tls-certs-cm.yaml
