syntax = "proto3";

// Application Service
//
// Application Service API returns the list of projects.
package application;

import "github.com/useryege/athena/pkg/apis/application/v1alpha1/generated.proto";
import "google/api/annotations.proto";

option go_package = "github.com/useryege/athena/pkg/apiclient/application";

// ListProjectsRequest queries the current known project snapshot.
message ListProjectsRequest {}

// ListProjectsResponse returns the current known project snapshot.
message ListProjectsResponse {
  repeated github.com.useryege.athena.pkg.apis.application.v1alpha1.ProjectView items = 1;
}

service ApplicationService {
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse) {
    option (google.api.http) = {get: "/api/v1/project/list"};
  }
}
