- op: add
  path: /rules/0
  value:
    apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - athena-redis
    verbs:
      - get
- op: add
  path: /rules/0
  value:
    apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create