// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_center.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountPreferences = `-- name: CreateAccountPreferences :one
INSERT INTO account_preferences (account_id, theme, revision)
VALUES ($1::uuid, $2::text, 1)
ON CONFLICT (account_id) DO NOTHING
RETURNING theme, revision
`

type CreateAccountPreferencesParams struct {
	AccountID pgtype.UUID
	Theme     string
}

type CreateAccountPreferencesRow struct {
	Theme    string
	Revision int64
}

func (q *Queries) CreateAccountPreferences(ctx context.Context, arg CreateAccountPreferencesParams) (CreateAccountPreferencesRow, error) {
	row := q.db.QueryRow(ctx, createAccountPreferences, arg.AccountID, arg.Theme)
	var i CreateAccountPreferencesRow
	err := row.Scan(&i.Theme, &i.Revision)
	return i, err
}

const createAccountProfile = `-- name: CreateAccountProfile :one
INSERT INTO account_profile (
  account_id, display_name, account_tier, avatar_object_key,
  avatar_content_type, avatar_etag, avatar_size_bytes, revision
)
VALUES (
  $1::uuid,
  $2::text,
  $3::text,
  $4::text,
  $5::text,
  $6::text,
  $7::bigint,
  1
)
ON CONFLICT (account_id) DO NOTHING
RETURNING display_name, account_tier, avatar_object_key, avatar_content_type,
          avatar_etag, avatar_size_bytes, revision
`

type CreateAccountProfileParams struct {
	AccountID         pgtype.UUID
	DisplayName       string
	AccountTier       string
	AvatarObjectKey   string
	AvatarContentType string
	AvatarEtag        string
	AvatarSizeBytes   int64
}

type CreateAccountProfileRow struct {
	DisplayName       string
	AccountTier       string
	AvatarObjectKey   string
	AvatarContentType string
	AvatarEtag        string
	AvatarSizeBytes   int64
	Revision          int64
}

func (q *Queries) CreateAccountProfile(ctx context.Context, arg CreateAccountProfileParams) (CreateAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, createAccountProfile,
		arg.AccountID,
		arg.DisplayName,
		arg.AccountTier,
		arg.AvatarObjectKey,
		arg.AvatarContentType,
		arg.AvatarEtag,
		arg.AvatarSizeBytes,
	)
	var i CreateAccountProfileRow
	err := row.Scan(
		&i.DisplayName,
		&i.AccountTier,
		&i.AvatarObjectKey,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSizeBytes,
		&i.Revision,
	)
	return i, err
}

const getAccountPreferences = `-- name: GetAccountPreferences :one
SELECT theme, revision
FROM account_preferences
WHERE account_id = $1::uuid
`

type GetAccountPreferencesRow struct {
	Theme    string
	Revision int64
}

func (q *Queries) GetAccountPreferences(ctx context.Context, accountID pgtype.UUID) (GetAccountPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getAccountPreferences, accountID)
	var i GetAccountPreferencesRow
	err := row.Scan(&i.Theme, &i.Revision)
	return i, err
}

const getAccountProfile = `-- name: GetAccountProfile :one
SELECT display_name, account_tier, avatar_object_key, avatar_content_type,
       avatar_etag, avatar_size_bytes, revision
FROM account_profile
WHERE account_id = $1::uuid
`

type GetAccountProfileRow struct {
	DisplayName       string
	AccountTier       string
	AvatarObjectKey   string
	AvatarContentType string
	AvatarEtag        string
	AvatarSizeBytes   int64
	Revision          int64
}

func (q *Queries) GetAccountProfile(ctx context.Context, accountID pgtype.UUID) (GetAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, accountID)
	var i GetAccountProfileRow
	err := row.Scan(
		&i.DisplayName,
		&i.AccountTier,
		&i.AvatarObjectKey,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSizeBytes,
		&i.Revision,
	)
	return i, err
}

const listAvatarObjectKeys = `-- name: ListAvatarObjectKeys :many
SELECT avatar_object_key
FROM account_profile
WHERE avatar_object_key <> ''
ORDER BY avatar_object_key
`

func (q *Queries) ListAvatarObjectKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAvatarObjectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var avatar_object_key string
		if err := rows.Scan(&avatar_object_key); err != nil {
			return nil, err
		}
		items = append(items, avatar_object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountPreferences = `-- name: UpdateAccountPreferences :one
UPDATE account_preferences
SET theme = $1::text,
    revision = account_preferences.revision + 1,
    updated_at = NOW()
WHERE account_id = $2::uuid
  AND $3::bigint > 0
  AND revision = $3::bigint
RETURNING theme, revision
`

type UpdateAccountPreferencesParams struct {
	Theme            string
	AccountID        pgtype.UUID
	ExpectedRevision int64
}

type UpdateAccountPreferencesRow struct {
	Theme    string
	Revision int64
}

func (q *Queries) UpdateAccountPreferences(ctx context.Context, arg UpdateAccountPreferencesParams) (UpdateAccountPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateAccountPreferences, arg.Theme, arg.AccountID, arg.ExpectedRevision)
	var i UpdateAccountPreferencesRow
	err := row.Scan(&i.Theme, &i.Revision)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE account_profile
SET display_name = $1::text,
    account_tier = $2::text,
    avatar_object_key = $3::text,
    avatar_content_type = $4::text,
    avatar_etag = $5::text,
    avatar_size_bytes = $6::bigint,
    revision = account_profile.revision + 1,
    updated_at = NOW()
WHERE account_id = $7::uuid
  AND $8::bigint > 0
  AND revision = $8::bigint
RETURNING display_name, account_tier, avatar_object_key, avatar_content_type,
          avatar_etag, avatar_size_bytes, revision
`

type UpdateAccountProfileParams struct {
	DisplayName       string
	AccountTier       string
	AvatarObjectKey   string
	AvatarContentType string
	AvatarEtag        string
	AvatarSizeBytes   int64
	AccountID         pgtype.UUID
	ExpectedRevision  int64
}

type UpdateAccountProfileRow struct {
	DisplayName       string
	AccountTier       string
	AvatarObjectKey   string
	AvatarContentType string
	AvatarEtag        string
	AvatarSizeBytes   int64
	Revision          int64
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (UpdateAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.DisplayName,
		arg.AccountTier,
		arg.AvatarObjectKey,
		arg.AvatarContentType,
		arg.AvatarEtag,
		arg.AvatarSizeBytes,
		arg.AccountID,
		arg.ExpectedRevision,
	)
	var i UpdateAccountProfileRow
	err := row.Scan(
		&i.DisplayName,
		&i.AccountTier,
		&i.AvatarObjectKey,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSizeBytes,
		&i.Revision,
	)
	return i, err
}
