// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bytecode struct {
	CodeHash                     []byte
	RuntimeBytecode              []byte
	SourceCode                   pgtype.Text
	SourceCodeHash               []byte
	SourceCodeFetchedAt          pgtype.Timestamptz
	SourceCodeOrigin             pgtype.Text
	SourceQualityReport          pgtype.Text
	SourceQualityReportFetchedAt pgtype.Timestamptz
	SourceQualityReportOrigin    pgtype.Text
	SourceQualityPromptVersion   int64
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type BytecodeBlacklist struct {
	CodeHash       []byte
	Note           pgtype.Text
	SourceChainID  pgtype.Int8
	SourceContract []byte
	CreatedAt      pgtype.Timestamptz
}

type ContractBytecodeDeployment struct {
	ChainID     int64
	Contract    []byte
	CodeHash    []byte
	FirstSeenAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Project struct {
	ID          int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	CreatedAt   pgtype.Timestamptz
}

type ProjectAvePair struct {
	ID              int64
	ProjectContract []byte
	RankIndex       int32
	Reserve0        pgtype.Text
	Reserve1        pgtype.Text
	Token0PriceEth  pgtype.Text
	Token0PriceUsd  pgtype.Text
	Token1PriceEth  pgtype.Text
	Token1PriceUsd  pgtype.Text
	PriceChange     pgtype.Text
	PriceChange24h  pgtype.Text
	PriceChange1h   pgtype.Text
	VolumeU         pgtype.Text
	LowU            pgtype.Text
	HighU           pgtype.Text
	Fee             pgtype.Text
	TotalSupply     pgtype.Text
	TxAmount        pgtype.Text
	Pair            pgtype.Text
	Chain           pgtype.Text
	Amm             pgtype.Text
	Token0Address   pgtype.Text
	Token0Symbol    pgtype.Text
	Token0Decimal   int32
	Token1Address   pgtype.Text
	Token1Symbol    pgtype.Text
	Token1Decimal   int32
	TargetToken     pgtype.Text
	PriceChange1d   pgtype.Text
	CreatedAt       int64
	TxCount         int32
	UpdatedAt       int64
	MarketCap       pgtype.Text
	Fdv             pgtype.Text
	IsFake          bool
	PersistedAt     pgtype.Timestamptz
}

type ProjectAveTokenDetail struct {
	ProjectContract     []byte
	Status              int32
	Msg                 pgtype.Text
	DataType            int32
	IsAudited           bool
	FetchedAt           pgtype.Timestamptz
	Total               pgtype.Text
	LaunchPrice         pgtype.Text
	CurrentPriceEth     pgtype.Text
	CurrentPriceUsd     pgtype.Text
	PriceChange1d       pgtype.Text
	PriceChange24h      pgtype.Text
	PriceChange1h       pgtype.Text
	LockAmount          pgtype.Text
	BurnAmount          pgtype.Text
	OtherAmount         pgtype.Text
	TxAmount24h         pgtype.Text
	TxVolumeU24h        pgtype.Text
	LockedPercent       pgtype.Text
	MarketCap           pgtype.Text
	Fdv                 pgtype.Text
	Tvl                 pgtype.Text
	MainPairTvl         pgtype.Text
	TokenPriceChange5m  pgtype.Text
	TokenPriceChange1h  pgtype.Text
	TokenPriceChange4h  pgtype.Text
	TokenPriceChange24h pgtype.Text
	TokenTxVolumeUsd5m  pgtype.Text
	TokenTxVolumeUsd1h  pgtype.Text
	TokenTxVolumeUsd4h  pgtype.Text
	TokenTxVolumeUsd24h pgtype.Text
	TokenBuyVolumeU5m   pgtype.Text
	TokenSellVolumeU5m  pgtype.Text
	Token               pgtype.Text
	Chain               pgtype.Text
	Decimal             int32
	Name                pgtype.Text
	Symbol              pgtype.Text
	Holders             int32
	Appendix            pgtype.Text
	RiskLevel           int32
	LogoUrl             pgtype.Text
	RiskInfo            pgtype.Text
	RiskScore           pgtype.Text
	LaunchAt            int64
	CreatedAt           int64
	TxCount24h          int32
	LockPlatform        pgtype.Text
	IsMintable          pgtype.Text
	UpdatedAt           int64
	MainPair            pgtype.Text
	HasMintMethod       bool
	IsLpNotLocked       bool
	HasNotRenounced     bool
	HasNotAudited       bool
	HasNotOpenSource    bool
	IsInBlacklist       bool
	IsHoneypot          bool
	AveRiskLevel        int32
}

type ProjectBytecodeFact struct {
	ProjectContract       []byte
	CodeHash              []byte
	IsBytecodeBlacklisted bool
	FetchedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ProjectChainState struct {
	ProjectContract []byte
	ChainState      []byte
	WethPair        []byte
	UsdtPair        []byte
	TokenName       pgtype.Text
	TokenSymbol     pgtype.Text
	FetchedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ProjectComponentState struct {
	ProjectContract []byte
	Component       string
	Status          string
	LastAttemptAt   pgtype.Timestamptz
	LastSuccessAt   pgtype.Timestamptz
	NextRunAt       pgtype.Timestamptz
	LastError       pgtype.Text
	UpdatedAt       pgtype.Timestamptz
}

type ProjectCreatorHistoricalProject struct {
	ID                        int64
	ProjectContract           []byte
	HistoricalProjectContract []byte
	RankIndex                 int32
	CreatedAt                 pgtype.Timestamptz
}

type ProjectGenesisWallet struct {
	ID                int64
	ProjectContract   []byte
	Wallet            []byte
	NetAmount         pgtype.Numeric
	RatioBps          int64
	RankIndex         int32
	TotalSupply       pgtype.Numeric
	SourceTxHash      []byte
	SourceBlockNumber int64
	CreatedAt         pgtype.Timestamptz
}

type ProjectReport struct {
	ProjectContract            []byte
	IsReportEvaluated          bool
	IsReportComplete           bool
	IsBlacklistedCreatorWallet bool
	IsBlacklistedGenesisWallet bool
	IsBlacklistedBytecode      bool
	HasMintRisk                bool
	EvaluatedAt                pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type ProjectSimulationResult struct {
	ProjectContract                    []byte
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	FetchedAt                          pgtype.Timestamptz
	UpdatedAt                          pgtype.Timestamptz
}

type SourceQualityPrompt struct {
	ID           int64
	Version      int64
	Name         string
	SystemPrompt string
	IsActive     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
