// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_candidate.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertProjectCandidate = `-- name: UpsertProjectCandidate :exec
INSERT INTO project_candidate (
  chain_id,
  contract,
  creator,
  tx_hash,
  block_number,
  block_time,
  tx_index,
  weth_pair,
  usdt_pair,
  source,
  status,
  payload
) VALUES (
  $1,
  $2,
  $3::bytea,
  $4::bytea,
  $5::bigint,
  $6::bigint,
  $7::bigint,
  $8::bytea,
  $9::bytea,
  $10,
  'pending',
  $11::jsonb
)
ON CONFLICT (chain_id, contract) DO UPDATE
SET creator = COALESCE(project_candidate.creator, EXCLUDED.creator),
  tx_hash = COALESCE(project_candidate.tx_hash, EXCLUDED.tx_hash),
  block_number = COALESCE(project_candidate.block_number, EXCLUDED.block_number),
  block_time = COALESCE(project_candidate.block_time, EXCLUDED.block_time),
  tx_index = COALESCE(project_candidate.tx_index, EXCLUDED.tx_index),
  weth_pair = COALESCE(project_candidate.weth_pair, EXCLUDED.weth_pair),
  usdt_pair = COALESCE(project_candidate.usdt_pair, EXCLUDED.usdt_pair),
  source = EXCLUDED.source,
  status = CASE
    WHEN project_candidate.status = 'processed' THEN project_candidate.status
    ELSE 'pending'
  END,
  payload = project_candidate.payload || EXCLUDED.payload,
  updated_at = now()
`

type UpsertProjectCandidateParams struct {
	ChainID     int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	BlockNumber pgtype.Int8
	BlockTime   pgtype.Int8
	TxIndex     pgtype.Int8
	WethPair    []byte
	UsdtPair    []byte
	Source      string
	Payload     []byte
}

func (q *Queries) UpsertProjectCandidate(ctx context.Context, arg UpsertProjectCandidateParams) error {
	_, err := q.db.Exec(ctx, upsertProjectCandidate,
		arg.ChainID,
		arg.Contract,
		arg.Creator,
		arg.TxHash,
		arg.BlockNumber,
		arg.BlockTime,
		arg.TxIndex,
		arg.WethPair,
		arg.UsdtPair,
		arg.Source,
		arg.Payload,
	)
	return err
}

const upsertProjectCollectionRequest = `-- name: UpsertProjectCollectionRequest :exec
INSERT INTO project_collection_state (
  project_id,
  status,
  last_requested_at,
  next_run_at
)
SELECT
  id,
  'requested',
  $1::timestamptz,
  $2::timestamptz
FROM project
WHERE chain_id = $3
  AND contract = $4
ON CONFLICT (project_id) DO UPDATE
SET status = EXCLUDED.status,
  last_requested_at = EXCLUDED.last_requested_at,
  next_run_at = EXCLUDED.next_run_at,
  updated_at = now()
`

type UpsertProjectCollectionRequestParams struct {
	RequestedAt     pgtype.Timestamptz
	NextRunAt       pgtype.Timestamptz
	ChainID         int64
	ProjectContract []byte
}

func (q *Queries) UpsertProjectCollectionRequest(ctx context.Context, arg UpsertProjectCollectionRequestParams) error {
	_, err := q.db.Exec(ctx, upsertProjectCollectionRequest,
		arg.RequestedAt,
		arg.NextRunAt,
		arg.ChainID,
		arg.ProjectContract,
	)
	return err
}
