// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)::bigint
FROM project
WHERE chain_id = $1
`

func (q *Queries) CountProjects(ctx context.Context, chainID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, chainID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getMaxProjectBlockNumber = `-- name: GetMaxProjectBlockNumber :one
SELECT
  COALESCE(MAX(block_number), 0)::bigint AS max_block,
  (COUNT(*)::bigint > 0) AS has_value
FROM project
WHERE chain_id = $1
`

type GetMaxProjectBlockNumberRow struct {
	MaxBlock int64
	HasValue bool
}

func (q *Queries) GetMaxProjectBlockNumber(ctx context.Context, chainID int64) (GetMaxProjectBlockNumberRow, error) {
	row := q.db.QueryRow(ctx, getMaxProjectBlockNumber, chainID)
	var i GetMaxProjectBlockNumberRow
	err := row.Scan(&i.MaxBlock, &i.HasValue)
	return i, err
}

const getProjectByContract = `-- name: GetProjectByContract :one
SELECT chain_id, block_number, block_time, contract, creator, tx_hash, tx_index, created_at
FROM project
WHERE chain_id = $1
  AND contract = $2
`

type GetProjectByContractParams struct {
	ChainID  int64
	Contract []byte
}

type GetProjectByContractRow struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProjectByContract(ctx context.Context, arg GetProjectByContractParams) (GetProjectByContractRow, error) {
	row := q.db.QueryRow(ctx, getProjectByContract, arg.ChainID, arg.Contract)
	var i GetProjectByContractRow
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockTime,
		&i.Contract,
		&i.Creator,
		&i.TxHash,
		&i.TxIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMetaByContract = `-- name: GetProjectMetaByContract :one
SELECT
  p.chain_id,
  p.block_number,
  p.block_time,
  p.contract,
  p.creator,
  COALESCE(cs.weth_pair, p.weth_pair, decode(repeat('00', 20), 'hex')) AS weth_pair,
  COALESCE(cs.usdt_pair, p.usdt_pair, decode(repeat('00', 20), 'hex')) AS usdt_pair,
  COALESCE(cs.fetched_at, p.created_at) AS fetch_at,
  p.tx_hash,
  p.tx_index,
  COALESCE(sr.can_mint_from_dead_via_transfer_from, false) AS can_mint_from_dead_via_transfer_from,
  COALESCE(sr.can_mint_from_zero_via_transfer_from, false) AS can_mint_from_zero_via_transfer_from,
  COALESCE(sr.can_mint_from_weth_pair_via_transfer_from, false) AS can_mint_from_weth_pair_via_transfer_from,
  COALESCE(sr.can_mint_from_usdt_pair_via_transfer_from, false) AS can_mint_from_usdt_pair_via_transfer_from,
  COALESCE(sr.can_mint_via_transfer_to_weth_pair, false) AS can_mint_via_transfer_to_weth_pair,
  COALESCE(sr.can_mint_via_transfer_to_usdt_pair, false) AS can_mint_via_transfer_to_usdt_pair,
  gw.last_success_at AS genesis_wallets_fetched_at,
  ch.last_success_at AS creator_historical_projects_fetched_at
FROM project p
LEFT JOIN project_chain_state cs ON cs.project_id = p.id
LEFT JOIN project_simulation_result sr ON sr.project_id = p.id
LEFT JOIN project_component_state gw ON gw.project_id = p.id AND gw.component = 'genesis_wallet'
LEFT JOIN project_component_state ch ON ch.project_id = p.id AND ch.component = 'creator_history'
WHERE p.chain_id = $1
  AND p.contract = $2
`

type GetProjectMetaByContractParams struct {
	ChainID  int64
	Contract []byte
}

type GetProjectMetaByContractRow struct {
	ChainID                            int64
	BlockNumber                        int64
	BlockTime                          int64
	Contract                           []byte
	Creator                            []byte
	WethPair                           []byte
	UsdtPair                           []byte
	FetchAt                            pgtype.Timestamptz
	TxHash                             []byte
	TxIndex                            int64
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	GenesisWalletsFetchedAt            pgtype.Timestamptz
	CreatorHistoricalProjectsFetchedAt pgtype.Timestamptz
}

func (q *Queries) GetProjectMetaByContract(ctx context.Context, arg GetProjectMetaByContractParams) (GetProjectMetaByContractRow, error) {
	row := q.db.QueryRow(ctx, getProjectMetaByContract, arg.ChainID, arg.Contract)
	var i GetProjectMetaByContractRow
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockTime,
		&i.Contract,
		&i.Creator,
		&i.WethPair,
		&i.UsdtPair,
		&i.FetchAt,
		&i.TxHash,
		&i.TxIndex,
		&i.CanMintFromDeadViaTransferFrom,
		&i.CanMintFromZeroViaTransferFrom,
		&i.CanMintFromWethPairViaTransferFrom,
		&i.CanMintFromUsdtPairViaTransferFrom,
		&i.CanMintViaTransferToWethPair,
		&i.CanMintViaTransferToUsdtPair,
		&i.GenesisWalletsFetchedAt,
		&i.CreatorHistoricalProjectsFetchedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO project (
  chain_id,
  block_number,
  block_time,
  contract,
  creator,
  tx_hash,
  tx_index
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
`

type InsertProjectParams struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockTime,
		arg.Contract,
		arg.Creator,
		arg.TxHash,
		arg.TxIndex,
	)
	return err
}

const listProjectMetas = `-- name: ListProjectMetas :many
SELECT
  p.chain_id,
  p.block_number,
  p.block_time,
  p.contract,
  p.creator,
  COALESCE(cs.weth_pair, p.weth_pair, decode(repeat('00', 20), 'hex')) AS weth_pair,
  COALESCE(cs.usdt_pair, p.usdt_pair, decode(repeat('00', 20), 'hex')) AS usdt_pair,
  COALESCE(cs.fetched_at, p.created_at) AS fetch_at,
  p.tx_hash,
  p.tx_index,
  COALESCE(sr.can_mint_from_dead_via_transfer_from, false) AS can_mint_from_dead_via_transfer_from,
  COALESCE(sr.can_mint_from_zero_via_transfer_from, false) AS can_mint_from_zero_via_transfer_from,
  COALESCE(sr.can_mint_from_weth_pair_via_transfer_from, false) AS can_mint_from_weth_pair_via_transfer_from,
  COALESCE(sr.can_mint_from_usdt_pair_via_transfer_from, false) AS can_mint_from_usdt_pair_via_transfer_from,
  COALESCE(sr.can_mint_via_transfer_to_weth_pair, false) AS can_mint_via_transfer_to_weth_pair,
  COALESCE(sr.can_mint_via_transfer_to_usdt_pair, false) AS can_mint_via_transfer_to_usdt_pair,
  gw.last_success_at AS genesis_wallets_fetched_at,
  ch.last_success_at AS creator_historical_projects_fetched_at
FROM project p
LEFT JOIN project_chain_state cs ON cs.project_id = p.id
LEFT JOIN project_simulation_result sr ON sr.project_id = p.id
LEFT JOIN project_component_state gw ON gw.project_id = p.id AND gw.component = 'genesis_wallet'
LEFT JOIN project_component_state ch ON ch.project_id = p.id AND ch.component = 'creator_history'
WHERE p.chain_id = $1
ORDER BY p.block_number, p.tx_index, p.id
`

type ListProjectMetasRow struct {
	ChainID                            int64
	BlockNumber                        int64
	BlockTime                          int64
	Contract                           []byte
	Creator                            []byte
	WethPair                           []byte
	UsdtPair                           []byte
	FetchAt                            pgtype.Timestamptz
	TxHash                             []byte
	TxIndex                            int64
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	GenesisWalletsFetchedAt            pgtype.Timestamptz
	CreatorHistoricalProjectsFetchedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectMetas(ctx context.Context, chainID int64) ([]ListProjectMetasRow, error) {
	rows, err := q.db.Query(ctx, listProjectMetas, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMetasRow
	for rows.Next() {
		var i ListProjectMetasRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.WethPair,
			&i.UsdtPair,
			&i.FetchAt,
			&i.TxHash,
			&i.TxIndex,
			&i.CanMintFromDeadViaTransferFrom,
			&i.CanMintFromZeroViaTransferFrom,
			&i.CanMintFromWethPairViaTransferFrom,
			&i.CanMintFromUsdtPairViaTransferFrom,
			&i.CanMintViaTransferToWethPair,
			&i.CanMintViaTransferToUsdtPair,
			&i.GenesisWalletsFetchedAt,
			&i.CreatorHistoricalProjectsFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMetasByCreator = `-- name: ListProjectMetasByCreator :many
SELECT
  p.chain_id,
  p.block_number,
  p.block_time,
  p.contract,
  p.creator,
  COALESCE(cs.weth_pair, p.weth_pair, decode(repeat('00', 20), 'hex')) AS weth_pair,
  COALESCE(cs.usdt_pair, p.usdt_pair, decode(repeat('00', 20), 'hex')) AS usdt_pair,
  COALESCE(cs.fetched_at, p.created_at) AS fetch_at,
  p.tx_hash,
  p.tx_index,
  COALESCE(sr.can_mint_from_dead_via_transfer_from, false) AS can_mint_from_dead_via_transfer_from,
  COALESCE(sr.can_mint_from_zero_via_transfer_from, false) AS can_mint_from_zero_via_transfer_from,
  COALESCE(sr.can_mint_from_weth_pair_via_transfer_from, false) AS can_mint_from_weth_pair_via_transfer_from,
  COALESCE(sr.can_mint_from_usdt_pair_via_transfer_from, false) AS can_mint_from_usdt_pair_via_transfer_from,
  COALESCE(sr.can_mint_via_transfer_to_weth_pair, false) AS can_mint_via_transfer_to_weth_pair,
  COALESCE(sr.can_mint_via_transfer_to_usdt_pair, false) AS can_mint_via_transfer_to_usdt_pair,
  gw.last_success_at AS genesis_wallets_fetched_at,
  ch.last_success_at AS creator_historical_projects_fetched_at
FROM project p
LEFT JOIN project_chain_state cs ON cs.project_id = p.id
LEFT JOIN project_simulation_result sr ON sr.project_id = p.id
LEFT JOIN project_component_state gw ON gw.project_id = p.id AND gw.component = 'genesis_wallet'
LEFT JOIN project_component_state ch ON ch.project_id = p.id AND ch.component = 'creator_history'
WHERE p.chain_id = $1
  AND p.creator = $2
ORDER BY p.block_number, p.tx_index, p.id
`

type ListProjectMetasByCreatorParams struct {
	ChainID int64
	Creator []byte
}

type ListProjectMetasByCreatorRow struct {
	ChainID                            int64
	BlockNumber                        int64
	BlockTime                          int64
	Contract                           []byte
	Creator                            []byte
	WethPair                           []byte
	UsdtPair                           []byte
	FetchAt                            pgtype.Timestamptz
	TxHash                             []byte
	TxIndex                            int64
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	GenesisWalletsFetchedAt            pgtype.Timestamptz
	CreatorHistoricalProjectsFetchedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectMetasByCreator(ctx context.Context, arg ListProjectMetasByCreatorParams) ([]ListProjectMetasByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listProjectMetasByCreator, arg.ChainID, arg.Creator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMetasByCreatorRow
	for rows.Next() {
		var i ListProjectMetasByCreatorRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.WethPair,
			&i.UsdtPair,
			&i.FetchAt,
			&i.TxHash,
			&i.TxIndex,
			&i.CanMintFromDeadViaTransferFrom,
			&i.CanMintFromZeroViaTransferFrom,
			&i.CanMintFromWethPairViaTransferFrom,
			&i.CanMintFromUsdtPairViaTransferFrom,
			&i.CanMintViaTransferToWethPair,
			&i.CanMintViaTransferToUsdtPair,
			&i.GenesisWalletsFetchedAt,
			&i.CreatorHistoricalProjectsFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMetasByCreatorBefore = `-- name: ListProjectMetasByCreatorBefore :many
SELECT
  p.chain_id,
  p.block_number,
  p.block_time,
  p.contract,
  p.creator,
  COALESCE(cs.weth_pair, p.weth_pair, decode(repeat('00', 20), 'hex')) AS weth_pair,
  COALESCE(cs.usdt_pair, p.usdt_pair, decode(repeat('00', 20), 'hex')) AS usdt_pair,
  COALESCE(cs.fetched_at, p.created_at) AS fetch_at,
  p.tx_hash,
  p.tx_index,
  COALESCE(sr.can_mint_from_dead_via_transfer_from, false) AS can_mint_from_dead_via_transfer_from,
  COALESCE(sr.can_mint_from_zero_via_transfer_from, false) AS can_mint_from_zero_via_transfer_from,
  COALESCE(sr.can_mint_from_weth_pair_via_transfer_from, false) AS can_mint_from_weth_pair_via_transfer_from,
  COALESCE(sr.can_mint_from_usdt_pair_via_transfer_from, false) AS can_mint_from_usdt_pair_via_transfer_from,
  COALESCE(sr.can_mint_via_transfer_to_weth_pair, false) AS can_mint_via_transfer_to_weth_pair,
  COALESCE(sr.can_mint_via_transfer_to_usdt_pair, false) AS can_mint_via_transfer_to_usdt_pair,
  gw.last_success_at AS genesis_wallets_fetched_at,
  ch.last_success_at AS creator_historical_projects_fetched_at
FROM project p
LEFT JOIN project_chain_state cs ON cs.project_id = p.id
LEFT JOIN project_simulation_result sr ON sr.project_id = p.id
LEFT JOIN project_component_state gw ON gw.project_id = p.id AND gw.component = 'genesis_wallet'
LEFT JOIN project_component_state ch ON ch.project_id = p.id AND ch.component = 'creator_history'
WHERE p.chain_id = $1
  AND p.creator = $2
  AND (p.block_number < $3 OR (p.block_number = $3 AND p.tx_index < $4))
ORDER BY p.block_number, p.tx_index, p.id
`

type ListProjectMetasByCreatorBeforeParams struct {
	ChainID     int64
	Creator     []byte
	BlockNumber int64
	TxIndex     int64
}

type ListProjectMetasByCreatorBeforeRow struct {
	ChainID                            int64
	BlockNumber                        int64
	BlockTime                          int64
	Contract                           []byte
	Creator                            []byte
	WethPair                           []byte
	UsdtPair                           []byte
	FetchAt                            pgtype.Timestamptz
	TxHash                             []byte
	TxIndex                            int64
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	GenesisWalletsFetchedAt            pgtype.Timestamptz
	CreatorHistoricalProjectsFetchedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectMetasByCreatorBefore(ctx context.Context, arg ListProjectMetasByCreatorBeforeParams) ([]ListProjectMetasByCreatorBeforeRow, error) {
	rows, err := q.db.Query(ctx, listProjectMetasByCreatorBefore,
		arg.ChainID,
		arg.Creator,
		arg.BlockNumber,
		arg.TxIndex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMetasByCreatorBeforeRow
	for rows.Next() {
		var i ListProjectMetasByCreatorBeforeRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.WethPair,
			&i.UsdtPair,
			&i.FetchAt,
			&i.TxHash,
			&i.TxIndex,
			&i.CanMintFromDeadViaTransferFrom,
			&i.CanMintFromZeroViaTransferFrom,
			&i.CanMintFromWethPairViaTransferFrom,
			&i.CanMintFromUsdtPairViaTransferFrom,
			&i.CanMintViaTransferToWethPair,
			&i.CanMintViaTransferToUsdtPair,
			&i.GenesisWalletsFetchedAt,
			&i.CreatorHistoricalProjectsFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMetasByPairAddresses = `-- name: ListProjectMetasByPairAddresses :many
SELECT
  p.chain_id,
  p.block_number,
  p.block_time,
  p.contract,
  p.creator,
  COALESCE(cs.weth_pair, p.weth_pair, decode(repeat('00', 20), 'hex')) AS weth_pair,
  COALESCE(cs.usdt_pair, p.usdt_pair, decode(repeat('00', 20), 'hex')) AS usdt_pair,
  COALESCE(cs.fetched_at, p.created_at) AS fetch_at,
  p.tx_hash,
  p.tx_index,
  COALESCE(sr.can_mint_from_dead_via_transfer_from, false) AS can_mint_from_dead_via_transfer_from,
  COALESCE(sr.can_mint_from_zero_via_transfer_from, false) AS can_mint_from_zero_via_transfer_from,
  COALESCE(sr.can_mint_from_weth_pair_via_transfer_from, false) AS can_mint_from_weth_pair_via_transfer_from,
  COALESCE(sr.can_mint_from_usdt_pair_via_transfer_from, false) AS can_mint_from_usdt_pair_via_transfer_from,
  COALESCE(sr.can_mint_via_transfer_to_weth_pair, false) AS can_mint_via_transfer_to_weth_pair,
  COALESCE(sr.can_mint_via_transfer_to_usdt_pair, false) AS can_mint_via_transfer_to_usdt_pair,
  gw.last_success_at AS genesis_wallets_fetched_at,
  ch.last_success_at AS creator_historical_projects_fetched_at
FROM project p
LEFT JOIN project_chain_state cs ON cs.project_id = p.id
LEFT JOIN project_simulation_result sr ON sr.project_id = p.id
LEFT JOIN project_component_state gw ON gw.project_id = p.id AND gw.component = 'genesis_wallet'
LEFT JOIN project_component_state ch ON ch.project_id = p.id AND ch.component = 'creator_history'
WHERE p.chain_id = $1
  AND (cs.weth_pair = ANY($2::bytea[])
    OR cs.usdt_pair = ANY($2::bytea[])
    OR p.weth_pair = ANY($2::bytea[])
    OR p.usdt_pair = ANY($2::bytea[]))
ORDER BY p.block_number, p.tx_index, p.id
`

type ListProjectMetasByPairAddressesParams struct {
	ChainID int64
	Pairs   [][]byte
}

type ListProjectMetasByPairAddressesRow struct {
	ChainID                            int64
	BlockNumber                        int64
	BlockTime                          int64
	Contract                           []byte
	Creator                            []byte
	WethPair                           []byte
	UsdtPair                           []byte
	FetchAt                            pgtype.Timestamptz
	TxHash                             []byte
	TxIndex                            int64
	CanMintFromDeadViaTransferFrom     bool
	CanMintFromZeroViaTransferFrom     bool
	CanMintFromWethPairViaTransferFrom bool
	CanMintFromUsdtPairViaTransferFrom bool
	CanMintViaTransferToWethPair       bool
	CanMintViaTransferToUsdtPair       bool
	GenesisWalletsFetchedAt            pgtype.Timestamptz
	CreatorHistoricalProjectsFetchedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectMetasByPairAddresses(ctx context.Context, arg ListProjectMetasByPairAddressesParams) ([]ListProjectMetasByPairAddressesRow, error) {
	rows, err := q.db.Query(ctx, listProjectMetasByPairAddresses, arg.ChainID, arg.Pairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMetasByPairAddressesRow
	for rows.Next() {
		var i ListProjectMetasByPairAddressesRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.WethPair,
			&i.UsdtPair,
			&i.FetchAt,
			&i.TxHash,
			&i.TxIndex,
			&i.CanMintFromDeadViaTransferFrom,
			&i.CanMintFromZeroViaTransferFrom,
			&i.CanMintFromWethPairViaTransferFrom,
			&i.CanMintFromUsdtPairViaTransferFrom,
			&i.CanMintViaTransferToWethPair,
			&i.CanMintViaTransferToUsdtPair,
			&i.GenesisWalletsFetchedAt,
			&i.CreatorHistoricalProjectsFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT chain_id, block_number, block_time, contract, creator, tx_hash, tx_index, created_at
FROM project
WHERE chain_id = $1
ORDER BY block_number, tx_index, id
`

type ListProjectsRow struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProjects(ctx context.Context, chainID int64) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.TxHash,
			&i.TxIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByCreatorBefore = `-- name: ListProjectsByCreatorBefore :many
SELECT chain_id, block_number, block_time, contract, creator, tx_hash, tx_index, created_at
FROM project
WHERE chain_id = $1
  AND creator = $2
  AND (block_number < $3 OR (block_number = $3 AND tx_index < $4))
ORDER BY block_number, tx_index, id
`

type ListProjectsByCreatorBeforeParams struct {
	ChainID     int64
	Creator     []byte
	BlockNumber int64
	TxIndex     int64
}

type ListProjectsByCreatorBeforeRow struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProjectsByCreatorBefore(ctx context.Context, arg ListProjectsByCreatorBeforeParams) ([]ListProjectsByCreatorBeforeRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByCreatorBefore,
		arg.ChainID,
		arg.Creator,
		arg.BlockNumber,
		arg.TxIndex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByCreatorBeforeRow
	for rows.Next() {
		var i ListProjectsByCreatorBeforeRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.TxHash,
			&i.TxIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsPage = `-- name: ListProjectsPage :many
SELECT chain_id, block_number, block_time, contract, creator, tx_hash, tx_index, created_at
FROM project
WHERE chain_id = $1
ORDER BY block_number, tx_index, id
LIMIT $3 OFFSET $2
`

type ListProjectsPageParams struct {
	ChainID     int64
	OffsetCount int32
	LimitCount  int32
}

type ListProjectsPageRow struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProjectsPage(ctx context.Context, arg ListProjectsPageParams) ([]ListProjectsPageRow, error) {
	rows, err := q.db.Query(ctx, listProjectsPage, arg.ChainID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsPageRow
	for rows.Next() {
		var i ListProjectsPageRow
		if err := rows.Scan(
			&i.ChainID,
			&i.BlockNumber,
			&i.BlockTime,
			&i.Contract,
			&i.Creator,
			&i.TxHash,
			&i.TxIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectFromDiscovery = `-- name: UpsertProjectFromDiscovery :exec
INSERT INTO project (
  chain_id,
  block_number,
  block_time,
  contract,
  creator,
  tx_hash,
  tx_index,
  weth_pair,
  usdt_pair,
  source,
  status,
  reason,
  payload,
  discovered_at,
  code_hash
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8::bytea,
  $9::bytea,
  $10,
  'processed',
  $11::text,
  $12::jsonb,
  now(),
  (
    SELECT d.code_hash
    FROM contract_bytecode_deployment d
    WHERE d.chain_id = $1
      AND d.contract = $4
  )
)
ON CONFLICT (chain_id, contract) DO UPDATE
SET weth_pair = COALESCE(project.weth_pair, EXCLUDED.weth_pair),
  usdt_pair = COALESCE(project.usdt_pair, EXCLUDED.usdt_pair),
  code_hash = COALESCE(EXCLUDED.code_hash, project.code_hash),
  source = EXCLUDED.source,
  status = 'processed',
  reason = COALESCE(EXCLUDED.reason, project.reason),
  payload = project.payload || EXCLUDED.payload,
  updated_at = now()
`

type UpsertProjectFromDiscoveryParams struct {
	ChainID     int64
	BlockNumber int64
	BlockTime   int64
	Contract    []byte
	Creator     []byte
	TxHash      []byte
	TxIndex     int64
	WethPair    []byte
	UsdtPair    []byte
	Source      string
	Reason      pgtype.Text
	Payload     []byte
}

func (q *Queries) UpsertProjectFromDiscovery(ctx context.Context, arg UpsertProjectFromDiscoveryParams) error {
	_, err := q.db.Exec(ctx, upsertProjectFromDiscovery,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockTime,
		arg.Contract,
		arg.Creator,
		arg.TxHash,
		arg.TxIndex,
		arg.WethPair,
		arg.UsdtPair,
		arg.Source,
		arg.Reason,
		arg.Payload,
	)
	return err
}
