// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_access_override.sql

package sqlc

import (
	"context"
)

const createAccountAccessOverrideHead = `-- name: CreateAccountAccessOverrideHead :one
INSERT INTO account_access_override (
  account_name,
  login_enabled,
  revision
)
VALUES (
  $1::text,
  $2::boolean,
  1
)
ON CONFLICT (account_name) DO NOTHING
RETURNING account_name, login_enabled, revision
`

type CreateAccountAccessOverrideHeadParams struct {
	AccountName  string
	LoginEnabled bool
}

type CreateAccountAccessOverrideHeadRow struct {
	AccountName  string
	LoginEnabled bool
	Revision     int64
}

func (q *Queries) CreateAccountAccessOverrideHead(ctx context.Context, arg CreateAccountAccessOverrideHeadParams) (CreateAccountAccessOverrideHeadRow, error) {
	row := q.db.QueryRow(ctx, createAccountAccessOverrideHead, arg.AccountName, arg.LoginEnabled)
	var i CreateAccountAccessOverrideHeadRow
	err := row.Scan(&i.AccountName, &i.LoginEnabled, &i.Revision)
	return i, err
}

const listAccountAccessOverrideHeads = `-- name: ListAccountAccessOverrideHeads :many
SELECT account_name, login_enabled, revision
FROM account_access_override
ORDER BY account_name
`

type ListAccountAccessOverrideHeadsRow struct {
	AccountName  string
	LoginEnabled bool
	Revision     int64
}

func (q *Queries) ListAccountAccessOverrideHeads(ctx context.Context) ([]ListAccountAccessOverrideHeadsRow, error) {
	rows, err := q.db.Query(ctx, listAccountAccessOverrideHeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountAccessOverrideHeadsRow
	for rows.Next() {
		var i ListAccountAccessOverrideHeadsRow
		if err := rows.Scan(&i.AccountName, &i.LoginEnabled, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountModuleAccessOverrides = `-- name: ListAccountModuleAccessOverrides :many
SELECT account_name, module, access_level
FROM account_module_access_override
ORDER BY account_name, module
`

func (q *Queries) ListAccountModuleAccessOverrides(ctx context.Context) ([]AccountModuleAccessOverride, error) {
	rows, err := q.db.Query(ctx, listAccountModuleAccessOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountModuleAccessOverride
	for rows.Next() {
		var i AccountModuleAccessOverride
		if err := rows.Scan(&i.AccountName, &i.Module, &i.AccessLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountAccessOverrideHead = `-- name: UpdateAccountAccessOverrideHead :one
UPDATE account_access_override
SET login_enabled = $1::boolean,
    revision = account_access_override.revision + 1,
    updated_at = NOW()
WHERE account_name = $2::text
  AND $3::bigint > 0
  AND revision = $3::bigint
RETURNING account_name, login_enabled, revision
`

type UpdateAccountAccessOverrideHeadParams struct {
	LoginEnabled     bool
	AccountName      string
	ExpectedRevision int64
}

type UpdateAccountAccessOverrideHeadRow struct {
	AccountName  string
	LoginEnabled bool
	Revision     int64
}

func (q *Queries) UpdateAccountAccessOverrideHead(ctx context.Context, arg UpdateAccountAccessOverrideHeadParams) (UpdateAccountAccessOverrideHeadRow, error) {
	row := q.db.QueryRow(ctx, updateAccountAccessOverrideHead, arg.LoginEnabled, arg.AccountName, arg.ExpectedRevision)
	var i UpdateAccountAccessOverrideHeadRow
	err := row.Scan(&i.AccountName, &i.LoginEnabled, &i.Revision)
	return i, err
}

const upsertAccountModuleAccessOverrides = `-- name: UpsertAccountModuleAccessOverrides :exec
INSERT INTO account_module_access_override (
  account_name,
  module,
  access_level
)
VALUES
  ($1::text, 'market_radar', $2::text),
  ($1::text, 'sports_live', $3::text),
  ($1::text, 'sports_history', $4::text),
  ($1::text, 'managed_oo', $5::text),
  ($1::text, 'worm_markets', $6::text),
  ($1::text, 'fifa_market_dashboard', $7::text),
  ($1::text, 'world_cup_corners', $8::text),
  ($1::text, 'token', $9::text),
  ($1::text, 'wallet', $10::text),
  ($1::text, 'notifications', $11::text)
ON CONFLICT (account_name, module) DO UPDATE
SET access_level = EXCLUDED.access_level
`

type UpsertAccountModuleAccessOverridesParams struct {
	AccountName                    string
	MarketRadarAccessLevel         string
	SportsLiveAccessLevel          string
	SportsHistoryAccessLevel       string
	ManagedOoAccessLevel           string
	WormMarketsAccessLevel         string
	FifaMarketDashboardAccessLevel string
	WorldCupCornersAccessLevel     string
	TokenAccessLevel               string
	WalletAccessLevel              string
	NotificationsAccessLevel       string
}

func (q *Queries) UpsertAccountModuleAccessOverrides(ctx context.Context, arg UpsertAccountModuleAccessOverridesParams) error {
	_, err := q.db.Exec(ctx, upsertAccountModuleAccessOverrides,
		arg.AccountName,
		arg.MarketRadarAccessLevel,
		arg.SportsLiveAccessLevel,
		arg.SportsHistoryAccessLevel,
		arg.ManagedOoAccessLevel,
		arg.WormMarketsAccessLevel,
		arg.FifaMarketDashboardAccessLevel,
		arg.WorldCupCornersAccessLevel,
		arg.TokenAccessLevel,
		arg.WalletAccessLevel,
		arg.NotificationsAccessLevel,
	)
	return err
}
