apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- athena-server-deployment.yaml
- athena-server-role.yaml
- athena-server-rolebinding.yaml
- athena-server-sa.yaml
- athena-server-service.yaml
- athena-server-metrics.yaml
- athena-server-network-policy.yaml